// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: svapi/base.proto

package svapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_DESC SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortOrder_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_svapi_base_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_svapi_base_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{0}
}

type SearchOperator int32

const (
	SearchOperator_EQ       SearchOperator = 0  // 等于
	SearchOperator_NE       SearchOperator = 1  // 不等于
	SearchOperator_GT       SearchOperator = 2  // 大于
	SearchOperator_GE       SearchOperator = 3  // 大于等于
	SearchOperator_LT       SearchOperator = 4  // 小于
	SearchOperator_LE       SearchOperator = 5  // 小于等于
	SearchOperator_LIKE     SearchOperator = 6  // 使用like的模糊匹配
	SearchOperator_WILDCARD SearchOperator = 7  // 使用通配符的模糊匹配
	SearchOperator_IN       SearchOperator = 8  // 在指定的集合中
	SearchOperator_NOT_IN   SearchOperator = 9  // 不在指定的集合中
	SearchOperator_BETWEEN  SearchOperator = 10 // 在指定的范围内
	SearchOperator_RE       SearchOperator = 11 // 正则匹配
)

// Enum value maps for SearchOperator.
var (
	SearchOperator_name = map[int32]string{
		0:  "EQ",
		1:  "NE",
		2:  "GT",
		3:  "GE",
		4:  "LT",
		5:  "LE",
		6:  "LIKE",
		7:  "WILDCARD",
		8:  "IN",
		9:  "NOT_IN",
		10: "BETWEEN",
		11: "RE",
	}
	SearchOperator_value = map[string]int32{
		"EQ":       0,
		"NE":       1,
		"GT":       2,
		"GE":       3,
		"LT":       4,
		"LE":       5,
		"LIKE":     6,
		"WILDCARD": 7,
		"IN":       8,
		"NOT_IN":   9,
		"BETWEEN":  10,
		"RE":       11,
	}
)

func (x SearchOperator) Enum() *SearchOperator {
	p := new(SearchOperator)
	*p = x
	return p
}

func (x SearchOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_svapi_base_proto_enumTypes[1].Descriptor()
}

func (SearchOperator) Type() protoreflect.EnumType {
	return &file_svapi_base_proto_enumTypes[1]
}

func (x SearchOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchOperator.Descriptor instead.
func (SearchOperator) EnumDescriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{1}
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizCode       int32                  `protobuf:"varint,1,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason        []string               `protobuf:"bytes,4,rep,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_svapi_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetBizCode() int32 {
	if x != nil {
		return x.BizCode
	}
	return 0
}

func (x *Metadata) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Metadata) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Metadata) GetReason() []string {
	if x != nil {
		return x.Reason
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                       // 用于排序的字段名称
	Order         SortOrder              `protobuf:"varint,2,opt,name=order,proto3,enum=svapi.SortOrder" json:"order,omitempty"` // 排序方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_svapi_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{1}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_ASC
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码 [1, +∞)
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 页面大小
	Sort          []*SortField           `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`  // 根据字段进行排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_svapi_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PaginationRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 当前数据的所属页码
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总页数
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 总条目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_svapi_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                                  // 用于搜索的字段名称
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                  // 搜索的值
	ValueList     []string               `protobuf:"bytes,3,rep,name=value_list,json=valueList,proto3" json:"value_list,omitempty"`         // 搜索的值列表
	Operator      SearchOperator         `protobuf:"varint,4,opt,name=operator,proto3,enum=svapi.SearchOperator" json:"operator,omitempty"` // 操作符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchField) Reset() {
	*x = SearchField{}
	mi := &file_svapi_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchField) ProtoMessage() {}

func (x *SearchField) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchField.ProtoReflect.Descriptor instead.
func (*SearchField) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{4}
}

func (x *SearchField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchField) GetValueList() []string {
	if x != nil {
		return x.ValueList
	}
	return nil
}

func (x *SearchField) GetOperator() SearchOperator {
	if x != nil {
		return x.Operator
	}
	return SearchOperator_EQ
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        []*SearchField         `protobuf:"bytes,1,rep,name=search,proto3" json:"search,omitempty"` // 搜索条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_svapi_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetSearch() []*SearchField {
	if x != nil {
		return x.Search
	}
	return nil
}

type VideoAuthor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsFollowing   bool   `protobuf:"varint,4,opt,name=isFollowing,proto3" json:"isFollowing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoAuthor) Reset() {
	*x = VideoAuthor{}
	mi := &file_svapi_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoAuthor) ProtoMessage() {}

func (x *VideoAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoAuthor.ProtoReflect.Descriptor instead.
func (*VideoAuthor) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{6}
}

func (x *VideoAuthor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoAuthor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VideoAuthor) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *VideoAuthor) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type Video struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id       int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`                            // 视频唯一标识
	Author   *VideoAuthor `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`                     // 视频作者信息
	PlayUrl  string       `protobuf:"bytes,3,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`    // 视频播放地址
	CoverUrl string       `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 视频封面地址
	// @gotags: json:"favoriteCount,omitempty,string"
	FavoriteCount int64 `protobuf:"varint,5,opt,name=favoriteCount,proto3" json:"favoriteCount,omitempty,string"` // 视频的点赞总数
	// @gotags: json:"commentCount,omitempty,string"
	CommentCount int64  `protobuf:"varint,6,opt,name=commentCount,proto3" json:"commentCount,omitempty,string"` // 视频的评论总数
	IsFavorite   bool   `protobuf:"varint,7,opt,name=isFavorite,proto3" json:"isFavorite,omitempty"`     // true-已点赞，false-未点赞
	Title        string `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`                // 视频标题
	IsCollected  bool   `protobuf:"varint,9,opt,name=isCollected,proto3" json:"isCollected,omitempty"`   // 是否已收藏
	// @gotags: json:"collectedCount,omitempty,string"
	CollectedCount int64 `protobuf:"varint,10,opt,name=collectedCount,proto3" json:"collectedCount,omitempty,string"` // 收藏数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_svapi_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_svapi_base_proto_rawDescGZIP(), []int{7}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetAuthor() *VideoAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

func (x *Video) GetCollectedCount() int64 {
	if x != nil {
		return x.CollectedCount
	}
	return 0
}

var File_svapi_base_proto protoreflect.FileDescriptor

const file_svapi_base_proto_rawDesc = "" +
	"\n" +
	"\x10svapi/base.proto\x12\x05svapi\"o\n" +
	"\bMetadata\x12\x19\n" +
	"\bbiz_code\x18\x01 \x01(\x05R\abizCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x04 \x03(\tR\x06reason\"I\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12&\n" +
	"\x05order\x18\x02 \x01(\x0e2\x10.svapi.SortOrderR\x05order\"a\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12$\n" +
	"\x04sort\x18\x03 \x03(\v2\x10.svapi.SortFieldR\x04sort\"T\n" +
	"\x12PaginationResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x8b\x01\n" +
	"\vSearchField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"value_list\x18\x03 \x03(\tR\tvalueList\x121\n" +
	"\boperator\x18\x04 \x01(\x0e2\x15.svapi.SearchOperatorR\boperator\";\n" +
	"\rSearchRequest\x12*\n" +
	"\x06search\x18\x01 \x03(\v2\x12.svapi.SearchFieldR\x06search\"k\n" +
	"\vVideoAuthor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\visFollowing\x18\x04 \x01(\bR\visFollowing\"\xc5\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x06author\x18\x02 \x01(\v2\x12.svapi.VideoAuthorR\x06author\x12\x19\n" +
	"\bplay_url\x18\x03 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12$\n" +
	"\rfavoriteCount\x18\x05 \x01(\x03R\rfavoriteCount\x12\"\n" +
	"\fcommentCount\x18\x06 \x01(\x03R\fcommentCount\x12\x1e\n" +
	"\n" +
	"isFavorite\x18\a \x01(\bR\n" +
	"isFavorite\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12 \n" +
	"\visCollected\x18\t \x01(\bR\visCollected\x12&\n" +
	"\x0ecollectedCount\x18\n" +
	" \x01(\x03R\x0ecollectedCount*\x1e\n" +
	"\tSortOrder\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01*\x81\x01\n" +
	"\x0eSearchOperator\x12\x06\n" +
	"\x02EQ\x10\x00\x12\x06\n" +
	"\x02NE\x10\x01\x12\x06\n" +
	"\x02GT\x10\x02\x12\x06\n" +
	"\x02GE\x10\x03\x12\x06\n" +
	"\x02LT\x10\x04\x12\x06\n" +
	"\x02LE\x10\x05\x12\b\n" +
	"\x04LIKE\x10\x06\x12\f\n" +
	"\bWILDCARD\x10\a\x12\x06\n" +
	"\x02IN\x10\b\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\t\x12\v\n" +
	"\aBETWEEN\x10\n" +
	"\x12\x06\n" +
	"\x02RE\x10\vB)Z'github.com/cloudzenith/DouTok/...;svapib\x06proto3"

var (
	file_svapi_base_proto_rawDescOnce sync.Once
	file_svapi_base_proto_rawDescData []byte
)

func file_svapi_base_proto_rawDescGZIP() []byte {
	file_svapi_base_proto_rawDescOnce.Do(func() {
		file_svapi_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svapi_base_proto_rawDesc), len(file_svapi_base_proto_rawDesc)))
	})
	return file_svapi_base_proto_rawDescData
}

var file_svapi_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_svapi_base_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_svapi_base_proto_goTypes = []any{
	(SortOrder)(0),             // 0: svapi.SortOrder
	(SearchOperator)(0),        // 1: svapi.SearchOperator
	(*Metadata)(nil),           // 2: svapi.Metadata
	(*SortField)(nil),          // 3: svapi.SortField
	(*PaginationRequest)(nil),  // 4: svapi.PaginationRequest
	(*PaginationResponse)(nil), // 5: svapi.PaginationResponse
	(*SearchField)(nil),        // 6: svapi.SearchField
	(*SearchRequest)(nil),      // 7: svapi.SearchRequest
	(*VideoAuthor)(nil),        // 8: svapi.VideoAuthor
	(*Video)(nil),              // 9: svapi.Video
}
var file_svapi_base_proto_depIdxs = []int32{
	0, // 0: svapi.SortField.order:type_name -> svapi.SortOrder
	3, // 1: svapi.PaginationRequest.sort:type_name -> svapi.SortField
	1, // 2: svapi.SearchField.operator:type_name -> svapi.SearchOperator
	6, // 3: svapi.SearchRequest.search:type_name -> svapi.SearchField
	8, // 4: svapi.Video.author:type_name -> svapi.VideoAuthor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_svapi_base_proto_init() }
func file_svapi_base_proto_init() {
	if File_svapi_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svapi_base_proto_rawDesc), len(file_svapi_base_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svapi_base_proto_goTypes,
		DependencyIndexes: file_svapi_base_proto_depIdxs,
		EnumInfos:         file_svapi_base_proto_enumTypes,
		MessageInfos:      file_svapi_base_proto_msgTypes,
	}.Build()
	File_svapi_base_proto = out.File
	file_svapi_base_proto_goTypes = nil
	file_svapi_base_proto_depIdxs = nil
}
