// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: svapi/collection.proto

package svapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"` // 收藏夹id
	// @gotags: json:"userId,omitempty,string"
	UserId        int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId,omitempty,string"` // 用户id
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                    // 收藏夹名称
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`      // 收藏夹描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_svapi_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Collection) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CollectionVideo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"` // 收藏夹id
	// @gotags: json:"videoId,omitempty,string"
	VideoId       int64  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"videoId,omitempty,string"`   // 视频id
	CoverUrl      string `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 视频封面地址
	Title         string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                       // 视频标题
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`           // 视频描述
	VideoUrl      string `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"` // 视频地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionVideo) Reset() {
	*x = CollectionVideo{}
	mi := &file_svapi_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionVideo) ProtoMessage() {}

func (x *CollectionVideo) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionVideo.ProtoReflect.Descriptor instead.
func (*CollectionVideo) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionVideo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollectionVideo) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CollectionVideo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CollectionVideo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CollectionVideo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CollectionVideo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 收藏夹名称
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 收藏夹描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type RemoveCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"` // 收藏夹id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollectionRequest) Reset() {
	*x = RemoveCollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionRequest) ProtoMessage() {}

func (x *RemoveCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCollectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollectionResponse) Reset() {
	*x = RemoveCollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionResponse) ProtoMessage() {}

func (x *RemoveCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveCollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{5}
}

type ListCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionRequest) Reset() {
	*x = ListCollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionRequest) ProtoMessage() {}

func (x *ListCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionResponse) Reset() {
	*x = ListCollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionResponse) ProtoMessage() {}

func (x *ListCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{7}
}

func (x *ListCollectionResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`                  // 收藏夹id
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 收藏夹名称
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 收藏夹描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCollectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionResponse) Reset() {
	*x = UpdateCollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionResponse) ProtoMessage() {}

func (x *UpdateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type AddVideo2CollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"collectionId,omitempty,string"
	CollectionId int64 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collectionId,omitempty,string"` // 收藏夹id，不传则添加到默认收藏夹
	// @gotags: json:"videoId,omitempty,string"
	VideoId       int64 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"videoId,omitempty,string"` // 视频id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideo2CollectionRequest) Reset() {
	*x = AddVideo2CollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideo2CollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideo2CollectionRequest) ProtoMessage() {}

func (x *AddVideo2CollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideo2CollectionRequest.ProtoReflect.Descriptor instead.
func (*AddVideo2CollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{10}
}

func (x *AddVideo2CollectionRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *AddVideo2CollectionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type AddVideo2CollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideo2CollectionResponse) Reset() {
	*x = AddVideo2CollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideo2CollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideo2CollectionResponse) ProtoMessage() {}

func (x *AddVideo2CollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideo2CollectionResponse.ProtoReflect.Descriptor instead.
func (*AddVideo2CollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{11}
}

type RemoveVideoFromCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"collectionId,omitempty,string"
	CollectionId int64 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collectionId,omitempty,string"` // 收藏夹id
	// @gotags: json:"videoId,omitempty,string"
	VideoId       int64 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"videoId,omitempty,string"` // 视频id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoFromCollectionRequest) Reset() {
	*x = RemoveVideoFromCollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoFromCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoFromCollectionRequest) ProtoMessage() {}

func (x *RemoveVideoFromCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoFromCollectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveVideoFromCollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveVideoFromCollectionRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *RemoveVideoFromCollectionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type RemoveVideoFromCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoFromCollectionResponse) Reset() {
	*x = RemoveVideoFromCollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoFromCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoFromCollectionResponse) ProtoMessage() {}

func (x *RemoveVideoFromCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoFromCollectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveVideoFromCollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{13}
}

type ListVideo4CollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"collectionId,omitempty,string"
	CollectionId  int64              `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collectionId,omitempty,string"` // 收藏夹id
	Pagination    *PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideo4CollectionRequest) Reset() {
	*x = ListVideo4CollectionRequest{}
	mi := &file_svapi_collection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideo4CollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideo4CollectionRequest) ProtoMessage() {}

func (x *ListVideo4CollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideo4CollectionRequest.ProtoReflect.Descriptor instead.
func (*ListVideo4CollectionRequest) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{14}
}

func (x *ListVideo4CollectionRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *ListVideo4CollectionRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListVideo4CollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideo4CollectionResponse) Reset() {
	*x = ListVideo4CollectionResponse{}
	mi := &file_svapi_collection_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideo4CollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideo4CollectionResponse) ProtoMessage() {}

func (x *ListVideo4CollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_collection_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideo4CollectionResponse.ProtoReflect.Descriptor instead.
func (*ListVideo4CollectionResponse) Descriptor() ([]byte, []int) {
	return file_svapi_collection_proto_rawDescGZIP(), []int{15}
}

func (x *ListVideo4CollectionResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideo4CollectionResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_svapi_collection_proto protoreflect.FileDescriptor

const file_svapi_collection_proto_rawDesc = "" +
	"\n" +
	"\x16svapi/collection.proto\x12\x05svapi\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x10svapi/base.proto\"k\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xae\x01\n" +
	"\x0fCollectionVideo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\"O\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"M\n" +
	"\x18CreateCollectionResponse\x121\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x11.svapi.CollectionR\n" +
	"collection\")\n" +
	"\x17RemoveCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1a\n" +
	"\x18RemoveCollectionResponse\"Q\n" +
	"\x15ListCollectionRequest\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.svapi.PaginationRequestR\n" +
	"pagination\"\x88\x01\n" +
	"\x16ListCollectionResponse\x123\n" +
	"\vcollections\x18\x01 \x03(\v2\x11.svapi.CollectionR\vcollections\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.svapi.PaginationResponseR\n" +
	"pagination\"_\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"M\n" +
	"\x18UpdateCollectionResponse\x121\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x11.svapi.CollectionR\n" +
	"collection\"\\\n" +
	"\x1aAddVideo2CollectionRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x1d\n" +
	"\x1bAddVideo2CollectionResponse\"b\n" +
	" RemoveVideoFromCollectionRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"#\n" +
	"!RemoveVideoFromCollectionResponse\"|\n" +
	"\x1bListVideo4CollectionRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.svapi.PaginationRequestR\n" +
	"pagination\"\x7f\n" +
	"\x1cListVideo4CollectionResponse\x12$\n" +
	"\x06videos\x18\x01 \x03(\v2\f.svapi.VideoR\x06videos\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.svapi.PaginationResponseR\n" +
	"pagination2\xc5\x06\n" +
	"\x11CollectionService\x12k\n" +
	"\x10CreateCollection\x12\x1e.svapi.CreateCollectionRequest\x1a\x1f.svapi.CreateCollectionResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/collection\x12k\n" +
	"\x10RemoveCollection\x12\x1e.svapi.RemoveCollectionRequest\x1a\x1f.svapi.RemoveCollectionResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01**\v/collection\x12b\n" +
	"\x0eListCollection\x12\x1c.svapi.ListCollectionRequest\x1a\x1d.svapi.ListCollectionResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/collection\x12k\n" +
	"\x10UpdateCollection\x12\x1e.svapi.UpdateCollectionRequest\x1a\x1f.svapi.UpdateCollectionResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/collection\x12z\n" +
	"\x13AddVideo2Collection\x12!.svapi.AddVideo2CollectionRequest\x1a\".svapi.AddVideo2CollectionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/collection/video\x12\x8c\x01\n" +
	"\x19RemoveVideoFromCollection\x12'.svapi.RemoveVideoFromCollectionRequest\x1a(.svapi.RemoveVideoFromCollectionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01**\x11/collection/video\x12z\n" +
	"\x14ListVideo4Collection\x12\".svapi.ListVideo4CollectionRequest\x1a#.svapi.ListVideo4CollectionResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/collection/videoB)Z'github.com/cloudzenith/DouTok/...;svapib\x06proto3"

var (
	file_svapi_collection_proto_rawDescOnce sync.Once
	file_svapi_collection_proto_rawDescData []byte
)

func file_svapi_collection_proto_rawDescGZIP() []byte {
	file_svapi_collection_proto_rawDescOnce.Do(func() {
		file_svapi_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svapi_collection_proto_rawDesc), len(file_svapi_collection_proto_rawDesc)))
	})
	return file_svapi_collection_proto_rawDescData
}

var file_svapi_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_svapi_collection_proto_goTypes = []any{
	(*Collection)(nil),                        // 0: svapi.Collection
	(*CollectionVideo)(nil),                   // 1: svapi.CollectionVideo
	(*CreateCollectionRequest)(nil),           // 2: svapi.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),          // 3: svapi.CreateCollectionResponse
	(*RemoveCollectionRequest)(nil),           // 4: svapi.RemoveCollectionRequest
	(*RemoveCollectionResponse)(nil),          // 5: svapi.RemoveCollectionResponse
	(*ListCollectionRequest)(nil),             // 6: svapi.ListCollectionRequest
	(*ListCollectionResponse)(nil),            // 7: svapi.ListCollectionResponse
	(*UpdateCollectionRequest)(nil),           // 8: svapi.UpdateCollectionRequest
	(*UpdateCollectionResponse)(nil),          // 9: svapi.UpdateCollectionResponse
	(*AddVideo2CollectionRequest)(nil),        // 10: svapi.AddVideo2CollectionRequest
	(*AddVideo2CollectionResponse)(nil),       // 11: svapi.AddVideo2CollectionResponse
	(*RemoveVideoFromCollectionRequest)(nil),  // 12: svapi.RemoveVideoFromCollectionRequest
	(*RemoveVideoFromCollectionResponse)(nil), // 13: svapi.RemoveVideoFromCollectionResponse
	(*ListVideo4CollectionRequest)(nil),       // 14: svapi.ListVideo4CollectionRequest
	(*ListVideo4CollectionResponse)(nil),      // 15: svapi.ListVideo4CollectionResponse
	(*PaginationRequest)(nil),                 // 16: svapi.PaginationRequest
	(*PaginationResponse)(nil),                // 17: svapi.PaginationResponse
	(*Video)(nil),                             // 18: svapi.Video
}
var file_svapi_collection_proto_depIdxs = []int32{
	0,  // 0: svapi.CreateCollectionResponse.collection:type_name -> svapi.Collection
	16, // 1: svapi.ListCollectionRequest.pagination:type_name -> svapi.PaginationRequest
	0,  // 2: svapi.ListCollectionResponse.collections:type_name -> svapi.Collection
	17, // 3: svapi.ListCollectionResponse.pagination:type_name -> svapi.PaginationResponse
	0,  // 4: svapi.UpdateCollectionResponse.collection:type_name -> svapi.Collection
	16, // 5: svapi.ListVideo4CollectionRequest.pagination:type_name -> svapi.PaginationRequest
	18, // 6: svapi.ListVideo4CollectionResponse.videos:type_name -> svapi.Video
	17, // 7: svapi.ListVideo4CollectionResponse.pagination:type_name -> svapi.PaginationResponse
	2,  // 8: svapi.CollectionService.CreateCollection:input_type -> svapi.CreateCollectionRequest
	4,  // 9: svapi.CollectionService.RemoveCollection:input_type -> svapi.RemoveCollectionRequest
	6,  // 10: svapi.CollectionService.ListCollection:input_type -> svapi.ListCollectionRequest
	8,  // 11: svapi.CollectionService.UpdateCollection:input_type -> svapi.UpdateCollectionRequest
	10, // 12: svapi.CollectionService.AddVideo2Collection:input_type -> svapi.AddVideo2CollectionRequest
	12, // 13: svapi.CollectionService.RemoveVideoFromCollection:input_type -> svapi.RemoveVideoFromCollectionRequest
	14, // 14: svapi.CollectionService.ListVideo4Collection:input_type -> svapi.ListVideo4CollectionRequest
	3,  // 15: svapi.CollectionService.CreateCollection:output_type -> svapi.CreateCollectionResponse
	5,  // 16: svapi.CollectionService.RemoveCollection:output_type -> svapi.RemoveCollectionResponse
	7,  // 17: svapi.CollectionService.ListCollection:output_type -> svapi.ListCollectionResponse
	9,  // 18: svapi.CollectionService.UpdateCollection:output_type -> svapi.UpdateCollectionResponse
	11, // 19: svapi.CollectionService.AddVideo2Collection:output_type -> svapi.AddVideo2CollectionResponse
	13, // 20: svapi.CollectionService.RemoveVideoFromCollection:output_type -> svapi.RemoveVideoFromCollectionResponse
	15, // 21: svapi.CollectionService.ListVideo4Collection:output_type -> svapi.ListVideo4CollectionResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_svapi_collection_proto_init() }
func file_svapi_collection_proto_init() {
	if File_svapi_collection_proto != nil {
		return
	}
	file_svapi_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svapi_collection_proto_rawDesc), len(file_svapi_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svapi_collection_proto_goTypes,
		DependencyIndexes: file_svapi_collection_proto_depIdxs,
		MessageInfos:      file_svapi_collection_proto_msgTypes,
	}.Build()
	File_svapi_collection_proto = out.File
	file_svapi_collection_proto_goTypes = nil
	file_svapi_collection_proto_depIdxs = nil
}
