// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: svapi/comment.proto

package svapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"` // 评论id
	// @gotags: json:"videoId,omitempty,string"
	VideoId int64 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"videoId,omitempty,string"` // 视频id
	// @gotags: json:"parentId,omitempty,string"
	ParentId      int64        `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parentId,omitempty,string"`      // 父评论id
	User          *CommentUser `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                               // 评论用户
	ReplyUser     *CommentUser `protobuf:"bytes,5,opt,name=reply_user,json=replyUser,proto3" json:"reply_user,omitempty"`    // 回复用户
	Content       string       `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                         // 评论内容
	Date          string       `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`                               // 评论日期
	LikeCount     string       `protobuf:"bytes,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`    // 点赞数
	ReplyCount    string       `protobuf:"bytes,9,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"` // 回复数
	Comments      []*Comment   `protobuf:"bytes,10,rep,name=comments,proto3" json:"comments,omitempty"`                      // 子评论
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_svapi_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetUser() *CommentUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetReplyUser() *CommentUser {
	if x != nil {
		return x.ReplyUser
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Comment) GetLikeCount() string {
	if x != nil {
		return x.LikeCount
	}
	return ""
}

func (x *Comment) GetReplyCount() string {
	if x != nil {
		return x.ReplyCount
	}
	return ""
}

func (x *Comment) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CommentUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`                                      // 用户id
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 用户名称
	Avatar        string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                               // 用户头像
	IsFollowing   bool   `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"` // 是否关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentUser) Reset() {
	*x = CommentUser{}
	mi := &file_svapi_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentUser) ProtoMessage() {}

func (x *CommentUser) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentUser.ProtoReflect.Descriptor instead.
func (*CommentUser) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CommentUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommentUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CommentUser) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type CreateCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"videoId,omitempty,string"
	VideoId int64  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"videoId,omitempty,string"` // 视频id
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                 // 评论内容
	// @gotags: json:"parentId,omitempty,string"
	ParentId int64 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parentId,omitempty,string"`
	// @gotags: json:"replyUserId,omitempty,string"
	ReplyUserId   int64 `protobuf:"varint,4,opt,name=reply_user_id,json=replyUserId,proto3" json:"replyUserId,omitempty,string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_svapi_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentRequest) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_svapi_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type RemoveCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"` // 评论id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommentRequest) Reset() {
	*x = RemoveCommentRequest{}
	mi := &file_svapi_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommentRequest) ProtoMessage() {}

func (x *RemoveCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommentRequest.ProtoReflect.Descriptor instead.
func (*RemoveCommentRequest) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommentResponse) Reset() {
	*x = RemoveCommentResponse{}
	mi := &file_svapi_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommentResponse) ProtoMessage() {}

func (x *RemoveCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommentResponse.ProtoReflect.Descriptor instead.
func (*RemoveCommentResponse) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{5}
}

type ListComment4VideoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"videoId,omitempty,string"
	VideoId       int64              `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"videoId,omitempty,string"` // 视频id
	Pagination    *PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComment4VideoRequest) Reset() {
	*x = ListComment4VideoRequest{}
	mi := &file_svapi_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComment4VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComment4VideoRequest) ProtoMessage() {}

func (x *ListComment4VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComment4VideoRequest.ProtoReflect.Descriptor instead.
func (*ListComment4VideoRequest) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{6}
}

func (x *ListComment4VideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *ListComment4VideoRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListComment4VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComment4VideoResponse) Reset() {
	*x = ListComment4VideoResponse{}
	mi := &file_svapi_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComment4VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComment4VideoResponse) ProtoMessage() {}

func (x *ListComment4VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComment4VideoResponse.ProtoReflect.Descriptor instead.
func (*ListComment4VideoResponse) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{7}
}

func (x *ListComment4VideoResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListComment4VideoResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListChildCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"commentId,omitempty,string"
	CommentId     int64              `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"commentId,omitempty,string"` // 评论id
	Pagination    *PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildCommentRequest) Reset() {
	*x = ListChildCommentRequest{}
	mi := &file_svapi_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildCommentRequest) ProtoMessage() {}

func (x *ListChildCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildCommentRequest.ProtoReflect.Descriptor instead.
func (*ListChildCommentRequest) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListChildCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ListChildCommentRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListChildCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildCommentResponse) Reset() {
	*x = ListChildCommentResponse{}
	mi := &file_svapi_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildCommentResponse) ProtoMessage() {}

func (x *ListChildCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildCommentResponse.ProtoReflect.Descriptor instead.
func (*ListChildCommentResponse) Descriptor() ([]byte, []int) {
	return file_svapi_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListChildCommentResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListChildCommentResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_svapi_comment_proto protoreflect.FileDescriptor

const file_svapi_comment_proto_rawDesc = "" +
	"\n" +
	"\x13svapi/comment.proto\x12\x05svapi\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x10svapi/base.proto\"\xc6\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12&\n" +
	"\x04user\x18\x04 \x01(\v2\x12.svapi.CommentUserR\x04user\x121\n" +
	"\n" +
	"reply_user\x18\x05 \x01(\v2\x12.svapi.CommentUserR\treplyUser\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\tR\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\t \x01(\tR\n" +
	"replyCount\x12*\n" +
	"\bcomments\x18\n" +
	" \x03(\v2\x0e.svapi.CommentR\bcomments\"l\n" +
	"\vCommentUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12!\n" +
	"\fis_following\x18\x04 \x01(\bR\visFollowing\"\x8c\x01\n" +
	"\x14CreateCommentRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\"\n" +
	"\rreply_user_id\x18\x04 \x01(\x03R\vreplyUserId\"A\n" +
	"\x15CreateCommentResponse\x12(\n" +
	"\acomment\x18\x01 \x01(\v2\x0e.svapi.CommentR\acomment\"&\n" +
	"\x14RemoveCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15RemoveCommentResponse\"o\n" +
	"\x18ListComment4VideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.svapi.PaginationRequestR\n" +
	"pagination\"\x82\x01\n" +
	"\x19ListComment4VideoResponse\x12*\n" +
	"\bcomments\x18\x01 \x03(\v2\x0e.svapi.CommentR\bcomments\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.svapi.PaginationResponseR\n" +
	"pagination\"r\n" +
	"\x17ListChildCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.svapi.PaginationRequestR\n" +
	"pagination\"\x81\x01\n" +
	"\x18ListChildCommentResponse\x12*\n" +
	"\bcomments\x18\x01 \x03(\v2\x0e.svapi.CommentR\bcomments\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.svapi.PaginationResponseR\n" +
	"pagination2\xb5\x03\n" +
	"\x0eCommentService\x12_\n" +
	"\rCreateComment\x12\x1b.svapi.CreateCommentRequest\x1a\x1c.svapi.CreateCommentResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/comment\x12_\n" +
	"\rRemoveComment\x12\x1b.svapi.RemoveCommentRequest\x1a\x1c.svapi.RemoveCommentResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01**\b/comment\x12q\n" +
	"\x11ListComment4Video\x12\x1f.svapi.ListComment4VideoRequest\x1a .svapi.ListComment4VideoResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/comment/video\x12n\n" +
	"\x10ListChildComment\x12\x1e.svapi.ListChildCommentRequest\x1a\x1f.svapi.ListChildCommentResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/comment/childB)Z'github.com/cloudzenith/DouTok/...;svapib\x06proto3"

var (
	file_svapi_comment_proto_rawDescOnce sync.Once
	file_svapi_comment_proto_rawDescData []byte
)

func file_svapi_comment_proto_rawDescGZIP() []byte {
	file_svapi_comment_proto_rawDescOnce.Do(func() {
		file_svapi_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svapi_comment_proto_rawDesc), len(file_svapi_comment_proto_rawDesc)))
	})
	return file_svapi_comment_proto_rawDescData
}

var file_svapi_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_svapi_comment_proto_goTypes = []any{
	(*Comment)(nil),                   // 0: svapi.Comment
	(*CommentUser)(nil),               // 1: svapi.CommentUser
	(*CreateCommentRequest)(nil),      // 2: svapi.CreateCommentRequest
	(*CreateCommentResponse)(nil),     // 3: svapi.CreateCommentResponse
	(*RemoveCommentRequest)(nil),      // 4: svapi.RemoveCommentRequest
	(*RemoveCommentResponse)(nil),     // 5: svapi.RemoveCommentResponse
	(*ListComment4VideoRequest)(nil),  // 6: svapi.ListComment4VideoRequest
	(*ListComment4VideoResponse)(nil), // 7: svapi.ListComment4VideoResponse
	(*ListChildCommentRequest)(nil),   // 8: svapi.ListChildCommentRequest
	(*ListChildCommentResponse)(nil),  // 9: svapi.ListChildCommentResponse
	(*PaginationRequest)(nil),         // 10: svapi.PaginationRequest
	(*PaginationResponse)(nil),        // 11: svapi.PaginationResponse
}
var file_svapi_comment_proto_depIdxs = []int32{
	1,  // 0: svapi.Comment.user:type_name -> svapi.CommentUser
	1,  // 1: svapi.Comment.reply_user:type_name -> svapi.CommentUser
	0,  // 2: svapi.Comment.comments:type_name -> svapi.Comment
	0,  // 3: svapi.CreateCommentResponse.comment:type_name -> svapi.Comment
	10, // 4: svapi.ListComment4VideoRequest.pagination:type_name -> svapi.PaginationRequest
	0,  // 5: svapi.ListComment4VideoResponse.comments:type_name -> svapi.Comment
	11, // 6: svapi.ListComment4VideoResponse.pagination:type_name -> svapi.PaginationResponse
	10, // 7: svapi.ListChildCommentRequest.pagination:type_name -> svapi.PaginationRequest
	0,  // 8: svapi.ListChildCommentResponse.comments:type_name -> svapi.Comment
	11, // 9: svapi.ListChildCommentResponse.pagination:type_name -> svapi.PaginationResponse
	2,  // 10: svapi.CommentService.CreateComment:input_type -> svapi.CreateCommentRequest
	4,  // 11: svapi.CommentService.RemoveComment:input_type -> svapi.RemoveCommentRequest
	6,  // 12: svapi.CommentService.ListComment4Video:input_type -> svapi.ListComment4VideoRequest
	8,  // 13: svapi.CommentService.ListChildComment:input_type -> svapi.ListChildCommentRequest
	3,  // 14: svapi.CommentService.CreateComment:output_type -> svapi.CreateCommentResponse
	5,  // 15: svapi.CommentService.RemoveComment:output_type -> svapi.RemoveCommentResponse
	7,  // 16: svapi.CommentService.ListComment4Video:output_type -> svapi.ListComment4VideoResponse
	9,  // 17: svapi.CommentService.ListChildComment:output_type -> svapi.ListChildCommentResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_svapi_comment_proto_init() }
func file_svapi_comment_proto_init() {
	if File_svapi_comment_proto != nil {
		return
	}
	file_svapi_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svapi_comment_proto_rawDesc), len(file_svapi_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svapi_comment_proto_goTypes,
		DependencyIndexes: file_svapi_comment_proto_depIdxs,
		MessageInfos:      file_svapi_comment_proto_msgTypes,
	}.Build()
	File_svapi_comment_proto = out.File
	file_svapi_comment_proto_goTypes = nil
	file_svapi_comment_proto_depIdxs = nil
}
