// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: svapi/favorite.proto

package svapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteTarget int32

const (
	FavoriteTarget_VIDEO   FavoriteTarget = 0
	FavoriteTarget_COMMENT FavoriteTarget = 1
)

// Enum value maps for FavoriteTarget.
var (
	FavoriteTarget_name = map[int32]string{
		0: "VIDEO",
		1: "COMMENT",
	}
	FavoriteTarget_value = map[string]int32{
		"VIDEO":   0,
		"COMMENT": 1,
	}
)

func (x FavoriteTarget) Enum() *FavoriteTarget {
	p := new(FavoriteTarget)
	*p = x
	return p
}

func (x FavoriteTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_svapi_favorite_proto_enumTypes[0].Descriptor()
}

func (FavoriteTarget) Type() protoreflect.EnumType {
	return &file_svapi_favorite_proto_enumTypes[0]
}

func (x FavoriteTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteTarget.Descriptor instead.
func (FavoriteTarget) EnumDescriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{0}
}

type FavoriteType int32

const (
	FavoriteType_FAVORITE FavoriteType = 0 // 点赞
	FavoriteType_UNLIKE   FavoriteType = 1 // 点踩
)

// Enum value maps for FavoriteType.
var (
	FavoriteType_name = map[int32]string{
		0: "FAVORITE",
		1: "UNLIKE",
	}
	FavoriteType_value = map[string]int32{
		"FAVORITE": 0,
		"UNLIKE":   1,
	}
)

func (x FavoriteType) Enum() *FavoriteType {
	p := new(FavoriteType)
	*p = x
	return p
}

func (x FavoriteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteType) Descriptor() protoreflect.EnumDescriptor {
	return file_svapi_favorite_proto_enumTypes[1].Descriptor()
}

func (FavoriteType) Type() protoreflect.EnumType {
	return &file_svapi_favorite_proto_enumTypes[1]
}

func (x FavoriteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteType.Descriptor instead.
func (FavoriteType) EnumDescriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{1}
}

type AddFavoriteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target FavoriteTarget         `protobuf:"varint,1,opt,name=target,proto3,enum=svapi.FavoriteTarget" json:"target,omitempty"`
	Type   FavoriteType           `protobuf:"varint,2,opt,name=type,proto3,enum=svapi.FavoriteType" json:"type,omitempty"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty,string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_svapi_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *AddFavoriteRequest) GetTarget() FavoriteTarget {
	if x != nil {
		return x.Target
	}
	return FavoriteTarget_VIDEO
}

func (x *AddFavoriteRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE
}

func (x *AddFavoriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_svapi_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{1}
}

type RemoveFavoriteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target FavoriteTarget         `protobuf:"varint,1,opt,name=target,proto3,enum=svapi.FavoriteTarget" json:"target,omitempty"`
	Type   FavoriteType           `protobuf:"varint,2,opt,name=type,proto3,enum=svapi.FavoriteType" json:"type,omitempty"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty,string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_svapi_favorite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_favorite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFavoriteRequest) GetTarget() FavoriteTarget {
	if x != nil {
		return x.Target
	}
	return FavoriteTarget_VIDEO
}

func (x *RemoveFavoriteRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE
}

func (x *RemoveFavoriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteResponse) Reset() {
	*x = RemoveFavoriteResponse{}
	mi := &file_svapi_favorite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteResponse) ProtoMessage() {}

func (x *RemoveFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_favorite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteResponse.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{3}
}

type ListFavoriteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteVideoRequest) Reset() {
	*x = ListFavoriteVideoRequest{}
	mi := &file_svapi_favorite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteVideoRequest) ProtoMessage() {}

func (x *ListFavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_favorite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*ListFavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{4}
}

func (x *ListFavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFavoriteVideoRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoriteVideoRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFavoriteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteVideoResponse) Reset() {
	*x = ListFavoriteVideoResponse{}
	mi := &file_svapi_favorite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteVideoResponse) ProtoMessage() {}

func (x *ListFavoriteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_favorite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteVideoResponse.ProtoReflect.Descriptor instead.
func (*ListFavoriteVideoResponse) Descriptor() ([]byte, []int) {
	return file_svapi_favorite_proto_rawDescGZIP(), []int{5}
}

func (x *ListFavoriteVideoResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListFavoriteVideoResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_svapi_favorite_proto protoreflect.FileDescriptor

const file_svapi_favorite_proto_rawDesc = "" +
	"\n" +
	"\x14svapi/favorite.proto\x12\x05svapi\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x10svapi/base.proto\x1a\x11svapi/video.proto\"|\n" +
	"\x12AddFavoriteRequest\x12-\n" +
	"\x06target\x18\x01 \x01(\x0e2\x15.svapi.FavoriteTargetR\x06target\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.svapi.FavoriteTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"\x15\n" +
	"\x13AddFavoriteResponse\"\x7f\n" +
	"\x15RemoveFavoriteRequest\x12-\n" +
	"\x06target\x18\x01 \x01(\x0e2\x15.svapi.FavoriteTargetR\x06target\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.svapi.FavoriteTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"\x18\n" +
	"\x16RemoveFavoriteResponse\"Z\n" +
	"\x18ListFavoriteVideoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"|\n" +
	"\x19ListFavoriteVideoResponse\x12$\n" +
	"\x06videos\x18\x01 \x03(\v2\f.svapi.VideoR\x06videos\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.svapi.PaginationResponseR\n" +
	"pagination*(\n" +
	"\x0eFavoriteTarget\x12\t\n" +
	"\x05VIDEO\x10\x00\x12\v\n" +
	"\aCOMMENT\x10\x01*(\n" +
	"\fFavoriteType\x12\f\n" +
	"\bFAVORITE\x10\x00\x12\n" +
	"\n" +
	"\x06UNLIKE\x10\x012\xcb\x02\n" +
	"\x0fFavoriteService\x12Z\n" +
	"\vAddFavorite\x12\x19.svapi.AddFavoriteRequest\x1a\x1a.svapi.AddFavoriteResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/favorite\x12c\n" +
	"\x0eRemoveFavorite\x12\x1c.svapi.RemoveFavoriteRequest\x1a\x1d.svapi.RemoveFavoriteResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01**\t/favorite\x12w\n" +
	"\x11ListFavoriteVideo\x12\x1f.svapi.ListFavoriteVideoRequest\x1a .svapi.ListFavoriteVideoResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/favorite/video/listB)Z'github.com/cloudzenith/DouTok/...;svapib\x06proto3"

var (
	file_svapi_favorite_proto_rawDescOnce sync.Once
	file_svapi_favorite_proto_rawDescData []byte
)

func file_svapi_favorite_proto_rawDescGZIP() []byte {
	file_svapi_favorite_proto_rawDescOnce.Do(func() {
		file_svapi_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svapi_favorite_proto_rawDesc), len(file_svapi_favorite_proto_rawDesc)))
	})
	return file_svapi_favorite_proto_rawDescData
}

var file_svapi_favorite_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_svapi_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_svapi_favorite_proto_goTypes = []any{
	(FavoriteTarget)(0),               // 0: svapi.FavoriteTarget
	(FavoriteType)(0),                 // 1: svapi.FavoriteType
	(*AddFavoriteRequest)(nil),        // 2: svapi.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),       // 3: svapi.AddFavoriteResponse
	(*RemoveFavoriteRequest)(nil),     // 4: svapi.RemoveFavoriteRequest
	(*RemoveFavoriteResponse)(nil),    // 5: svapi.RemoveFavoriteResponse
	(*ListFavoriteVideoRequest)(nil),  // 6: svapi.ListFavoriteVideoRequest
	(*ListFavoriteVideoResponse)(nil), // 7: svapi.ListFavoriteVideoResponse
	(*Video)(nil),                     // 8: svapi.Video
	(*PaginationResponse)(nil),        // 9: svapi.PaginationResponse
}
var file_svapi_favorite_proto_depIdxs = []int32{
	0, // 0: svapi.AddFavoriteRequest.target:type_name -> svapi.FavoriteTarget
	1, // 1: svapi.AddFavoriteRequest.type:type_name -> svapi.FavoriteType
	0, // 2: svapi.RemoveFavoriteRequest.target:type_name -> svapi.FavoriteTarget
	1, // 3: svapi.RemoveFavoriteRequest.type:type_name -> svapi.FavoriteType
	8, // 4: svapi.ListFavoriteVideoResponse.videos:type_name -> svapi.Video
	9, // 5: svapi.ListFavoriteVideoResponse.pagination:type_name -> svapi.PaginationResponse
	2, // 6: svapi.FavoriteService.AddFavorite:input_type -> svapi.AddFavoriteRequest
	4, // 7: svapi.FavoriteService.RemoveFavorite:input_type -> svapi.RemoveFavoriteRequest
	6, // 8: svapi.FavoriteService.ListFavoriteVideo:input_type -> svapi.ListFavoriteVideoRequest
	3, // 9: svapi.FavoriteService.AddFavorite:output_type -> svapi.AddFavoriteResponse
	5, // 10: svapi.FavoriteService.RemoveFavorite:output_type -> svapi.RemoveFavoriteResponse
	7, // 11: svapi.FavoriteService.ListFavoriteVideo:output_type -> svapi.ListFavoriteVideoResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_svapi_favorite_proto_init() }
func file_svapi_favorite_proto_init() {
	if File_svapi_favorite_proto != nil {
		return
	}
	file_svapi_base_proto_init()
	file_svapi_video_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svapi_favorite_proto_rawDesc), len(file_svapi_favorite_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svapi_favorite_proto_goTypes,
		DependencyIndexes: file_svapi_favorite_proto_depIdxs,
		EnumInfos:         file_svapi_favorite_proto_enumTypes,
		MessageInfos:      file_svapi_favorite_proto_msgTypes,
	}.Build()
	File_svapi_favorite_proto = out.File
	file_svapi_favorite_proto_goTypes = nil
	file_svapi_favorite_proto_depIdxs = nil
}
