// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.21.12
// source: svapi/search.proto

package svapi

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSearchServiceSearch = "/svapi.SearchService/Search"

type SearchServiceHTTPServer interface {
	// Search 搜索
	Search(context.Context, *ContentSearchRequest) (*ContentSearchResponse, error)
}

func RegisterSearchServiceHTTPServer(s *http.Server, srv SearchServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/search", _SearchService_Search0_HTTP_Handler(srv))
}

func _SearchService_Search0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContentSearchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*ContentSearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContentSearchResponse)
		return ctx.Result(200, reply)
	}
}

type SearchServiceHTTPClient interface {
	Search(ctx context.Context, req *ContentSearchRequest, opts ...http.CallOption) (rsp *ContentSearchResponse, err error)
}

type SearchServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchServiceHTTPClient(client *http.Client) SearchServiceHTTPClient {
	return &SearchServiceHTTPClientImpl{client}
}

func (c *SearchServiceHTTPClientImpl) Search(ctx context.Context, in *ContentSearchRequest, opts ...http.CallOption) (*ContentSearchResponse, error) {
	var out ContentSearchResponse
	pattern := "/search"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSearchServiceSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
