// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: svapi/search.proto

package svapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 搜索类型枚举
type SearchType int32

const (
	SearchType_SEARCH_TYPE_ALL   SearchType = 0 // 全部
	SearchType_SEARCH_TYPE_VIDEO SearchType = 1 // 视频
	SearchType_SEARCH_TYPE_USER  SearchType = 2 // 用户
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "SEARCH_TYPE_ALL",
		1: "SEARCH_TYPE_VIDEO",
		2: "SEARCH_TYPE_USER",
	}
	SearchType_value = map[string]int32{
		"SEARCH_TYPE_ALL":   0,
		"SEARCH_TYPE_VIDEO": 1,
		"SEARCH_TYPE_USER":  2,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_svapi_search_proto_enumTypes[0].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_svapi_search_proto_enumTypes[0]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_svapi_search_proto_rawDescGZIP(), []int{0}
}

// 搜索请求消息类型
type ContentSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                      // 搜索关键词
	Type          SearchType             `protobuf:"varint,2,opt,name=type,proto3,enum=svapi.SearchType" json:"type,omitempty"` // 搜索类型
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`            // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentSearchRequest) Reset() {
	*x = ContentSearchRequest{}
	mi := &file_svapi_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSearchRequest) ProtoMessage() {}

func (x *ContentSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSearchRequest.ProtoReflect.Descriptor instead.
func (*ContentSearchRequest) Descriptor() ([]byte, []int) {
	return file_svapi_search_proto_rawDescGZIP(), []int{0}
}

func (x *ContentSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ContentSearchRequest) GetType() SearchType {
	if x != nil {
		return x.Type
	}
	return SearchType_SEARCH_TYPE_ALL
}

func (x *ContentSearchRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 搜索响应消息类型
type ContentSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`         // 视频搜索结果
	Users         []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`           // 用户搜索结果
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentSearchResponse) Reset() {
	*x = ContentSearchResponse{}
	mi := &file_svapi_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSearchResponse) ProtoMessage() {}

func (x *ContentSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSearchResponse.ProtoReflect.Descriptor instead.
func (*ContentSearchResponse) Descriptor() ([]byte, []int) {
	return file_svapi_search_proto_rawDescGZIP(), []int{1}
}

func (x *ContentSearchResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ContentSearchResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ContentSearchResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_svapi_search_proto protoreflect.FileDescriptor

const file_svapi_search_proto_rawDesc = "" +
	"\n" +
	"\x12svapi/search.proto\x12\x05svapi\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x10svapi/base.proto\x1a\x10svapi/user.proto\"\x96\x01\n" +
	"\x14ContentSearchRequest\x12\x1d\n" +
	"\x05query\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05query\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.svapi.SearchTypeR\x04type\x128\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x18.svapi.PaginationRequestR\n" +
	"pagination\"\x9b\x01\n" +
	"\x15ContentSearchResponse\x12$\n" +
	"\x06videos\x18\x01 \x03(\v2\f.svapi.VideoR\x06videos\x12!\n" +
	"\x05users\x18\x02 \x03(\v2\v.svapi.UserR\x05users\x129\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x19.svapi.PaginationResponseR\n" +
	"pagination*N\n" +
	"\n" +
	"SearchType\x12\x13\n" +
	"\x0fSEARCH_TYPE_ALL\x10\x00\x12\x15\n" +
	"\x11SEARCH_TYPE_VIDEO\x10\x01\x12\x14\n" +
	"\x10SEARCH_TYPE_USER\x10\x022h\n" +
	"\rSearchService\x12W\n" +
	"\x06Search\x12\x1b.svapi.ContentSearchRequest\x1a\x1c.svapi.ContentSearchResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/searchB)Z'github.com/cloudzenith/DouTok/...;svapib\x06proto3"

var (
	file_svapi_search_proto_rawDescOnce sync.Once
	file_svapi_search_proto_rawDescData []byte
)

func file_svapi_search_proto_rawDescGZIP() []byte {
	file_svapi_search_proto_rawDescOnce.Do(func() {
		file_svapi_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svapi_search_proto_rawDesc), len(file_svapi_search_proto_rawDesc)))
	})
	return file_svapi_search_proto_rawDescData
}

var file_svapi_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svapi_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_svapi_search_proto_goTypes = []any{
	(SearchType)(0),               // 0: svapi.SearchType
	(*ContentSearchRequest)(nil),  // 1: svapi.ContentSearchRequest
	(*ContentSearchResponse)(nil), // 2: svapi.ContentSearchResponse
	(*PaginationRequest)(nil),     // 3: svapi.PaginationRequest
	(*Video)(nil),                 // 4: svapi.Video
	(*User)(nil),                  // 5: svapi.User
	(*PaginationResponse)(nil),    // 6: svapi.PaginationResponse
}
var file_svapi_search_proto_depIdxs = []int32{
	0, // 0: svapi.ContentSearchRequest.type:type_name -> svapi.SearchType
	3, // 1: svapi.ContentSearchRequest.pagination:type_name -> svapi.PaginationRequest
	4, // 2: svapi.ContentSearchResponse.videos:type_name -> svapi.Video
	5, // 3: svapi.ContentSearchResponse.users:type_name -> svapi.User
	6, // 4: svapi.ContentSearchResponse.pagination:type_name -> svapi.PaginationResponse
	1, // 5: svapi.SearchService.Search:input_type -> svapi.ContentSearchRequest
	2, // 6: svapi.SearchService.Search:output_type -> svapi.ContentSearchResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_svapi_search_proto_init() }
func file_svapi_search_proto_init() {
	if File_svapi_search_proto != nil {
		return
	}
	file_svapi_base_proto_init()
	file_svapi_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svapi_search_proto_rawDesc), len(file_svapi_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svapi_search_proto_goTypes,
		DependencyIndexes: file_svapi_search_proto_depIdxs,
		EnumInfos:         file_svapi_search_proto_enumTypes,
		MessageInfos:      file_svapi_search_proto_msgTypes,
	}.Build()
	File_svapi_search_proto = out.File
	file_svapi_search_proto_goTypes = nil
	file_svapi_search_proto_depIdxs = nil
}
