// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: svapi/user.proto

package svapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoucherType int32

const (
	VoucherType_PHONE VoucherType = 0
	VoucherType_EMAIL VoucherType = 1
)

// Enum value maps for VoucherType.
var (
	VoucherType_name = map[int32]string{
		0: "PHONE",
		1: "EMAIL",
	}
	VoucherType_value = map[string]int32{
		"PHONE": 0,
		"EMAIL": 1,
	}
)

func (x VoucherType) Enum() *VoucherType {
	p := new(VoucherType)
	*p = x
	return p
}

func (x VoucherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoucherType) Descriptor() protoreflect.EnumDescriptor {
	return file_svapi_user_proto_enumTypes[0].Descriptor()
}

func (VoucherType) Type() protoreflect.EnumType {
	return &file_svapi_user_proto_enumTypes[0]
}

func (x VoucherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoucherType.Descriptor instead.
func (VoucherType) EnumDescriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`                                                 // 用户id
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // 用户名称
	Avatar          string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                          // 用户头像Url
	BackgroundImage string `protobuf:"bytes,4,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"` // 用户个人页顶部大图
	Signature       string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                    // 个人简介
	Mobile          string `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`                                          // 手机号
	Email           string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                            // 邮箱
	// @gotags: json:"followCount,omitempty,string"
	FollowCount int64 `protobuf:"varint,8,opt,name=followCount,proto3" json:"followCount,omitempty,string"` // 关注总数
	// @gotags: json:"followerCount,omitempty,string"
	FollowerCount int64 `protobuf:"varint,9,opt,name=followerCount,proto3" json:"followerCount,omitempty,string"` // 粉丝总数
	// @gotags: json:"totalFavorited,omitempty,string"
	TotalFavorited int64 `protobuf:"varint,10,opt,name=totalFavorited,proto3" json:"totalFavorited,omitempty,string"` // 获赞数量
	// @gotags: json:"workCount,omitempty,string"
	WorkCount int64 `protobuf:"varint,11,opt,name=workCount,proto3" json:"workCount,omitempty,string"` // 作品数量
	// @gotags: json:"favoriteCount,omitempty,string"
	FavoriteCount int64 `protobuf:"varint,12,opt,name=favoriteCount,proto3" json:"favoriteCount,omitempty,string"` // 点赞数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_svapi_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetTotalFavorited() int64 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *User) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *User) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type GetVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerificationCodeRequest) Reset() {
	*x = GetVerificationCodeRequest{}
	mi := &file_svapi_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationCodeRequest) ProtoMessage() {}

func (x *GetVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerificationCodeRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetVerificationCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetVerificationCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"code_id,omitempty,string"
	CodeId        int64 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty,string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerificationCodeResponse) Reset() {
	*x = GetVerificationCodeResponse{}
	mi := &file_svapi_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationCodeResponse) ProtoMessage() {}

func (x *GetVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*GetVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetVerificationCodeResponse) GetCodeId() int64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

type RegisterRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Mobile   string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email    string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// @gotags: json:"code_id,omitempty,string"
	CodeId        int64  `protobuf:"varint,4,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty,string"`
	Code          string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_svapi_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCodeId() int64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *RegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"user_id,omitempty,string"
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty,string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_svapi_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_svapi_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_svapi_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"user_id,omitempty,string"
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty,string"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_svapi_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_svapi_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"user_id,omitempty,string"
	UserId          int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty,string"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundImage string `protobuf:"bytes,4,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"`
	Signature       string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_svapi_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type UpdateUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_svapi_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{10}
}

type BindUserVoucherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoucherType   VoucherType            `protobuf:"varint,1,opt,name=voucher_type,json=voucherType,proto3,enum=svapi.VoucherType" json:"voucher_type,omitempty"`
	Voucher       string                 `protobuf:"bytes,2,opt,name=voucher,proto3" json:"voucher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindUserVoucherRequest) Reset() {
	*x = BindUserVoucherRequest{}
	mi := &file_svapi_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindUserVoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindUserVoucherRequest) ProtoMessage() {}

func (x *BindUserVoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindUserVoucherRequest.ProtoReflect.Descriptor instead.
func (*BindUserVoucherRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{11}
}

func (x *BindUserVoucherRequest) GetVoucherType() VoucherType {
	if x != nil {
		return x.VoucherType
	}
	return VoucherType_PHONE
}

func (x *BindUserVoucherRequest) GetVoucher() string {
	if x != nil {
		return x.Voucher
	}
	return ""
}

type BindUserVoucherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindUserVoucherResponse) Reset() {
	*x = BindUserVoucherResponse{}
	mi := &file_svapi_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindUserVoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindUserVoucherResponse) ProtoMessage() {}

func (x *BindUserVoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindUserVoucherResponse.ProtoReflect.Descriptor instead.
func (*BindUserVoucherResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{12}
}

type UnbindUserVoucherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoucherType   VoucherType            `protobuf:"varint,1,opt,name=voucher_type,json=voucherType,proto3,enum=svapi.VoucherType" json:"voucher_type,omitempty"`
	Voucher       string                 `protobuf:"bytes,2,opt,name=voucher,proto3" json:"voucher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindUserVoucherRequest) Reset() {
	*x = UnbindUserVoucherRequest{}
	mi := &file_svapi_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindUserVoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindUserVoucherRequest) ProtoMessage() {}

func (x *UnbindUserVoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindUserVoucherRequest.ProtoReflect.Descriptor instead.
func (*UnbindUserVoucherRequest) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{13}
}

func (x *UnbindUserVoucherRequest) GetVoucherType() VoucherType {
	if x != nil {
		return x.VoucherType
	}
	return VoucherType_PHONE
}

func (x *UnbindUserVoucherRequest) GetVoucher() string {
	if x != nil {
		return x.Voucher
	}
	return ""
}

type UnbindUserVoucherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindUserVoucherResponse) Reset() {
	*x = UnbindUserVoucherResponse{}
	mi := &file_svapi_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindUserVoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindUserVoucherResponse) ProtoMessage() {}

func (x *UnbindUserVoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svapi_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindUserVoucherResponse.ProtoReflect.Descriptor instead.
func (*UnbindUserVoucherResponse) Descriptor() ([]byte, []int) {
	return file_svapi_user_proto_rawDescGZIP(), []int{14}
}

var File_svapi_user_proto protoreflect.FileDescriptor

const file_svapi_user_proto_rawDesc = "" +
	"\n" +
	"\x10svapi/user.proto\x12\x05svapi\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x10svapi/base.proto\"\xed\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\x04 \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12 \n" +
	"\vfollowCount\x18\b \x01(\x03R\vfollowCount\x12$\n" +
	"\rfollowerCount\x18\t \x01(\x03R\rfollowerCount\x12&\n" +
	"\x0etotalFavorited\x18\n" +
	" \x01(\x03R\x0etotalFavorited\x12\x1c\n" +
	"\tworkCount\x18\v \x01(\x03R\tworkCount\x12$\n" +
	"\rfavoriteCount\x18\f \x01(\x03R\rfavoriteCount\"J\n" +
	"\x1aGetVerificationCodeRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"6\n" +
	"\x1bGetVerificationCodeResponse\x12\x17\n" +
	"\acode_id\x18\x01 \x01(\x03R\x06codeId\"\x93\x01\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\bpassword\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x06\x182R\bpassword\x12\x17\n" +
	"\acode_id\x18\x04 \x01(\x03R\x06codeId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x87\x01\n" +
	"\fLoginRequest\x121\n" +
	"\x06mobile\x18\x01 \x01(\tB\x19\xbaH\x16r\x142\x12^\\+?[1-9]\\d{1,14}$R\x06mobile\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12%\n" +
	"\bpassword\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\b\x182R\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"6\n" +
	"\x13GetUserInfoResponse\x12\x1f\n" +
	"\x04user\x18\x02 \x01(\v2\v.svapi.UserR\x04user\"\xb9\x01\n" +
	"\x15UpdateUserInfoRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x06userId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\x04 \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"\x18\n" +
	"\x16UpdateUserInfoResponse\"i\n" +
	"\x16BindUserVoucherRequest\x125\n" +
	"\fvoucher_type\x18\x01 \x01(\x0e2\x12.svapi.VoucherTypeR\vvoucherType\x12\x18\n" +
	"\avoucher\x18\x02 \x01(\tR\avoucher\"\x19\n" +
	"\x17BindUserVoucherResponse\"k\n" +
	"\x18UnbindUserVoucherRequest\x125\n" +
	"\fvoucher_type\x18\x01 \x01(\x0e2\x12.svapi.VoucherTypeR\vvoucherType\x12\x18\n" +
	"\avoucher\x18\x02 \x01(\tR\avoucher\"\x1b\n" +
	"\x19UnbindUserVoucherResponse*#\n" +
	"\vVoucherType\x12\t\n" +
	"\x05PHONE\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x012\xc4\x05\n" +
	"\vUserService\x12s\n" +
	"\x13GetVerificationCode\x12!.svapi.GetVerificationCodeRequest\x1a\".svapi.GetVerificationCodeResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/user/code\x12V\n" +
	"\bRegister\x12\x16.svapi.RegisterRequest\x1a\x17.svapi.RegisterResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/register\x12J\n" +
	"\x05Login\x12\x13.svapi.LoginRequest\x1a\x14.svapi.LoginResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12X\n" +
	"\vGetUserInfo\x12\x19.svapi.GetUserInfoRequest\x1a\x1a.svapi.GetUserInfoResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/user/info\x12d\n" +
	"\x0eUpdateUserInfo\x12\x1c.svapi.UpdateUserInfoRequest\x1a\x1d.svapi.UpdateUserInfoResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x1a\n" +
	"/user/info\x12j\n" +
	"\x0fBindUserVoucher\x12\x1d.svapi.BindUserVoucherRequest\x1a\x1e.svapi.BindUserVoucherResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/user/voucher\x12p\n" +
	"\x11UnbindUserVoucher\x12\x1f.svapi.UnbindUserVoucherRequest\x1a .svapi.UnbindUserVoucherResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01**\r/user/voucherB)Z'github.com/cloudzenith/DouTok/...;svapib\x06proto3"

var (
	file_svapi_user_proto_rawDescOnce sync.Once
	file_svapi_user_proto_rawDescData []byte
)

func file_svapi_user_proto_rawDescGZIP() []byte {
	file_svapi_user_proto_rawDescOnce.Do(func() {
		file_svapi_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svapi_user_proto_rawDesc), len(file_svapi_user_proto_rawDesc)))
	})
	return file_svapi_user_proto_rawDescData
}

var file_svapi_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svapi_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_svapi_user_proto_goTypes = []any{
	(VoucherType)(0),                    // 0: svapi.VoucherType
	(*User)(nil),                        // 1: svapi.User
	(*GetVerificationCodeRequest)(nil),  // 2: svapi.GetVerificationCodeRequest
	(*GetVerificationCodeResponse)(nil), // 3: svapi.GetVerificationCodeResponse
	(*RegisterRequest)(nil),             // 4: svapi.RegisterRequest
	(*RegisterResponse)(nil),            // 5: svapi.RegisterResponse
	(*LoginRequest)(nil),                // 6: svapi.LoginRequest
	(*LoginResponse)(nil),               // 7: svapi.LoginResponse
	(*GetUserInfoRequest)(nil),          // 8: svapi.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),         // 9: svapi.GetUserInfoResponse
	(*UpdateUserInfoRequest)(nil),       // 10: svapi.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil),      // 11: svapi.UpdateUserInfoResponse
	(*BindUserVoucherRequest)(nil),      // 12: svapi.BindUserVoucherRequest
	(*BindUserVoucherResponse)(nil),     // 13: svapi.BindUserVoucherResponse
	(*UnbindUserVoucherRequest)(nil),    // 14: svapi.UnbindUserVoucherRequest
	(*UnbindUserVoucherResponse)(nil),   // 15: svapi.UnbindUserVoucherResponse
}
var file_svapi_user_proto_depIdxs = []int32{
	1,  // 0: svapi.GetUserInfoResponse.user:type_name -> svapi.User
	0,  // 1: svapi.BindUserVoucherRequest.voucher_type:type_name -> svapi.VoucherType
	0,  // 2: svapi.UnbindUserVoucherRequest.voucher_type:type_name -> svapi.VoucherType
	2,  // 3: svapi.UserService.GetVerificationCode:input_type -> svapi.GetVerificationCodeRequest
	4,  // 4: svapi.UserService.Register:input_type -> svapi.RegisterRequest
	6,  // 5: svapi.UserService.Login:input_type -> svapi.LoginRequest
	8,  // 6: svapi.UserService.GetUserInfo:input_type -> svapi.GetUserInfoRequest
	10, // 7: svapi.UserService.UpdateUserInfo:input_type -> svapi.UpdateUserInfoRequest
	12, // 8: svapi.UserService.BindUserVoucher:input_type -> svapi.BindUserVoucherRequest
	14, // 9: svapi.UserService.UnbindUserVoucher:input_type -> svapi.UnbindUserVoucherRequest
	3,  // 10: svapi.UserService.GetVerificationCode:output_type -> svapi.GetVerificationCodeResponse
	5,  // 11: svapi.UserService.Register:output_type -> svapi.RegisterResponse
	7,  // 12: svapi.UserService.Login:output_type -> svapi.LoginResponse
	9,  // 13: svapi.UserService.GetUserInfo:output_type -> svapi.GetUserInfoResponse
	11, // 14: svapi.UserService.UpdateUserInfo:output_type -> svapi.UpdateUserInfoResponse
	13, // 15: svapi.UserService.BindUserVoucher:output_type -> svapi.BindUserVoucherResponse
	15, // 16: svapi.UserService.UnbindUserVoucher:output_type -> svapi.UnbindUserVoucherResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_svapi_user_proto_init() }
func file_svapi_user_proto_init() {
	if File_svapi_user_proto != nil {
		return
	}
	file_svapi_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svapi_user_proto_rawDesc), len(file_svapi_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svapi_user_proto_goTypes,
		DependencyIndexes: file_svapi_user_proto_depIdxs,
		EnumInfos:         file_svapi_user_proto_enumTypes,
		MessageInfos:      file_svapi_user_proto_msgTypes,
	}.Build()
	File_svapi_user_proto = out.File
	file_svapi_user_proto_goTypes = nil
	file_svapi_user_proto_depIdxs = nil
}
