// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/base.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_DESC SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortOrder_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_base_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_v1_base_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{0}
}

type SearchOperator int32

const (
	SearchOperator_EQ       SearchOperator = 0  // 等于
	SearchOperator_NE       SearchOperator = 1  // 不等于
	SearchOperator_GT       SearchOperator = 2  // 大于
	SearchOperator_GE       SearchOperator = 3  // 大于等于
	SearchOperator_LT       SearchOperator = 4  // 小于
	SearchOperator_LE       SearchOperator = 5  // 小于等于
	SearchOperator_LIKE     SearchOperator = 6  // 使用like的模糊匹配
	SearchOperator_WILDCARD SearchOperator = 7  // 使用通配符的模糊匹配
	SearchOperator_IN       SearchOperator = 8  // 在指定的集合中
	SearchOperator_NOT_IN   SearchOperator = 9  // 不在指定的集合中
	SearchOperator_BETWEEN  SearchOperator = 10 // 在指定的范围内
	SearchOperator_RE       SearchOperator = 11 // 正则匹配
)

// Enum value maps for SearchOperator.
var (
	SearchOperator_name = map[int32]string{
		0:  "EQ",
		1:  "NE",
		2:  "GT",
		3:  "GE",
		4:  "LT",
		5:  "LE",
		6:  "LIKE",
		7:  "WILDCARD",
		8:  "IN",
		9:  "NOT_IN",
		10: "BETWEEN",
		11: "RE",
	}
	SearchOperator_value = map[string]int32{
		"EQ":       0,
		"NE":       1,
		"GT":       2,
		"GE":       3,
		"LT":       4,
		"LE":       5,
		"LIKE":     6,
		"WILDCARD": 7,
		"IN":       8,
		"NOT_IN":   9,
		"BETWEEN":  10,
		"RE":       11,
	}
)

func (x SearchOperator) Enum() *SearchOperator {
	p := new(SearchOperator)
	*p = x
	return p
}

func (x SearchOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_base_proto_enumTypes[1].Descriptor()
}

func (SearchOperator) Type() protoreflect.EnumType {
	return &file_v1_base_proto_enumTypes[1]
}

func (x SearchOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchOperator.Descriptor instead.
func (SearchOperator) EnumDescriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{1}
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizCode       int32                  `protobuf:"varint,1,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason        []string               `protobuf:"bytes,4,rep,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_v1_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetBizCode() int32 {
	if x != nil {
		return x.BizCode
	}
	return 0
}

func (x *Metadata) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Metadata) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Metadata) GetReason() []string {
	if x != nil {
		return x.Reason
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                                              // 用于排序的字段名称
	Order         SortOrder              `protobuf:"varint,2,opt,name=order,proto3,enum=shortVideoCoreService.api.v1.SortOrder" json:"order,omitempty"` // 排序方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_v1_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_v1_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_ASC
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码 [1, +∞)
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 页面大小
	Sort          []*SortField           `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`  // 根据字段进行排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_v1_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PaginationRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 当前数据的所属页码
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总页数
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 总条目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_v1_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                                                         // 用于搜索的字段名称
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                                         // 搜索的值
	ValueList     []string               `protobuf:"bytes,3,rep,name=value_list,json=valueList,proto3" json:"value_list,omitempty"`                                // 搜索的值列表
	Operator      SearchOperator         `protobuf:"varint,4,opt,name=operator,proto3,enum=shortVideoCoreService.api.v1.SearchOperator" json:"operator,omitempty"` // 操作符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchField) Reset() {
	*x = SearchField{}
	mi := &file_v1_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchField) ProtoMessage() {}

func (x *SearchField) ProtoReflect() protoreflect.Message {
	mi := &file_v1_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchField.ProtoReflect.Descriptor instead.
func (*SearchField) Descriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{4}
}

func (x *SearchField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchField) GetValueList() []string {
	if x != nil {
		return x.ValueList
	}
	return nil
}

func (x *SearchField) GetOperator() SearchOperator {
	if x != nil {
		return x.Operator
	}
	return SearchOperator_EQ
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        []*SearchField         `protobuf:"bytes,1,rep,name=search,proto3" json:"search,omitempty"` // 搜索条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_v1_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_v1_base_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetSearch() []*SearchField {
	if x != nil {
		return x.Search
	}
	return nil
}

var File_v1_base_proto protoreflect.FileDescriptor

const file_v1_base_proto_rawDesc = "" +
	"\n" +
	"\rv1/base.proto\x12\x1cshortVideoCoreService.api.v1\x1a\x17validate/validate.proto\"o\n" +
	"\bMetadata\x12\x19\n" +
	"\bbiz_code\x18\x01 \x01(\x05R\abizCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x04 \x03(\tR\x06reason\"`\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12=\n" +
	"\x05order\x18\x02 \x01(\x0e2'.shortVideoCoreService.api.v1.SortOrderR\x05order\"\x8a\x01\n" +
	"\x11PaginationRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04page\x12\x1b\n" +
	"\x04size\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04size\x12;\n" +
	"\x04sort\x18\x03 \x03(\v2'.shortVideoCoreService.api.v1.SortFieldR\x04sort\"T\n" +
	"\x12PaginationResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xa2\x01\n" +
	"\vSearchField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"value_list\x18\x03 \x03(\tR\tvalueList\x12H\n" +
	"\boperator\x18\x04 \x01(\x0e2,.shortVideoCoreService.api.v1.SearchOperatorR\boperator\"R\n" +
	"\rSearchRequest\x12A\n" +
	"\x06search\x18\x01 \x03(\v2).shortVideoCoreService.api.v1.SearchFieldR\x06search*\x1e\n" +
	"\tSortOrder\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01*\x81\x01\n" +
	"\x0eSearchOperator\x12\x06\n" +
	"\x02EQ\x10\x00\x12\x06\n" +
	"\x02NE\x10\x01\x12\x06\n" +
	"\x02GT\x10\x02\x12\x06\n" +
	"\x02GE\x10\x03\x12\x06\n" +
	"\x02LT\x10\x04\x12\x06\n" +
	"\x02LE\x10\x05\x12\b\n" +
	"\x04LIKE\x10\x06\x12\f\n" +
	"\bWILDCARD\x10\a\x12\x06\n" +
	"\x02IN\x10\b\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\t\x12\v\n" +
	"\aBETWEEN\x10\n" +
	"\x12\x06\n" +
	"\x02RE\x10\vBGZEgithub.com/cloudzenith/DouTok/backend/shortVideoCoreService/api/v1;v1b\x06proto3"

var (
	file_v1_base_proto_rawDescOnce sync.Once
	file_v1_base_proto_rawDescData []byte
)

func file_v1_base_proto_rawDescGZIP() []byte {
	file_v1_base_proto_rawDescOnce.Do(func() {
		file_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_base_proto_rawDesc), len(file_v1_base_proto_rawDesc)))
	})
	return file_v1_base_proto_rawDescData
}

var file_v1_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_base_proto_goTypes = []any{
	(SortOrder)(0),             // 0: shortVideoCoreService.api.v1.SortOrder
	(SearchOperator)(0),        // 1: shortVideoCoreService.api.v1.SearchOperator
	(*Metadata)(nil),           // 2: shortVideoCoreService.api.v1.Metadata
	(*SortField)(nil),          // 3: shortVideoCoreService.api.v1.SortField
	(*PaginationRequest)(nil),  // 4: shortVideoCoreService.api.v1.PaginationRequest
	(*PaginationResponse)(nil), // 5: shortVideoCoreService.api.v1.PaginationResponse
	(*SearchField)(nil),        // 6: shortVideoCoreService.api.v1.SearchField
	(*SearchRequest)(nil),      // 7: shortVideoCoreService.api.v1.SearchRequest
}
var file_v1_base_proto_depIdxs = []int32{
	0, // 0: shortVideoCoreService.api.v1.SortField.order:type_name -> shortVideoCoreService.api.v1.SortOrder
	3, // 1: shortVideoCoreService.api.v1.PaginationRequest.sort:type_name -> shortVideoCoreService.api.v1.SortField
	1, // 2: shortVideoCoreService.api.v1.SearchField.operator:type_name -> shortVideoCoreService.api.v1.SearchOperator
	6, // 3: shortVideoCoreService.api.v1.SearchRequest.search:type_name -> shortVideoCoreService.api.v1.SearchField
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_base_proto_init() }
func file_v1_base_proto_init() {
	if File_v1_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_base_proto_rawDesc), len(file_v1_base_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_base_proto_goTypes,
		DependencyIndexes: file_v1_base_proto_depIdxs,
		EnumInfos:         file_v1_base_proto_enumTypes,
		MessageInfos:      file_v1_base_proto_msgTypes,
	}.Build()
	File_v1_base_proto = out.File
	file_v1_base_proto_goTypes = nil
	file_v1_base_proto_depIdxs = nil
}
