// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/collection.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_v1_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Collection) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_v1_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCollectionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_v1_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetCollectionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionByIdRequest) Reset() {
	*x = GetCollectionByIdRequest{}
	mi := &file_v1_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionByIdRequest) ProtoMessage() {}

func (x *GetCollectionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionByIdRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{3}
}

func (x *GetCollectionByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCollectionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionByIdResponse) Reset() {
	*x = GetCollectionByIdResponse{}
	mi := &file_v1_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionByIdResponse) ProtoMessage() {}

func (x *GetCollectionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionByIdResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{4}
}

func (x *GetCollectionByIdResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *GetCollectionByIdResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RemoveCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollectionRequest) Reset() {
	*x = RemoveCollectionRequest{}
	mi := &file_v1_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionRequest) ProtoMessage() {}

func (x *RemoveCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveCollectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollectionResponse) Reset() {
	*x = RemoveCollectionResponse{}
	mi := &file_v1_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionResponse) ProtoMessage() {}

func (x *RemoveCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveCollectionResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionRequest) Reset() {
	*x = ListCollectionRequest{}
	mi := &file_v1_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionRequest) ProtoMessage() {}

func (x *ListCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{7}
}

func (x *ListCollectionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListCollectionRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionResponse) Reset() {
	*x = ListCollectionResponse{}
	mi := &file_v1_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionResponse) ProtoMessage() {}

func (x *ListCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{8}
}

func (x *ListCollectionResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListCollectionResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_v1_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCollectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionResponse) Reset() {
	*x = UpdateCollectionResponse{}
	mi := &file_v1_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionResponse) ProtoMessage() {}

func (x *UpdateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCollectionResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AddVideo2CollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  int64                  `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 不传则添加到默认收藏夹
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideo2CollectionRequest) Reset() {
	*x = AddVideo2CollectionRequest{}
	mi := &file_v1_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideo2CollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideo2CollectionRequest) ProtoMessage() {}

func (x *AddVideo2CollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideo2CollectionRequest.ProtoReflect.Descriptor instead.
func (*AddVideo2CollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{11}
}

func (x *AddVideo2CollectionRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *AddVideo2CollectionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *AddVideo2CollectionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddVideo2CollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideo2CollectionResponse) Reset() {
	*x = AddVideo2CollectionResponse{}
	mi := &file_v1_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideo2CollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideo2CollectionResponse) ProtoMessage() {}

func (x *AddVideo2CollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideo2CollectionResponse.ProtoReflect.Descriptor instead.
func (*AddVideo2CollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{12}
}

func (x *AddVideo2CollectionResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RemoveVideoFromCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  int64                  `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoFromCollectionRequest) Reset() {
	*x = RemoveVideoFromCollectionRequest{}
	mi := &file_v1_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoFromCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoFromCollectionRequest) ProtoMessage() {}

func (x *RemoveVideoFromCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoFromCollectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveVideoFromCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveVideoFromCollectionRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *RemoveVideoFromCollectionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *RemoveVideoFromCollectionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveVideoFromCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoFromCollectionResponse) Reset() {
	*x = RemoveVideoFromCollectionResponse{}
	mi := &file_v1_collection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoFromCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoFromCollectionResponse) ProtoMessage() {}

func (x *RemoveVideoFromCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoFromCollectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveVideoFromCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveVideoFromCollectionResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListCollectionVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  int64                  `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionVideoRequest) Reset() {
	*x = ListCollectionVideoRequest{}
	mi := &file_v1_collection_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionVideoRequest) ProtoMessage() {}

func (x *ListCollectionVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionVideoRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionVideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{15}
}

func (x *ListCollectionVideoRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *ListCollectionVideoRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCollectionVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIdList   []int64                `protobuf:"varint,1,rep,packed,name=video_id_list,json=videoIdList,proto3" json:"video_id_list,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionVideoResponse) Reset() {
	*x = ListCollectionVideoResponse{}
	mi := &file_v1_collection_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionVideoResponse) ProtoMessage() {}

func (x *ListCollectionVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionVideoResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionVideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{16}
}

func (x *ListCollectionVideoResponse) GetVideoIdList() []int64 {
	if x != nil {
		return x.VideoIdList
	}
	return nil
}

func (x *ListCollectionVideoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListCollectionVideoResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type IsCollectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoIdList   []int64                `protobuf:"varint,2,rep,packed,name=video_id_list,json=videoIdList,proto3" json:"video_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCollectedRequest) Reset() {
	*x = IsCollectedRequest{}
	mi := &file_v1_collection_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCollectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCollectedRequest) ProtoMessage() {}

func (x *IsCollectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCollectedRequest.ProtoReflect.Descriptor instead.
func (*IsCollectedRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{17}
}

func (x *IsCollectedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsCollectedRequest) GetVideoIdList() []int64 {
	if x != nil {
		return x.VideoIdList
	}
	return nil
}

type IsCollectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIdList   []int64                `protobuf:"varint,1,rep,packed,name=video_id_list,json=videoIdList,proto3" json:"video_id_list,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCollectedResponse) Reset() {
	*x = IsCollectedResponse{}
	mi := &file_v1_collection_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCollectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCollectedResponse) ProtoMessage() {}

func (x *IsCollectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCollectedResponse.ProtoReflect.Descriptor instead.
func (*IsCollectedResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{18}
}

func (x *IsCollectedResponse) GetVideoIdList() []int64 {
	if x != nil {
		return x.VideoIdList
	}
	return nil
}

func (x *IsCollectedResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CountCollect4VideoResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountCollect4VideoResult) Reset() {
	*x = CountCollect4VideoResult{}
	mi := &file_v1_collection_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountCollect4VideoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCollect4VideoResult) ProtoMessage() {}

func (x *CountCollect4VideoResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCollect4VideoResult.ProtoReflect.Descriptor instead.
func (*CountCollect4VideoResult) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{19}
}

func (x *CountCollect4VideoResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CountCollect4VideoResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CountCollect4VideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIdList   []int64                `protobuf:"varint,1,rep,packed,name=video_id_list,json=videoIdList,proto3" json:"video_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountCollect4VideoRequest) Reset() {
	*x = CountCollect4VideoRequest{}
	mi := &file_v1_collection_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountCollect4VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCollect4VideoRequest) ProtoMessage() {}

func (x *CountCollect4VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCollect4VideoRequest.ProtoReflect.Descriptor instead.
func (*CountCollect4VideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{20}
}

func (x *CountCollect4VideoRequest) GetVideoIdList() []int64 {
	if x != nil {
		return x.VideoIdList
	}
	return nil
}

type CountCollect4VideoResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CountResult   []*CountCollect4VideoResult `protobuf:"bytes,1,rep,name=count_result,json=countResult,proto3" json:"count_result,omitempty"`
	Meta          *Metadata                   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountCollect4VideoResponse) Reset() {
	*x = CountCollect4VideoResponse{}
	mi := &file_v1_collection_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountCollect4VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountCollect4VideoResponse) ProtoMessage() {}

func (x *CountCollect4VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_collection_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountCollect4VideoResponse.ProtoReflect.Descriptor instead.
func (*CountCollect4VideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_collection_proto_rawDescGZIP(), []int{21}
}

func (x *CountCollect4VideoResponse) GetCountResult() []*CountCollect4VideoResult {
	if x != nil {
		return x.CountResult
	}
	return nil
}

func (x *CountCollect4VideoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_v1_collection_proto protoreflect.FileDescriptor

const file_v1_collection_proto_rawDesc = "" +
	"\n" +
	"\x13v1/collection.proto\x12\x1cshortVideoCoreService.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\rv1/base.proto\"k\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"h\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"V\n" +
	"\x18CreateCollectionResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"*\n" +
	"\x18GetCollectionByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa1\x01\n" +
	"\x19GetCollectionByIdResponse\x12H\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2(.shortVideoCoreService.api.v1.CollectionR\n" +
	"collection\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\")\n" +
	"\x17RemoveCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x18RemoveCollectionResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"\x81\x01\n" +
	"\x15ListCollectionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12O\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2/.shortVideoCoreService.api.v1.PaginationRequestR\n" +
	"pagination\"\xf2\x01\n" +
	"\x16ListCollectionResponse\x12J\n" +
	"\vcollections\x18\x01 \x03(\v2(.shortVideoCoreService.api.v1.CollectionR\vcollections\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12P\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v20.shortVideoCoreService.api.v1.PaginationResponseR\n" +
	"pagination\"_\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"V\n" +
	"\x18UpdateCollectionResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"u\n" +
	"\x1aAddVideo2CollectionRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"Y\n" +
	"\x1bAddVideo2CollectionResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"{\n" +
	" RemoveVideoFromCollectionRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"_\n" +
	"!RemoveVideoFromCollectionResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"\x92\x01\n" +
	"\x1aListCollectionVideoRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12O\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2/.shortVideoCoreService.api.v1.PaginationRequestR\n" +
	"pagination\"\xcf\x01\n" +
	"\x1bListCollectionVideoResponse\x12\"\n" +
	"\rvideo_id_list\x18\x01 \x03(\x03R\vvideoIdList\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12P\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v20.shortVideoCoreService.api.v1.PaginationResponseR\n" +
	"pagination\"Q\n" +
	"\x12IsCollectedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\"\n" +
	"\rvideo_id_list\x18\x02 \x03(\x03R\vvideoIdList\"u\n" +
	"\x13IsCollectedResponse\x12\"\n" +
	"\rvideo_id_list\x18\x01 \x03(\x03R\vvideoIdList\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"@\n" +
	"\x18CountCollect4VideoResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"?\n" +
	"\x19CountCollect4VideoRequest\x12\"\n" +
	"\rvideo_id_list\x18\x01 \x03(\x03R\vvideoIdList\"\xb3\x01\n" +
	"\x1aCountCollect4VideoResponse\x12Y\n" +
	"\fcount_result\x18\x01 \x03(\v26.shortVideoCoreService.api.v1.CountCollect4VideoResultR\vcountResult\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta2\xda\n" +
	"\n" +
	"\x11CollectionService\x12\x81\x01\n" +
	"\x10CreateCollection\x125.shortVideoCoreService.api.v1.CreateCollectionRequest\x1a6.shortVideoCoreService.api.v1.CreateCollectionResponse\x12\x84\x01\n" +
	"\x11GetCollectionById\x126.shortVideoCoreService.api.v1.GetCollectionByIdRequest\x1a7.shortVideoCoreService.api.v1.GetCollectionByIdResponse\x12\x81\x01\n" +
	"\x10RemoveCollection\x125.shortVideoCoreService.api.v1.RemoveCollectionRequest\x1a6.shortVideoCoreService.api.v1.RemoveCollectionResponse\x12{\n" +
	"\x0eListCollection\x123.shortVideoCoreService.api.v1.ListCollectionRequest\x1a4.shortVideoCoreService.api.v1.ListCollectionResponse\x12\x81\x01\n" +
	"\x10UpdateCollection\x125.shortVideoCoreService.api.v1.UpdateCollectionRequest\x1a6.shortVideoCoreService.api.v1.UpdateCollectionResponse\x12\x8a\x01\n" +
	"\x13AddVideo2Collection\x128.shortVideoCoreService.api.v1.AddVideo2CollectionRequest\x1a9.shortVideoCoreService.api.v1.AddVideo2CollectionResponse\x12\x9c\x01\n" +
	"\x19RemoveVideoFromCollection\x12>.shortVideoCoreService.api.v1.RemoveVideoFromCollectionRequest\x1a?.shortVideoCoreService.api.v1.RemoveVideoFromCollectionResponse\x12\x8a\x01\n" +
	"\x13ListCollectionVideo\x128.shortVideoCoreService.api.v1.ListCollectionVideoRequest\x1a9.shortVideoCoreService.api.v1.ListCollectionVideoResponse\x12r\n" +
	"\vIsCollected\x120.shortVideoCoreService.api.v1.IsCollectedRequest\x1a1.shortVideoCoreService.api.v1.IsCollectedResponse\x12\x87\x01\n" +
	"\x12CountCollect4Video\x127.shortVideoCoreService.api.v1.CountCollect4VideoRequest\x1a8.shortVideoCoreService.api.v1.CountCollect4VideoResponseBGZEgithub.com/cloudzenith/DouTok/backend/shortVideoCoreService/api/v1;v1b\x06proto3"

var (
	file_v1_collection_proto_rawDescOnce sync.Once
	file_v1_collection_proto_rawDescData []byte
)

func file_v1_collection_proto_rawDescGZIP() []byte {
	file_v1_collection_proto_rawDescOnce.Do(func() {
		file_v1_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_collection_proto_rawDesc), len(file_v1_collection_proto_rawDesc)))
	})
	return file_v1_collection_proto_rawDescData
}

var file_v1_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_v1_collection_proto_goTypes = []any{
	(*Collection)(nil),                        // 0: shortVideoCoreService.api.v1.Collection
	(*CreateCollectionRequest)(nil),           // 1: shortVideoCoreService.api.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),          // 2: shortVideoCoreService.api.v1.CreateCollectionResponse
	(*GetCollectionByIdRequest)(nil),          // 3: shortVideoCoreService.api.v1.GetCollectionByIdRequest
	(*GetCollectionByIdResponse)(nil),         // 4: shortVideoCoreService.api.v1.GetCollectionByIdResponse
	(*RemoveCollectionRequest)(nil),           // 5: shortVideoCoreService.api.v1.RemoveCollectionRequest
	(*RemoveCollectionResponse)(nil),          // 6: shortVideoCoreService.api.v1.RemoveCollectionResponse
	(*ListCollectionRequest)(nil),             // 7: shortVideoCoreService.api.v1.ListCollectionRequest
	(*ListCollectionResponse)(nil),            // 8: shortVideoCoreService.api.v1.ListCollectionResponse
	(*UpdateCollectionRequest)(nil),           // 9: shortVideoCoreService.api.v1.UpdateCollectionRequest
	(*UpdateCollectionResponse)(nil),          // 10: shortVideoCoreService.api.v1.UpdateCollectionResponse
	(*AddVideo2CollectionRequest)(nil),        // 11: shortVideoCoreService.api.v1.AddVideo2CollectionRequest
	(*AddVideo2CollectionResponse)(nil),       // 12: shortVideoCoreService.api.v1.AddVideo2CollectionResponse
	(*RemoveVideoFromCollectionRequest)(nil),  // 13: shortVideoCoreService.api.v1.RemoveVideoFromCollectionRequest
	(*RemoveVideoFromCollectionResponse)(nil), // 14: shortVideoCoreService.api.v1.RemoveVideoFromCollectionResponse
	(*ListCollectionVideoRequest)(nil),        // 15: shortVideoCoreService.api.v1.ListCollectionVideoRequest
	(*ListCollectionVideoResponse)(nil),       // 16: shortVideoCoreService.api.v1.ListCollectionVideoResponse
	(*IsCollectedRequest)(nil),                // 17: shortVideoCoreService.api.v1.IsCollectedRequest
	(*IsCollectedResponse)(nil),               // 18: shortVideoCoreService.api.v1.IsCollectedResponse
	(*CountCollect4VideoResult)(nil),          // 19: shortVideoCoreService.api.v1.CountCollect4VideoResult
	(*CountCollect4VideoRequest)(nil),         // 20: shortVideoCoreService.api.v1.CountCollect4VideoRequest
	(*CountCollect4VideoResponse)(nil),        // 21: shortVideoCoreService.api.v1.CountCollect4VideoResponse
	(*Metadata)(nil),                          // 22: shortVideoCoreService.api.v1.Metadata
	(*PaginationRequest)(nil),                 // 23: shortVideoCoreService.api.v1.PaginationRequest
	(*PaginationResponse)(nil),                // 24: shortVideoCoreService.api.v1.PaginationResponse
}
var file_v1_collection_proto_depIdxs = []int32{
	22, // 0: shortVideoCoreService.api.v1.CreateCollectionResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	0,  // 1: shortVideoCoreService.api.v1.GetCollectionByIdResponse.collection:type_name -> shortVideoCoreService.api.v1.Collection
	22, // 2: shortVideoCoreService.api.v1.GetCollectionByIdResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	22, // 3: shortVideoCoreService.api.v1.RemoveCollectionResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	23, // 4: shortVideoCoreService.api.v1.ListCollectionRequest.pagination:type_name -> shortVideoCoreService.api.v1.PaginationRequest
	0,  // 5: shortVideoCoreService.api.v1.ListCollectionResponse.collections:type_name -> shortVideoCoreService.api.v1.Collection
	22, // 6: shortVideoCoreService.api.v1.ListCollectionResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	24, // 7: shortVideoCoreService.api.v1.ListCollectionResponse.pagination:type_name -> shortVideoCoreService.api.v1.PaginationResponse
	22, // 8: shortVideoCoreService.api.v1.UpdateCollectionResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	22, // 9: shortVideoCoreService.api.v1.AddVideo2CollectionResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	22, // 10: shortVideoCoreService.api.v1.RemoveVideoFromCollectionResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	23, // 11: shortVideoCoreService.api.v1.ListCollectionVideoRequest.pagination:type_name -> shortVideoCoreService.api.v1.PaginationRequest
	22, // 12: shortVideoCoreService.api.v1.ListCollectionVideoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	24, // 13: shortVideoCoreService.api.v1.ListCollectionVideoResponse.pagination:type_name -> shortVideoCoreService.api.v1.PaginationResponse
	22, // 14: shortVideoCoreService.api.v1.IsCollectedResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	19, // 15: shortVideoCoreService.api.v1.CountCollect4VideoResponse.count_result:type_name -> shortVideoCoreService.api.v1.CountCollect4VideoResult
	22, // 16: shortVideoCoreService.api.v1.CountCollect4VideoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 17: shortVideoCoreService.api.v1.CollectionService.CreateCollection:input_type -> shortVideoCoreService.api.v1.CreateCollectionRequest
	3,  // 18: shortVideoCoreService.api.v1.CollectionService.GetCollectionById:input_type -> shortVideoCoreService.api.v1.GetCollectionByIdRequest
	5,  // 19: shortVideoCoreService.api.v1.CollectionService.RemoveCollection:input_type -> shortVideoCoreService.api.v1.RemoveCollectionRequest
	7,  // 20: shortVideoCoreService.api.v1.CollectionService.ListCollection:input_type -> shortVideoCoreService.api.v1.ListCollectionRequest
	9,  // 21: shortVideoCoreService.api.v1.CollectionService.UpdateCollection:input_type -> shortVideoCoreService.api.v1.UpdateCollectionRequest
	11, // 22: shortVideoCoreService.api.v1.CollectionService.AddVideo2Collection:input_type -> shortVideoCoreService.api.v1.AddVideo2CollectionRequest
	13, // 23: shortVideoCoreService.api.v1.CollectionService.RemoveVideoFromCollection:input_type -> shortVideoCoreService.api.v1.RemoveVideoFromCollectionRequest
	15, // 24: shortVideoCoreService.api.v1.CollectionService.ListCollectionVideo:input_type -> shortVideoCoreService.api.v1.ListCollectionVideoRequest
	17, // 25: shortVideoCoreService.api.v1.CollectionService.IsCollected:input_type -> shortVideoCoreService.api.v1.IsCollectedRequest
	20, // 26: shortVideoCoreService.api.v1.CollectionService.CountCollect4Video:input_type -> shortVideoCoreService.api.v1.CountCollect4VideoRequest
	2,  // 27: shortVideoCoreService.api.v1.CollectionService.CreateCollection:output_type -> shortVideoCoreService.api.v1.CreateCollectionResponse
	4,  // 28: shortVideoCoreService.api.v1.CollectionService.GetCollectionById:output_type -> shortVideoCoreService.api.v1.GetCollectionByIdResponse
	6,  // 29: shortVideoCoreService.api.v1.CollectionService.RemoveCollection:output_type -> shortVideoCoreService.api.v1.RemoveCollectionResponse
	8,  // 30: shortVideoCoreService.api.v1.CollectionService.ListCollection:output_type -> shortVideoCoreService.api.v1.ListCollectionResponse
	10, // 31: shortVideoCoreService.api.v1.CollectionService.UpdateCollection:output_type -> shortVideoCoreService.api.v1.UpdateCollectionResponse
	12, // 32: shortVideoCoreService.api.v1.CollectionService.AddVideo2Collection:output_type -> shortVideoCoreService.api.v1.AddVideo2CollectionResponse
	14, // 33: shortVideoCoreService.api.v1.CollectionService.RemoveVideoFromCollection:output_type -> shortVideoCoreService.api.v1.RemoveVideoFromCollectionResponse
	16, // 34: shortVideoCoreService.api.v1.CollectionService.ListCollectionVideo:output_type -> shortVideoCoreService.api.v1.ListCollectionVideoResponse
	18, // 35: shortVideoCoreService.api.v1.CollectionService.IsCollected:output_type -> shortVideoCoreService.api.v1.IsCollectedResponse
	21, // 36: shortVideoCoreService.api.v1.CollectionService.CountCollect4Video:output_type -> shortVideoCoreService.api.v1.CountCollect4VideoResponse
	27, // [27:37] is the sub-list for method output_type
	17, // [17:27] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_v1_collection_proto_init() }
func file_v1_collection_proto_init() {
	if File_v1_collection_proto != nil {
		return
	}
	file_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_collection_proto_rawDesc), len(file_v1_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_collection_proto_goTypes,
		DependencyIndexes: file_v1_collection_proto_depIdxs,
		MessageInfos:      file_v1_collection_proto_msgTypes,
	}.Build()
	File_v1_collection_proto = out.File
	file_v1_collection_proto_goTypes = nil
	file_v1_collection_proto_depIdxs = nil
}
