// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/favorite.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteTarget int32

const (
	FavoriteTarget_VIDEO   FavoriteTarget = 0
	FavoriteTarget_COMMENT FavoriteTarget = 1
)

// Enum value maps for FavoriteTarget.
var (
	FavoriteTarget_name = map[int32]string{
		0: "VIDEO",
		1: "COMMENT",
	}
	FavoriteTarget_value = map[string]int32{
		"VIDEO":   0,
		"COMMENT": 1,
	}
)

func (x FavoriteTarget) Enum() *FavoriteTarget {
	p := new(FavoriteTarget)
	*p = x
	return p
}

func (x FavoriteTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_favorite_proto_enumTypes[0].Descriptor()
}

func (FavoriteTarget) Type() protoreflect.EnumType {
	return &file_v1_favorite_proto_enumTypes[0]
}

func (x FavoriteTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteTarget.Descriptor instead.
func (FavoriteTarget) EnumDescriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{0}
}

type FavoriteType int32

const (
	FavoriteType_FAVORITE FavoriteType = 0 // 点赞
	FavoriteType_UNLIKE   FavoriteType = 1 // 点踩
)

// Enum value maps for FavoriteType.
var (
	FavoriteType_name = map[int32]string{
		0: "FAVORITE",
		1: "UNLIKE",
	}
	FavoriteType_value = map[string]int32{
		"FAVORITE": 0,
		"UNLIKE":   1,
	}
)

func (x FavoriteType) Enum() *FavoriteType {
	p := new(FavoriteType)
	*p = x
	return p
}

func (x FavoriteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_favorite_proto_enumTypes[1].Descriptor()
}

func (FavoriteType) Type() protoreflect.EnumType {
	return &file_v1_favorite_proto_enumTypes[1]
}

func (x FavoriteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteType.Descriptor instead.
func (FavoriteType) EnumDescriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{1}
}

type FavoriteAggregateType int32

const (
	FavoriteAggregateType_BY_VIDEO   FavoriteAggregateType = 0
	FavoriteAggregateType_BY_COMMENT FavoriteAggregateType = 1
	FavoriteAggregateType_BY_USER    FavoriteAggregateType = 2
)

// Enum value maps for FavoriteAggregateType.
var (
	FavoriteAggregateType_name = map[int32]string{
		0: "BY_VIDEO",
		1: "BY_COMMENT",
		2: "BY_USER",
	}
	FavoriteAggregateType_value = map[string]int32{
		"BY_VIDEO":   0,
		"BY_COMMENT": 1,
		"BY_USER":    2,
	}
)

func (x FavoriteAggregateType) Enum() *FavoriteAggregateType {
	p := new(FavoriteAggregateType)
	*p = x
	return p
}

func (x FavoriteAggregateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteAggregateType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_favorite_proto_enumTypes[2].Descriptor()
}

func (FavoriteAggregateType) Type() protoreflect.EnumType {
	return &file_v1_favorite_proto_enumTypes[2]
}

func (x FavoriteAggregateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteAggregateType.Descriptor instead.
func (FavoriteAggregateType) EnumDescriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{2}
}

type AddFavoriteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target FavoriteTarget         `protobuf:"varint,1,opt,name=target,proto3,enum=shortVideoCoreService.api.v1.FavoriteTarget" json:"target,omitempty"`
	Type   FavoriteType           `protobuf:"varint,2,opt,name=type,proto3,enum=shortVideoCoreService.api.v1.FavoriteType" json:"type,omitempty"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_v1_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *AddFavoriteRequest) GetTarget() FavoriteTarget {
	if x != nil {
		return x.Target
	}
	return FavoriteTarget_VIDEO
}

func (x *AddFavoriteRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE
}

func (x *AddFavoriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddFavoriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_v1_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *AddFavoriteResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RemoveFavoriteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target FavoriteTarget         `protobuf:"varint,1,opt,name=target,proto3,enum=shortVideoCoreService.api.v1.FavoriteTarget" json:"target,omitempty"`
	Type   FavoriteType           `protobuf:"varint,2,opt,name=type,proto3,enum=shortVideoCoreService.api.v1.FavoriteType" json:"type,omitempty"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_v1_favorite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFavoriteRequest) GetTarget() FavoriteTarget {
	if x != nil {
		return x.Target
	}
	return FavoriteTarget_VIDEO
}

func (x *RemoveFavoriteRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE
}

func (x *RemoveFavoriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RemoveFavoriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteResponse) Reset() {
	*x = RemoveFavoriteResponse{}
	mi := &file_v1_favorite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteResponse) ProtoMessage() {}

func (x *RemoveFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteResponse.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFavoriteResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateType FavoriteAggregateType  `protobuf:"varint,1,opt,name=aggregate_type,json=aggregateType,proto3,enum=shortVideoCoreService.api.v1.FavoriteAggregateType" json:"aggregate_type,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	FavoriteType  FavoriteType           `protobuf:"varint,4,opt,name=favorite_type,json=favoriteType,proto3,enum=shortVideoCoreService.api.v1.FavoriteType" json:"favorite_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteRequest) Reset() {
	*x = ListFavoriteRequest{}
	mi := &file_v1_favorite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteRequest) ProtoMessage() {}

func (x *ListFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteRequest.ProtoReflect.Descriptor instead.
func (*ListFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{4}
}

func (x *ListFavoriteRequest) GetAggregateType() FavoriteAggregateType {
	if x != nil {
		return x.AggregateType
	}
	return FavoriteAggregateType_BY_VIDEO
}

func (x *ListFavoriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListFavoriteRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListFavoriteRequest) GetFavoriteType() FavoriteType {
	if x != nil {
		return x.FavoriteType
	}
	return FavoriteType_FAVORITE
}

type ListFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	BizId         []int64                `protobuf:"varint,2,rep,packed,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteResponse) Reset() {
	*x = ListFavoriteResponse{}
	mi := &file_v1_favorite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteResponse) ProtoMessage() {}

func (x *ListFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteResponse.ProtoReflect.Descriptor instead.
func (*ListFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{5}
}

func (x *ListFavoriteResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListFavoriteResponse) GetBizId() []int64 {
	if x != nil {
		return x.BizId
	}
	return nil
}

func (x *ListFavoriteResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CountFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateType FavoriteAggregateType  `protobuf:"varint,1,opt,name=aggregate_type,json=aggregateType,proto3,enum=shortVideoCoreService.api.v1.FavoriteAggregateType" json:"aggregate_type,omitempty"`
	Id            []int64                `protobuf:"varint,2,rep,packed,name=id,proto3" json:"id,omitempty"`
	FavoriteType  FavoriteType           `protobuf:"varint,4,opt,name=favorite_type,json=favoriteType,proto3,enum=shortVideoCoreService.api.v1.FavoriteType" json:"favorite_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountFavoriteRequest) Reset() {
	*x = CountFavoriteRequest{}
	mi := &file_v1_favorite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountFavoriteRequest) ProtoMessage() {}

func (x *CountFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountFavoriteRequest.ProtoReflect.Descriptor instead.
func (*CountFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{6}
}

func (x *CountFavoriteRequest) GetAggregateType() FavoriteAggregateType {
	if x != nil {
		return x.AggregateType
	}
	return FavoriteAggregateType_BY_VIDEO
}

func (x *CountFavoriteRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CountFavoriteRequest) GetFavoriteType() FavoriteType {
	if x != nil {
		return x.FavoriteType
	}
	return FavoriteType_FAVORITE
}

type CountFavoriteResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountFavoriteResponseItem) Reset() {
	*x = CountFavoriteResponseItem{}
	mi := &file_v1_favorite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountFavoriteResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountFavoriteResponseItem) ProtoMessage() {}

func (x *CountFavoriteResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountFavoriteResponseItem.ProtoReflect.Descriptor instead.
func (*CountFavoriteResponseItem) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{7}
}

func (x *CountFavoriteResponseItem) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *CountFavoriteResponseItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CountFavoriteResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Meta          *Metadata                    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Items         []*CountFavoriteResponseItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountFavoriteResponse) Reset() {
	*x = CountFavoriteResponse{}
	mi := &file_v1_favorite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountFavoriteResponse) ProtoMessage() {}

func (x *CountFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountFavoriteResponse.ProtoReflect.Descriptor instead.
func (*CountFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{8}
}

func (x *CountFavoriteResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CountFavoriteResponse) GetItems() []*CountFavoriteResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type IsFavoriteRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,3,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteRequestItem) Reset() {
	*x = IsFavoriteRequestItem{}
	mi := &file_v1_favorite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteRequestItem) ProtoMessage() {}

func (x *IsFavoriteRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteRequestItem.ProtoReflect.Descriptor instead.
func (*IsFavoriteRequestItem) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{9}
}

func (x *IsFavoriteRequestItem) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *IsFavoriteRequestItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsFavoriteRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Target        FavoriteTarget           `protobuf:"varint,1,opt,name=target,proto3,enum=shortVideoCoreService.api.v1.FavoriteTarget" json:"target,omitempty"`
	Type          FavoriteType             `protobuf:"varint,2,opt,name=type,proto3,enum=shortVideoCoreService.api.v1.FavoriteType" json:"type,omitempty"`
	BizId         int64                    `protobuf:"varint,3,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	UserId        int64                    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*IsFavoriteRequestItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteRequest) Reset() {
	*x = IsFavoriteRequest{}
	mi := &file_v1_favorite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteRequest) ProtoMessage() {}

func (x *IsFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteRequest.ProtoReflect.Descriptor instead.
func (*IsFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{10}
}

func (x *IsFavoriteRequest) GetTarget() FavoriteTarget {
	if x != nil {
		return x.Target
	}
	return FavoriteTarget_VIDEO
}

func (x *IsFavoriteRequest) GetType() FavoriteType {
	if x != nil {
		return x.Type
	}
	return FavoriteType_FAVORITE
}

func (x *IsFavoriteRequest) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *IsFavoriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsFavoriteRequest) GetItems() []*IsFavoriteRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type IsFavoriteResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,3,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteResponseItem) Reset() {
	*x = IsFavoriteResponseItem{}
	mi := &file_v1_favorite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteResponseItem) ProtoMessage() {}

func (x *IsFavoriteResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteResponseItem.ProtoReflect.Descriptor instead.
func (*IsFavoriteResponseItem) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{11}
}

func (x *IsFavoriteResponseItem) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *IsFavoriteResponseItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsFavoriteResponseItem) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type IsFavoriteResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Meta          *Metadata                 `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	IsFavorite    bool                      `protobuf:"varint,2,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	Result        []*IsFavoriteResponseItem `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteResponse) Reset() {
	*x = IsFavoriteResponse{}
	mi := &file_v1_favorite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteResponse) ProtoMessage() {}

func (x *IsFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_favorite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteResponse.ProtoReflect.Descriptor instead.
func (*IsFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_v1_favorite_proto_rawDescGZIP(), []int{12}
}

func (x *IsFavoriteResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IsFavoriteResponse) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *IsFavoriteResponse) GetResult() []*IsFavoriteResponseItem {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_v1_favorite_proto protoreflect.FileDescriptor

const file_v1_favorite_proto_rawDesc = "" +
	"\n" +
	"\x11v1/favorite.proto\x12\x1cshortVideoCoreService.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\rv1/base.proto\"\xc3\x01\n" +
	"\x12AddFavoriteRequest\x12D\n" +
	"\x06target\x18\x01 \x01(\x0e2,.shortVideoCoreService.api.v1.FavoriteTargetR\x06target\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2*.shortVideoCoreService.api.v1.FavoriteTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"Q\n" +
	"\x13AddFavoriteResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"\xc6\x01\n" +
	"\x15RemoveFavoriteRequest\x12D\n" +
	"\x06target\x18\x01 \x01(\x0e2,.shortVideoCoreService.api.v1.FavoriteTargetR\x06target\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2*.shortVideoCoreService.api.v1.FavoriteTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"T\n" +
	"\x16RemoveFavoriteResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"\xa3\x02\n" +
	"\x13ListFavoriteRequest\x12Z\n" +
	"\x0eaggregate_type\x18\x01 \x01(\x0e23.shortVideoCoreService.api.v1.FavoriteAggregateTypeR\raggregateType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12O\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2/.shortVideoCoreService.api.v1.PaginationRequestR\n" +
	"pagination\x12O\n" +
	"\rfavorite_type\x18\x04 \x01(\x0e2*.shortVideoCoreService.api.v1.FavoriteTypeR\ffavoriteType\"\xbb\x01\n" +
	"\x14ListFavoriteResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12\x15\n" +
	"\x06biz_id\x18\x02 \x03(\x03R\x05bizId\x12P\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v20.shortVideoCoreService.api.v1.PaginationResponseR\n" +
	"pagination\"\xd3\x01\n" +
	"\x14CountFavoriteRequest\x12Z\n" +
	"\x0eaggregate_type\x18\x01 \x01(\x0e23.shortVideoCoreService.api.v1.FavoriteAggregateTypeR\raggregateType\x12\x0e\n" +
	"\x02id\x18\x02 \x03(\x03R\x02id\x12O\n" +
	"\rfavorite_type\x18\x04 \x01(\x0e2*.shortVideoCoreService.api.v1.FavoriteTypeR\ffavoriteType\"H\n" +
	"\x19CountFavoriteResponseItem\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x03R\x05bizId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xa2\x01\n" +
	"\x15CountFavoriteResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12M\n" +
	"\x05items\x18\x02 \x03(\v27.shortVideoCoreService.api.v1.CountFavoriteResponseItemR\x05items\"G\n" +
	"\x15IsFavoriteRequestItem\x12\x15\n" +
	"\x06biz_id\x18\x03 \x01(\x03R\x05bizId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"\x94\x02\n" +
	"\x11IsFavoriteRequest\x12D\n" +
	"\x06target\x18\x01 \x01(\x0e2,.shortVideoCoreService.api.v1.FavoriteTargetR\x06target\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2*.shortVideoCoreService.api.v1.FavoriteTypeR\x04type\x12\x15\n" +
	"\x06biz_id\x18\x03 \x01(\x03R\x05bizId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12I\n" +
	"\x05items\x18\x05 \x03(\v23.shortVideoCoreService.api.v1.IsFavoriteRequestItemR\x05items\"i\n" +
	"\x16IsFavoriteResponseItem\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x03R\x05bizId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vis_favorite\x18\x03 \x01(\bR\n" +
	"isFavorite\"\xbf\x01\n" +
	"\x12IsFavoriteResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12\x1f\n" +
	"\vis_favorite\x18\x02 \x01(\bR\n" +
	"isFavorite\x12L\n" +
	"\x06result\x18\x03 \x03(\v24.shortVideoCoreService.api.v1.IsFavoriteResponseItemR\x06result*(\n" +
	"\x0eFavoriteTarget\x12\t\n" +
	"\x05VIDEO\x10\x00\x12\v\n" +
	"\aCOMMENT\x10\x01*(\n" +
	"\fFavoriteType\x12\f\n" +
	"\bFAVORITE\x10\x00\x12\n" +
	"\n" +
	"\x06UNLIKE\x10\x01*B\n" +
	"\x15FavoriteAggregateType\x12\f\n" +
	"\bBY_VIDEO\x10\x00\x12\x0e\n" +
	"\n" +
	"BY_COMMENT\x10\x01\x12\v\n" +
	"\aBY_USER\x10\x022\xe4\x04\n" +
	"\x0fFavoriteService\x12r\n" +
	"\vAddFavorite\x120.shortVideoCoreService.api.v1.AddFavoriteRequest\x1a1.shortVideoCoreService.api.v1.AddFavoriteResponse\x12{\n" +
	"\x0eRemoveFavorite\x123.shortVideoCoreService.api.v1.RemoveFavoriteRequest\x1a4.shortVideoCoreService.api.v1.RemoveFavoriteResponse\x12u\n" +
	"\fListFavorite\x121.shortVideoCoreService.api.v1.ListFavoriteRequest\x1a2.shortVideoCoreService.api.v1.ListFavoriteResponse\x12x\n" +
	"\rCountFavorite\x122.shortVideoCoreService.api.v1.CountFavoriteRequest\x1a3.shortVideoCoreService.api.v1.CountFavoriteResponse\x12o\n" +
	"\n" +
	"IsFavorite\x12/.shortVideoCoreService.api.v1.IsFavoriteRequest\x1a0.shortVideoCoreService.api.v1.IsFavoriteResponseBGZEgithub.com/cloudzenith/DouTok/backend/shortVideoCoreService/api/v1;v1b\x06proto3"

var (
	file_v1_favorite_proto_rawDescOnce sync.Once
	file_v1_favorite_proto_rawDescData []byte
)

func file_v1_favorite_proto_rawDescGZIP() []byte {
	file_v1_favorite_proto_rawDescOnce.Do(func() {
		file_v1_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_favorite_proto_rawDesc), len(file_v1_favorite_proto_rawDesc)))
	})
	return file_v1_favorite_proto_rawDescData
}

var file_v1_favorite_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_favorite_proto_goTypes = []any{
	(FavoriteTarget)(0),               // 0: shortVideoCoreService.api.v1.FavoriteTarget
	(FavoriteType)(0),                 // 1: shortVideoCoreService.api.v1.FavoriteType
	(FavoriteAggregateType)(0),        // 2: shortVideoCoreService.api.v1.FavoriteAggregateType
	(*AddFavoriteRequest)(nil),        // 3: shortVideoCoreService.api.v1.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),       // 4: shortVideoCoreService.api.v1.AddFavoriteResponse
	(*RemoveFavoriteRequest)(nil),     // 5: shortVideoCoreService.api.v1.RemoveFavoriteRequest
	(*RemoveFavoriteResponse)(nil),    // 6: shortVideoCoreService.api.v1.RemoveFavoriteResponse
	(*ListFavoriteRequest)(nil),       // 7: shortVideoCoreService.api.v1.ListFavoriteRequest
	(*ListFavoriteResponse)(nil),      // 8: shortVideoCoreService.api.v1.ListFavoriteResponse
	(*CountFavoriteRequest)(nil),      // 9: shortVideoCoreService.api.v1.CountFavoriteRequest
	(*CountFavoriteResponseItem)(nil), // 10: shortVideoCoreService.api.v1.CountFavoriteResponseItem
	(*CountFavoriteResponse)(nil),     // 11: shortVideoCoreService.api.v1.CountFavoriteResponse
	(*IsFavoriteRequestItem)(nil),     // 12: shortVideoCoreService.api.v1.IsFavoriteRequestItem
	(*IsFavoriteRequest)(nil),         // 13: shortVideoCoreService.api.v1.IsFavoriteRequest
	(*IsFavoriteResponseItem)(nil),    // 14: shortVideoCoreService.api.v1.IsFavoriteResponseItem
	(*IsFavoriteResponse)(nil),        // 15: shortVideoCoreService.api.v1.IsFavoriteResponse
	(*Metadata)(nil),                  // 16: shortVideoCoreService.api.v1.Metadata
	(*PaginationRequest)(nil),         // 17: shortVideoCoreService.api.v1.PaginationRequest
	(*PaginationResponse)(nil),        // 18: shortVideoCoreService.api.v1.PaginationResponse
}
var file_v1_favorite_proto_depIdxs = []int32{
	0,  // 0: shortVideoCoreService.api.v1.AddFavoriteRequest.target:type_name -> shortVideoCoreService.api.v1.FavoriteTarget
	1,  // 1: shortVideoCoreService.api.v1.AddFavoriteRequest.type:type_name -> shortVideoCoreService.api.v1.FavoriteType
	16, // 2: shortVideoCoreService.api.v1.AddFavoriteResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	0,  // 3: shortVideoCoreService.api.v1.RemoveFavoriteRequest.target:type_name -> shortVideoCoreService.api.v1.FavoriteTarget
	1,  // 4: shortVideoCoreService.api.v1.RemoveFavoriteRequest.type:type_name -> shortVideoCoreService.api.v1.FavoriteType
	16, // 5: shortVideoCoreService.api.v1.RemoveFavoriteResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	2,  // 6: shortVideoCoreService.api.v1.ListFavoriteRequest.aggregate_type:type_name -> shortVideoCoreService.api.v1.FavoriteAggregateType
	17, // 7: shortVideoCoreService.api.v1.ListFavoriteRequest.pagination:type_name -> shortVideoCoreService.api.v1.PaginationRequest
	1,  // 8: shortVideoCoreService.api.v1.ListFavoriteRequest.favorite_type:type_name -> shortVideoCoreService.api.v1.FavoriteType
	16, // 9: shortVideoCoreService.api.v1.ListFavoriteResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	18, // 10: shortVideoCoreService.api.v1.ListFavoriteResponse.pagination:type_name -> shortVideoCoreService.api.v1.PaginationResponse
	2,  // 11: shortVideoCoreService.api.v1.CountFavoriteRequest.aggregate_type:type_name -> shortVideoCoreService.api.v1.FavoriteAggregateType
	1,  // 12: shortVideoCoreService.api.v1.CountFavoriteRequest.favorite_type:type_name -> shortVideoCoreService.api.v1.FavoriteType
	16, // 13: shortVideoCoreService.api.v1.CountFavoriteResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	10, // 14: shortVideoCoreService.api.v1.CountFavoriteResponse.items:type_name -> shortVideoCoreService.api.v1.CountFavoriteResponseItem
	0,  // 15: shortVideoCoreService.api.v1.IsFavoriteRequest.target:type_name -> shortVideoCoreService.api.v1.FavoriteTarget
	1,  // 16: shortVideoCoreService.api.v1.IsFavoriteRequest.type:type_name -> shortVideoCoreService.api.v1.FavoriteType
	12, // 17: shortVideoCoreService.api.v1.IsFavoriteRequest.items:type_name -> shortVideoCoreService.api.v1.IsFavoriteRequestItem
	16, // 18: shortVideoCoreService.api.v1.IsFavoriteResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	14, // 19: shortVideoCoreService.api.v1.IsFavoriteResponse.result:type_name -> shortVideoCoreService.api.v1.IsFavoriteResponseItem
	3,  // 20: shortVideoCoreService.api.v1.FavoriteService.AddFavorite:input_type -> shortVideoCoreService.api.v1.AddFavoriteRequest
	5,  // 21: shortVideoCoreService.api.v1.FavoriteService.RemoveFavorite:input_type -> shortVideoCoreService.api.v1.RemoveFavoriteRequest
	7,  // 22: shortVideoCoreService.api.v1.FavoriteService.ListFavorite:input_type -> shortVideoCoreService.api.v1.ListFavoriteRequest
	9,  // 23: shortVideoCoreService.api.v1.FavoriteService.CountFavorite:input_type -> shortVideoCoreService.api.v1.CountFavoriteRequest
	13, // 24: shortVideoCoreService.api.v1.FavoriteService.IsFavorite:input_type -> shortVideoCoreService.api.v1.IsFavoriteRequest
	4,  // 25: shortVideoCoreService.api.v1.FavoriteService.AddFavorite:output_type -> shortVideoCoreService.api.v1.AddFavoriteResponse
	6,  // 26: shortVideoCoreService.api.v1.FavoriteService.RemoveFavorite:output_type -> shortVideoCoreService.api.v1.RemoveFavoriteResponse
	8,  // 27: shortVideoCoreService.api.v1.FavoriteService.ListFavorite:output_type -> shortVideoCoreService.api.v1.ListFavoriteResponse
	11, // 28: shortVideoCoreService.api.v1.FavoriteService.CountFavorite:output_type -> shortVideoCoreService.api.v1.CountFavoriteResponse
	15, // 29: shortVideoCoreService.api.v1.FavoriteService.IsFavorite:output_type -> shortVideoCoreService.api.v1.IsFavoriteResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_favorite_proto_init() }
func file_v1_favorite_proto_init() {
	if File_v1_favorite_proto != nil {
		return
	}
	file_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_favorite_proto_rawDesc), len(file_v1_favorite_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_favorite_proto_goTypes,
		DependencyIndexes: file_v1_favorite_proto_depIdxs,
		EnumInfos:         file_v1_favorite_proto_enumTypes,
		MessageInfos:      file_v1_favorite_proto_msgTypes,
	}.Build()
	File_v1_favorite_proto = out.File
	file_v1_favorite_proto_goTypes = nil
	file_v1_favorite_proto_depIdxs = nil
}
