// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/follow.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowType int32

const (
	FollowType_FOLLOWING FollowType = 0
	FollowType_FOLLOWER  FollowType = 1
	FollowType_BOTH      FollowType = 2
)

// Enum value maps for FollowType.
var (
	FollowType_name = map[int32]string{
		0: "FOLLOWING",
		1: "FOLLOWER",
		2: "BOTH",
	}
	FollowType_value = map[string]int32{
		"FOLLOWING": 0,
		"FOLLOWER":  1,
		"BOTH":      2,
	}
)

func (x FollowType) Enum() *FollowType {
	p := new(FollowType)
	*p = x
	return p
}

func (x FollowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FollowType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_follow_proto_enumTypes[0].Descriptor()
}

func (FollowType) Type() protoreflect.EnumType {
	return &file_v1_follow_proto_enumTypes[0]
}

func (x FollowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FollowType.Descriptor instead.
func (FollowType) EnumDescriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{0}
}

type AddFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFollowRequest) Reset() {
	*x = AddFollowRequest{}
	mi := &file_v1_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFollowRequest) ProtoMessage() {}

func (x *AddFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFollowRequest.ProtoReflect.Descriptor instead.
func (*AddFollowRequest) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{0}
}

func (x *AddFollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddFollowRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type AddFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFollowResponse) Reset() {
	*x = AddFollowResponse{}
	mi := &file_v1_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFollowResponse) ProtoMessage() {}

func (x *AddFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFollowResponse.ProtoReflect.Descriptor instead.
func (*AddFollowResponse) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{1}
}

func (x *AddFollowResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RemoveFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFollowRequest) Reset() {
	*x = RemoveFollowRequest{}
	mi := &file_v1_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFollowRequest) ProtoMessage() {}

func (x *RemoveFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFollowRequest.ProtoReflect.Descriptor instead.
func (*RemoveFollowRequest) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFollowRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type RemoveFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFollowResponse) Reset() {
	*x = RemoveFollowResponse{}
	mi := &file_v1_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFollowResponse) ProtoMessage() {}

func (x *RemoveFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFollowResponse.ProtoReflect.Descriptor instead.
func (*RemoveFollowResponse) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFollowResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowType    FollowType             `protobuf:"varint,2,opt,name=follow_type,json=followType,proto3,enum=shortVideoCoreService.api.v1.FollowType" json:"follow_type,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingRequest) Reset() {
	*x = ListFollowingRequest{}
	mi := &file_v1_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingRequest) ProtoMessage() {}

func (x *ListFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingRequest) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{4}
}

func (x *ListFollowingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFollowingRequest) GetFollowType() FollowType {
	if x != nil {
		return x.FollowType
	}
	return FollowType_FOLLOWING
}

func (x *ListFollowingRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	UserIdList    []int64                `protobuf:"varint,2,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingResponse) Reset() {
	*x = ListFollowingResponse{}
	mi := &file_v1_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingResponse) ProtoMessage() {}

func (x *ListFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingResponse.ProtoReflect.Descriptor instead.
func (*ListFollowingResponse) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{5}
}

func (x *ListFollowingResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListFollowingResponse) GetUserIdList() []int64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

func (x *ListFollowingResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type IsFollowingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserIdList []int64                `protobuf:"varint,2,rep,packed,name=target_user_id_list,json=targetUserIdList,proto3" json:"target_user_id_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_v1_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{6}
}

func (x *IsFollowingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsFollowingRequest) GetTargetUserIdList() []int64 {
	if x != nil {
		return x.TargetUserIdList
	}
	return nil
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	FollowingList []int64                `protobuf:"varint,2,rep,packed,name=following_list,json=followingList,proto3" json:"following_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_v1_follow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{7}
}

func (x *IsFollowingResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IsFollowingResponse) GetFollowingList() []int64 {
	if x != nil {
		return x.FollowingList
	}
	return nil
}

type CountFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountFollowRequest) Reset() {
	*x = CountFollowRequest{}
	mi := &file_v1_follow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountFollowRequest) ProtoMessage() {}

func (x *CountFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountFollowRequest.ProtoReflect.Descriptor instead.
func (*CountFollowRequest) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{8}
}

func (x *CountFollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CountFollowResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meta           *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	FollowingCount int64                  `protobuf:"varint,2,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowerCount  int64                  `protobuf:"varint,3,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CountFollowResponse) Reset() {
	*x = CountFollowResponse{}
	mi := &file_v1_follow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountFollowResponse) ProtoMessage() {}

func (x *CountFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountFollowResponse.ProtoReflect.Descriptor instead.
func (*CountFollowResponse) Descriptor() ([]byte, []int) {
	return file_v1_follow_proto_rawDescGZIP(), []int{9}
}

func (x *CountFollowResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CountFollowResponse) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *CountFollowResponse) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

var File_v1_follow_proto protoreflect.FileDescriptor

const file_v1_follow_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/follow.proto\x12\x1cshortVideoCoreService.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\rv1/base.proto\"Q\n" +
	"\x10AddFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"O\n" +
	"\x11AddFollowResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"T\n" +
	"\x13RemoveFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"R\n" +
	"\x14RemoveFollowResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"\xcb\x01\n" +
	"\x14ListFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12I\n" +
	"\vfollow_type\x18\x02 \x01(\x0e2(.shortVideoCoreService.api.v1.FollowTypeR\n" +
	"followType\x12O\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2/.shortVideoCoreService.api.v1.PaginationRequestR\n" +
	"pagination\"\xc7\x01\n" +
	"\x15ListFollowingResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12 \n" +
	"\fuser_id_list\x18\x02 \x03(\x03R\n" +
	"userIdList\x12P\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v20.shortVideoCoreService.api.v1.PaginationResponseR\n" +
	"pagination\"\\\n" +
	"\x12IsFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12-\n" +
	"\x13target_user_id_list\x18\x02 \x03(\x03R\x10targetUserIdList\"x\n" +
	"\x13IsFollowingResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12%\n" +
	"\x0efollowing_list\x18\x02 \x03(\x03R\rfollowingList\"-\n" +
	"\x12CountFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xa1\x01\n" +
	"\x13CountFollowResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12'\n" +
	"\x0ffollowing_count\x18\x02 \x01(\x03R\x0efollowingCount\x12%\n" +
	"\x0efollower_count\x18\x03 \x01(\x03R\rfollowerCount*3\n" +
	"\n" +
	"FollowType\x12\r\n" +
	"\tFOLLOWING\x10\x00\x12\f\n" +
	"\bFOLLOWER\x10\x01\x12\b\n" +
	"\x04BOTH\x10\x022\xd6\x04\n" +
	"\rFollowService\x12l\n" +
	"\tAddFollow\x12..shortVideoCoreService.api.v1.AddFollowRequest\x1a/.shortVideoCoreService.api.v1.AddFollowResponse\x12u\n" +
	"\fRemoveFollow\x121.shortVideoCoreService.api.v1.RemoveFollowRequest\x1a2.shortVideoCoreService.api.v1.RemoveFollowResponse\x12x\n" +
	"\rListFollowing\x122.shortVideoCoreService.api.v1.ListFollowingRequest\x1a3.shortVideoCoreService.api.v1.ListFollowingResponse\x12r\n" +
	"\vIsFollowing\x120.shortVideoCoreService.api.v1.IsFollowingRequest\x1a1.shortVideoCoreService.api.v1.IsFollowingResponse\x12r\n" +
	"\vCountFollow\x120.shortVideoCoreService.api.v1.CountFollowRequest\x1a1.shortVideoCoreService.api.v1.CountFollowResponseBGZEgithub.com/cloudzenith/DouTok/backend/shortVideoCoreService/api/v1;v1b\x06proto3"

var (
	file_v1_follow_proto_rawDescOnce sync.Once
	file_v1_follow_proto_rawDescData []byte
)

func file_v1_follow_proto_rawDescGZIP() []byte {
	file_v1_follow_proto_rawDescOnce.Do(func() {
		file_v1_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_follow_proto_rawDesc), len(file_v1_follow_proto_rawDesc)))
	})
	return file_v1_follow_proto_rawDescData
}

var file_v1_follow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_follow_proto_goTypes = []any{
	(FollowType)(0),               // 0: shortVideoCoreService.api.v1.FollowType
	(*AddFollowRequest)(nil),      // 1: shortVideoCoreService.api.v1.AddFollowRequest
	(*AddFollowResponse)(nil),     // 2: shortVideoCoreService.api.v1.AddFollowResponse
	(*RemoveFollowRequest)(nil),   // 3: shortVideoCoreService.api.v1.RemoveFollowRequest
	(*RemoveFollowResponse)(nil),  // 4: shortVideoCoreService.api.v1.RemoveFollowResponse
	(*ListFollowingRequest)(nil),  // 5: shortVideoCoreService.api.v1.ListFollowingRequest
	(*ListFollowingResponse)(nil), // 6: shortVideoCoreService.api.v1.ListFollowingResponse
	(*IsFollowingRequest)(nil),    // 7: shortVideoCoreService.api.v1.IsFollowingRequest
	(*IsFollowingResponse)(nil),   // 8: shortVideoCoreService.api.v1.IsFollowingResponse
	(*CountFollowRequest)(nil),    // 9: shortVideoCoreService.api.v1.CountFollowRequest
	(*CountFollowResponse)(nil),   // 10: shortVideoCoreService.api.v1.CountFollowResponse
	(*Metadata)(nil),              // 11: shortVideoCoreService.api.v1.Metadata
	(*PaginationRequest)(nil),     // 12: shortVideoCoreService.api.v1.PaginationRequest
	(*PaginationResponse)(nil),    // 13: shortVideoCoreService.api.v1.PaginationResponse
}
var file_v1_follow_proto_depIdxs = []int32{
	11, // 0: shortVideoCoreService.api.v1.AddFollowResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	11, // 1: shortVideoCoreService.api.v1.RemoveFollowResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	0,  // 2: shortVideoCoreService.api.v1.ListFollowingRequest.follow_type:type_name -> shortVideoCoreService.api.v1.FollowType
	12, // 3: shortVideoCoreService.api.v1.ListFollowingRequest.pagination:type_name -> shortVideoCoreService.api.v1.PaginationRequest
	11, // 4: shortVideoCoreService.api.v1.ListFollowingResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	13, // 5: shortVideoCoreService.api.v1.ListFollowingResponse.pagination:type_name -> shortVideoCoreService.api.v1.PaginationResponse
	11, // 6: shortVideoCoreService.api.v1.IsFollowingResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	11, // 7: shortVideoCoreService.api.v1.CountFollowResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 8: shortVideoCoreService.api.v1.FollowService.AddFollow:input_type -> shortVideoCoreService.api.v1.AddFollowRequest
	3,  // 9: shortVideoCoreService.api.v1.FollowService.RemoveFollow:input_type -> shortVideoCoreService.api.v1.RemoveFollowRequest
	5,  // 10: shortVideoCoreService.api.v1.FollowService.ListFollowing:input_type -> shortVideoCoreService.api.v1.ListFollowingRequest
	7,  // 11: shortVideoCoreService.api.v1.FollowService.IsFollowing:input_type -> shortVideoCoreService.api.v1.IsFollowingRequest
	9,  // 12: shortVideoCoreService.api.v1.FollowService.CountFollow:input_type -> shortVideoCoreService.api.v1.CountFollowRequest
	2,  // 13: shortVideoCoreService.api.v1.FollowService.AddFollow:output_type -> shortVideoCoreService.api.v1.AddFollowResponse
	4,  // 14: shortVideoCoreService.api.v1.FollowService.RemoveFollow:output_type -> shortVideoCoreService.api.v1.RemoveFollowResponse
	6,  // 15: shortVideoCoreService.api.v1.FollowService.ListFollowing:output_type -> shortVideoCoreService.api.v1.ListFollowingResponse
	8,  // 16: shortVideoCoreService.api.v1.FollowService.IsFollowing:output_type -> shortVideoCoreService.api.v1.IsFollowingResponse
	10, // 17: shortVideoCoreService.api.v1.FollowService.CountFollow:output_type -> shortVideoCoreService.api.v1.CountFollowResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_follow_proto_init() }
func file_v1_follow_proto_init() {
	if File_v1_follow_proto != nil {
		return
	}
	file_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_follow_proto_rawDesc), len(file_v1_follow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_follow_proto_goTypes,
		DependencyIndexes: file_v1_follow_proto_depIdxs,
		EnumInfos:         file_v1_follow_proto_enumTypes,
		MessageInfos:      file_v1_follow_proto_msgTypes,
	}.Build()
	File_v1_follow_proto = out.File
	file_v1_follow_proto_goTypes = nil
	file_v1_follow_proto_depIdxs = nil
}
