// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/user.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserImageType int32

const (
	UpdateUserImageType_AVATAR           UpdateUserImageType = 0
	UpdateUserImageType_BACKGROUND_IMAGE UpdateUserImageType = 1
)

// Enum value maps for UpdateUserImageType.
var (
	UpdateUserImageType_name = map[int32]string{
		0: "AVATAR",
		1: "BACKGROUND_IMAGE",
	}
	UpdateUserImageType_value = map[string]int32{
		"AVATAR":           0,
		"BACKGROUND_IMAGE": 1,
	}
)

func (x UpdateUserImageType) Enum() *UpdateUserImageType {
	p := new(UpdateUserImageType)
	*p = x
	return p
}

func (x UpdateUserImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateUserImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_user_proto_enumTypes[0].Descriptor()
}

func (UpdateUserImageType) Type() protoreflect.EnumType {
	return &file_v1_user_proto_enumTypes[0]
}

func (x UpdateUserImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateUserImageType.Descriptor instead.
func (UpdateUserImageType) EnumDescriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // 用户id
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // 用户名称
	Avatar          string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                          // 用户头像Url
	BackgroundImage string                 `protobuf:"bytes,4,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"` // 用户个人页顶部大图
	Signature       string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                    // 个人简介
	Mobile          string                 `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`                                          // 手机号
	Email           string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                            // 邮箱
	FollowCount     int64                  `protobuf:"varint,8,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`            // 关注总数
	FollowerCount   int64                  `protobuf:"varint,9,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`      // 粉丝总数
	TotalFavorited  int64                  `protobuf:"varint,10,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`  // 获赞数量
	WorkCount       int64                  `protobuf:"varint,11,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`                 // 作品数量
	FavoriteCount   int64                  `protobuf:"varint,12,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`     // 点赞数量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetTotalFavorited() int64 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *User) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *User) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetUserInfoResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundImage string                 `protobuf:"bytes,4,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"`
	Signature       string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type UpdateUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetUserByIdListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdList    []int64                `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdListRequest) Reset() {
	*x = GetUserByIdListRequest{}
	mi := &file_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdListRequest) ProtoMessage() {}

func (x *GetUserByIdListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdListRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdListRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByIdListRequest) GetUserIdList() []int64 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type GetUserByIdListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*User                `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdListResponse) Reset() {
	*x = GetUserByIdListResponse{}
	mi := &file_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdListResponse) ProtoMessage() {}

func (x *GetUserByIdListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdListResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdListResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserByIdListResponse) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *GetUserByIdListResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SearchUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`           // 搜索关键词
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserRequest) Reset() {
	*x = SearchUserRequest{}
	mi := &file_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserRequest) ProtoMessage() {}

func (x *SearchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserRequest.ProtoReflect.Descriptor instead.
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUserRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUserRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*User                `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResponse) Reset() {
	*x = SearchUserResponse{}
	mi := &file_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResponse) ProtoMessage() {}

func (x *SearchUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResponse.ProtoReflect.Descriptor instead.
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUserResponse) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *SearchUserResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchUserResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_v1_user_proto protoreflect.FileDescriptor

const file_v1_user_proto_rawDesc = "" +
	"\n" +
	"\rv1/user.proto\x12\x1cshortVideoCoreService.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\rv1/base.proto\"\xf2\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\x04 \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12!\n" +
	"\ffollow_count\x18\b \x01(\x03R\vfollowCount\x12%\n" +
	"\x0efollower_count\x18\t \x01(\x03R\rfollowerCount\x12'\n" +
	"\x0ftotal_favorited\x18\n" +
	" \x01(\x03R\x0etotalFavorited\x12\x1d\n" +
	"\n" +
	"work_count\x18\v \x01(\x03R\tworkCount\x12%\n" +
	"\x0efavorite_count\x18\f \x01(\x03R\rfavoriteCount\"i\n" +
	"\x11CreateUserRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12&\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\taccountId\"i\n" +
	"\x12CreateUserResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"L\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"\x89\x01\n" +
	"\x13GetUserInfoResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x126\n" +
	"\x04user\x18\x02 \x01(\v2\".shortVideoCoreService.api.v1.UserR\x04user\"\xae\x01\n" +
	"\x15UpdateUserInfoRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\x04 \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"T\n" +
	"\x16UpdateUserInfoResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\":\n" +
	"\x16GetUserByIdListRequest\x12 \n" +
	"\fuser_id_list\x18\x01 \x03(\x03R\n" +
	"userIdList\"\x96\x01\n" +
	"\x17GetUserByIdListResponse\x12?\n" +
	"\tuser_list\x18\x01 \x03(\v2\".shortVideoCoreService.api.v1.UserR\buserList\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\"\x83\x01\n" +
	"\x11SearchUserRequest\x12\x1d\n" +
	"\x05query\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05query\x12O\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2/.shortVideoCoreService.api.v1.PaginationRequestR\n" +
	"pagination\"\xe3\x01\n" +
	"\x12SearchUserResponse\x12?\n" +
	"\tuser_list\x18\x01 \x03(\v2\".shortVideoCoreService.api.v1.UserR\buserList\x12P\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v20.shortVideoCoreService.api.v1.PaginationResponseR\n" +
	"pagination\x12:\n" +
	"\x04meta\x18\x03 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta*7\n" +
	"\x13UpdateUserImageType\x12\n" +
	"\n" +
	"\x06AVATAR\x10\x00\x12\x14\n" +
	"\x10BACKGROUND_IMAGE\x10\x012\xc4\x05\n" +
	"\vUserService\x12\x84\x01\n" +
	"\n" +
	"CreateUser\x12/.shortVideoCoreService.api.v1.CreateUserRequest\x1a0.shortVideoCoreService.api.v1.CreateUserResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/user\x12\x89\x01\n" +
	"\vGetUserInfo\x120.shortVideoCoreService.api.v1.GetUserInfoRequest\x1a1.shortVideoCoreService.api.v1.GetUserInfoResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/info\x12\x90\x01\n" +
	"\x0eUpdateUserInfo\x123.shortVideoCoreService.api.v1.UpdateUserInfoRequest\x1a4.shortVideoCoreService.api.v1.UpdateUserInfoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\x1a\b/v1/user\x12\x80\x01\n" +
	"\x0fGetUserByIdList\x124.shortVideoCoreService.api.v1.GetUserByIdListRequest\x1a5.shortVideoCoreService.api.v1.GetUserByIdListResponse\"\x00\x12\x8b\x01\n" +
	"\n" +
	"SearchUser\x12/.shortVideoCoreService.api.v1.SearchUserRequest\x1a0.shortVideoCoreService.api.v1.SearchUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/searchBGZEgithub.com/cloudzenith/DouTok/backend/shortVideoCoreService/api/v1;v1b\x06proto3"

var (
	file_v1_user_proto_rawDescOnce sync.Once
	file_v1_user_proto_rawDescData []byte
)

func file_v1_user_proto_rawDescGZIP() []byte {
	file_v1_user_proto_rawDescOnce.Do(func() {
		file_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)))
	})
	return file_v1_user_proto_rawDescData
}

var file_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_user_proto_goTypes = []any{
	(UpdateUserImageType)(0),        // 0: shortVideoCoreService.api.v1.UpdateUserImageType
	(*User)(nil),                    // 1: shortVideoCoreService.api.v1.User
	(*CreateUserRequest)(nil),       // 2: shortVideoCoreService.api.v1.CreateUserRequest
	(*CreateUserResponse)(nil),      // 3: shortVideoCoreService.api.v1.CreateUserResponse
	(*GetUserInfoRequest)(nil),      // 4: shortVideoCoreService.api.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),     // 5: shortVideoCoreService.api.v1.GetUserInfoResponse
	(*UpdateUserInfoRequest)(nil),   // 6: shortVideoCoreService.api.v1.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil),  // 7: shortVideoCoreService.api.v1.UpdateUserInfoResponse
	(*GetUserByIdListRequest)(nil),  // 8: shortVideoCoreService.api.v1.GetUserByIdListRequest
	(*GetUserByIdListResponse)(nil), // 9: shortVideoCoreService.api.v1.GetUserByIdListResponse
	(*SearchUserRequest)(nil),       // 10: shortVideoCoreService.api.v1.SearchUserRequest
	(*SearchUserResponse)(nil),      // 11: shortVideoCoreService.api.v1.SearchUserResponse
	(*Metadata)(nil),                // 12: shortVideoCoreService.api.v1.Metadata
	(*PaginationRequest)(nil),       // 13: shortVideoCoreService.api.v1.PaginationRequest
	(*PaginationResponse)(nil),      // 14: shortVideoCoreService.api.v1.PaginationResponse
}
var file_v1_user_proto_depIdxs = []int32{
	12, // 0: shortVideoCoreService.api.v1.CreateUserResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	12, // 1: shortVideoCoreService.api.v1.GetUserInfoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 2: shortVideoCoreService.api.v1.GetUserInfoResponse.user:type_name -> shortVideoCoreService.api.v1.User
	12, // 3: shortVideoCoreService.api.v1.UpdateUserInfoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 4: shortVideoCoreService.api.v1.GetUserByIdListResponse.user_list:type_name -> shortVideoCoreService.api.v1.User
	12, // 5: shortVideoCoreService.api.v1.GetUserByIdListResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	13, // 6: shortVideoCoreService.api.v1.SearchUserRequest.pagination:type_name -> shortVideoCoreService.api.v1.PaginationRequest
	1,  // 7: shortVideoCoreService.api.v1.SearchUserResponse.user_list:type_name -> shortVideoCoreService.api.v1.User
	14, // 8: shortVideoCoreService.api.v1.SearchUserResponse.pagination:type_name -> shortVideoCoreService.api.v1.PaginationResponse
	12, // 9: shortVideoCoreService.api.v1.SearchUserResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	2,  // 10: shortVideoCoreService.api.v1.UserService.CreateUser:input_type -> shortVideoCoreService.api.v1.CreateUserRequest
	4,  // 11: shortVideoCoreService.api.v1.UserService.GetUserInfo:input_type -> shortVideoCoreService.api.v1.GetUserInfoRequest
	6,  // 12: shortVideoCoreService.api.v1.UserService.UpdateUserInfo:input_type -> shortVideoCoreService.api.v1.UpdateUserInfoRequest
	8,  // 13: shortVideoCoreService.api.v1.UserService.GetUserByIdList:input_type -> shortVideoCoreService.api.v1.GetUserByIdListRequest
	10, // 14: shortVideoCoreService.api.v1.UserService.SearchUser:input_type -> shortVideoCoreService.api.v1.SearchUserRequest
	3,  // 15: shortVideoCoreService.api.v1.UserService.CreateUser:output_type -> shortVideoCoreService.api.v1.CreateUserResponse
	5,  // 16: shortVideoCoreService.api.v1.UserService.GetUserInfo:output_type -> shortVideoCoreService.api.v1.GetUserInfoResponse
	7,  // 17: shortVideoCoreService.api.v1.UserService.UpdateUserInfo:output_type -> shortVideoCoreService.api.v1.UpdateUserInfoResponse
	9,  // 18: shortVideoCoreService.api.v1.UserService.GetUserByIdList:output_type -> shortVideoCoreService.api.v1.GetUserByIdListResponse
	11, // 19: shortVideoCoreService.api.v1.UserService.SearchUser:output_type -> shortVideoCoreService.api.v1.SearchUserResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_user_proto_init() }
func file_v1_user_proto_init() {
	if File_v1_user_proto != nil {
		return
	}
	file_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_proto_goTypes,
		DependencyIndexes: file_v1_user_proto_depIdxs,
		EnumInfos:         file_v1_user_proto_enumTypes,
		MessageInfos:      file_v1_user_proto_msgTypes,
	}.Build()
	File_v1_user_proto = out.File
	file_v1_user_proto_goTypes = nil
	file_v1_user_proto_depIdxs = nil
}
