// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/video.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 作者唯一标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 作者昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                               // 作者头像地址
	IsFollowing   int64                  `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"` // 0-未关注，1-已关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Author) GetIsFollowing() int64 {
	if x != nil {
		return x.IsFollowing
	}
	return 0
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 视频唯一标识
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                       // 视频标题
	Author        *Author                `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`                                     // 视频作者信息
	PlayUrl       string                 `protobuf:"bytes,4,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`                    // 视频播放地址
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`                 // 视频封面地址
	FavoriteCount int64                  `protobuf:"varint,6,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"` // 视频的点赞总数
	CommentCount  int64                  `protobuf:"varint,7,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`    // 视频的评论总数
	IsFavorite    int64                  `protobuf:"varint,8,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`          // 0-未点赞，1-已点赞
	UploadTime    string                 `protobuf:"bytes,9,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"`           // 视频上传时间
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`                          // 视频描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetIsFavorite() int64 {
	if x != nil {
		return x.IsFavorite
	}
	return 0
}

func (x *Video) GetUploadTime() string {
	if x != nil {
		return x.UploadTime
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FeedShortVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestTime    int64                  `protobuf:"varint,1,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"` // 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedNum       int64                  `protobuf:"varint,3,opt,name=feed_num,json=feedNum,proto3" json:"feed_num,omitempty"` // 返回视频的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedShortVideoRequest) Reset() {
	*x = FeedShortVideoRequest{}
	mi := &file_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedShortVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedShortVideoRequest) ProtoMessage() {}

func (x *FeedShortVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedShortVideoRequest.ProtoReflect.Descriptor instead.
func (*FeedShortVideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *FeedShortVideoRequest) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *FeedShortVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FeedShortVideoRequest) GetFeedNum() int64 {
	if x != nil {
		return x.FeedNum
	}
	return 0
}

type FeedShortVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Videos        []*Video               `protobuf:"bytes,2,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedShortVideoResponse) Reset() {
	*x = FeedShortVideoResponse{}
	mi := &file_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedShortVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedShortVideoResponse) ProtoMessage() {}

func (x *FeedShortVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedShortVideoResponse.ProtoReflect.Descriptor instead.
func (*FeedShortVideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *FeedShortVideoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FeedShortVideoResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type GetVideoByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoByIdRequest) Reset() {
	*x = GetVideoByIdRequest{}
	mi := &file_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIdRequest) ProtoMessage() {}

func (x *GetVideoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetVideoByIdRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoByIdRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetVideoByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Video         *Video                 `protobuf:"bytes,2,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoByIdResponse) Reset() {
	*x = GetVideoByIdResponse{}
	mi := &file_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIdResponse) ProtoMessage() {}

func (x *GetVideoByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIdResponse.ProtoReflect.Descriptor instead.
func (*GetVideoByIdResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoByIdResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetVideoByIdResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type PublishVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                       // 视频标题
	CoverUrl      string                 `protobuf:"bytes,2,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 视频封面地址
	PlayUrl       string                 `protobuf:"bytes,3,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`    // 视频播放地址
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`           // 视频描述
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 视频作者id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoRequest) Reset() {
	*x = PublishVideoRequest{}
	mi := &file_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoRequest) ProtoMessage() {}

func (x *PublishVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoRequest.ProtoReflect.Descriptor instead.
func (*PublishVideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *PublishVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishVideoRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PublishVideoRequest) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *PublishVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PublishVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoResponse) Reset() {
	*x = PublishVideoResponse{}
	mi := &file_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoResponse) ProtoMessage() {}

func (x *PublishVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoResponse.ProtoReflect.Descriptor instead.
func (*PublishVideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *PublishVideoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PublishVideoResponse) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type ListPublishedVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LatestTime    int64                  `protobuf:"varint,2,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"` // 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishedVideoRequest) Reset() {
	*x = ListPublishedVideoRequest{}
	mi := &file_v1_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishedVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishedVideoRequest) ProtoMessage() {}

func (x *ListPublishedVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishedVideoRequest.ProtoReflect.Descriptor instead.
func (*ListPublishedVideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{8}
}

func (x *ListPublishedVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPublishedVideoRequest) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *ListPublishedVideoRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPublishedVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Videos        []*Video               `protobuf:"bytes,2,rep,name=videos,proto3" json:"videos,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishedVideoResponse) Reset() {
	*x = ListPublishedVideoResponse{}
	mi := &file_v1_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishedVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishedVideoResponse) ProtoMessage() {}

func (x *ListPublishedVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishedVideoResponse.ProtoReflect.Descriptor instead.
func (*ListPublishedVideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{9}
}

func (x *ListPublishedVideoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListPublishedVideoResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListPublishedVideoResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetVideoByIdListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIdList   []int64                `protobuf:"varint,1,rep,packed,name=video_id_list,json=videoIdList,proto3" json:"video_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoByIdListRequest) Reset() {
	*x = GetVideoByIdListRequest{}
	mi := &file_v1_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoByIdListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIdListRequest) ProtoMessage() {}

func (x *GetVideoByIdListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIdListRequest.ProtoReflect.Descriptor instead.
func (*GetVideoByIdListRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{10}
}

func (x *GetVideoByIdListRequest) GetVideoIdList() []int64 {
	if x != nil {
		return x.VideoIdList
	}
	return nil
}

type GetVideoByIdListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Videos        []*Video               `protobuf:"bytes,2,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoByIdListResponse) Reset() {
	*x = GetVideoByIdListResponse{}
	mi := &file_v1_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoByIdListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIdListResponse) ProtoMessage() {}

func (x *GetVideoByIdListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIdListResponse.ProtoReflect.Descriptor instead.
func (*GetVideoByIdListResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{11}
}

func (x *GetVideoByIdListResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetVideoByIdListResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type SearchVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // 搜索关键词
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LatestTime    int64                  `protobuf:"varint,3,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"` // 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
	SearchNum     int64                  `protobuf:"varint,4,opt,name=search_num,json=searchNum,proto3" json:"search_num,omitempty"`    // 返回视频的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoRequest) Reset() {
	*x = SearchVideoRequest{}
	mi := &file_v1_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoRequest) ProtoMessage() {}

func (x *SearchVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoRequest.ProtoReflect.Descriptor instead.
func (*SearchVideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{12}
}

func (x *SearchVideoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchVideoRequest) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *SearchVideoRequest) GetSearchNum() int64 {
	if x != nil {
		return x.SearchNum
	}
	return 0
}

type SearchVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Videos        []*Video               `protobuf:"bytes,2,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideoResponse) Reset() {
	*x = SearchVideoResponse{}
	mi := &file_v1_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideoResponse) ProtoMessage() {}

func (x *SearchVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideoResponse.ProtoReflect.Descriptor instead.
func (*SearchVideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{13}
}

func (x *SearchVideoResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SearchVideoResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_v1_video_proto protoreflect.FileDescriptor

const file_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/video.proto\x12\x1cshortVideoCoreService.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\rv1/base.proto\"g\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12!\n" +
	"\fis_following\x18\x04 \x01(\x03R\visFollowing\"\xd3\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12<\n" +
	"\x06author\x18\x03 \x01(\v2$.shortVideoCoreService.api.v1.AuthorR\x06author\x12\x19\n" +
	"\bplay_url\x18\x04 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12%\n" +
	"\x0efavorite_count\x18\x06 \x01(\x03R\rfavoriteCount\x12#\n" +
	"\rcomment_count\x18\a \x01(\x03R\fcommentCount\x12\x1f\n" +
	"\vis_favorite\x18\b \x01(\x03R\n" +
	"isFavorite\x12\x1f\n" +
	"\vupload_time\x18\t \x01(\tR\n" +
	"uploadTime\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"~\n" +
	"\x15FeedShortVideoRequest\x12\x1f\n" +
	"\vlatest_time\x18\x01 \x01(\x03R\n" +
	"latestTime\x12 \n" +
	"\auser_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\"\n" +
	"\bfeed_num\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\afeedNum\"\x91\x01\n" +
	"\x16FeedShortVideoResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12;\n" +
	"\x06videos\x18\x02 \x03(\v2#.shortVideoCoreService.api.v1.VideoR\x06videos\"9\n" +
	"\x13GetVideoByIdRequest\x12\"\n" +
	"\bvideo_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\avideoId\"\x8d\x01\n" +
	"\x14GetVideoByIdResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x129\n" +
	"\x05video\x18\x02 \x01(\v2#.shortVideoCoreService.api.v1.VideoR\x05video\"\xd4\x01\n" +
	"\x13PublishVideoRequest\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x05title\x12'\n" +
	"\tcover_url\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xf4\x03R\bcoverUrl\x12%\n" +
	"\bplay_url\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xf4\x03R\aplayUrl\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\vdescription\x12 \n" +
	"\auser_id\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\"m\n" +
	"\x14PublishVideoResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\xaf\x01\n" +
	"\x19ListPublishedVideoRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1f\n" +
	"\vlatest_time\x18\x02 \x01(\x03R\n" +
	"latestTime\x12O\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2/.shortVideoCoreService.api.v1.PaginationRequestR\n" +
	"pagination\"\xe7\x01\n" +
	"\x1aListPublishedVideoResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12;\n" +
	"\x06videos\x18\x02 \x03(\v2#.shortVideoCoreService.api.v1.VideoR\x06videos\x12P\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v20.shortVideoCoreService.api.v1.PaginationResponseR\n" +
	"pagination\"=\n" +
	"\x17GetVideoByIdListRequest\x12\"\n" +
	"\rvideo_id_list\x18\x01 \x03(\x03R\vvideoIdList\"\x93\x01\n" +
	"\x18GetVideoByIdListResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12;\n" +
	"\x06videos\x18\x02 \x03(\v2#.shortVideoCoreService.api.v1.VideoR\x06videos\"\x9e\x01\n" +
	"\x12SearchVideoRequest\x12\x1d\n" +
	"\x05query\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05query\x12 \n" +
	"\auser_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1f\n" +
	"\vlatest_time\x18\x03 \x01(\x03R\n" +
	"latestTime\x12&\n" +
	"\n" +
	"search_num\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tsearchNum\"\x8e\x01\n" +
	"\x13SearchVideoResponse\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.shortVideoCoreService.api.v1.MetadataR\x04meta\x12;\n" +
	"\x06videos\x18\x02 \x03(\v2#.shortVideoCoreService.api.v1.VideoR\x06videos2\x90\a\n" +
	"\fVideoService\x12\x96\x01\n" +
	"\x0eFeedShortVideo\x123.shortVideoCoreService.api.v1.FeedShortVideoRequest\x1a4.shortVideoCoreService.api.v1.FeedShortVideoResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/video/feed\x12\x93\x01\n" +
	"\fGetVideoById\x121.shortVideoCoreService.api.v1.GetVideoByIdRequest\x1a2.shortVideoCoreService.api.v1.GetVideoByIdResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/video/{video_id}\x12\x93\x01\n" +
	"\fPublishVideo\x121.shortVideoCoreService.api.v1.PublishVideoRequest\x1a2.shortVideoCoreService.api.v1.PublishVideoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/video/publish\x12\xa2\x01\n" +
	"\x12ListPublishedVideo\x127.shortVideoCoreService.api.v1.ListPublishedVideoRequest\x1a8.shortVideoCoreService.api.v1.ListPublishedVideoResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/video/list\x12\x83\x01\n" +
	"\x10GetVideoByIdList\x125.shortVideoCoreService.api.v1.GetVideoByIdListRequest\x1a6.shortVideoCoreService.api.v1.GetVideoByIdListResponse\"\x00\x12\x8f\x01\n" +
	"\vSearchVideo\x120.shortVideoCoreService.api.v1.SearchVideoRequest\x1a1.shortVideoCoreService.api.v1.SearchVideoResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/video/searchBGZEgithub.com/cloudzenith/DouTok/backend/shortVideoCoreService/api/v1;v1b\x06proto3"

var (
	file_v1_video_proto_rawDescOnce sync.Once
	file_v1_video_proto_rawDescData []byte
)

func file_v1_video_proto_rawDescGZIP() []byte {
	file_v1_video_proto_rawDescOnce.Do(func() {
		file_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_video_proto_rawDesc), len(file_v1_video_proto_rawDesc)))
	})
	return file_v1_video_proto_rawDescData
}

var file_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_video_proto_goTypes = []any{
	(*Author)(nil),                     // 0: shortVideoCoreService.api.v1.Author
	(*Video)(nil),                      // 1: shortVideoCoreService.api.v1.Video
	(*FeedShortVideoRequest)(nil),      // 2: shortVideoCoreService.api.v1.FeedShortVideoRequest
	(*FeedShortVideoResponse)(nil),     // 3: shortVideoCoreService.api.v1.FeedShortVideoResponse
	(*GetVideoByIdRequest)(nil),        // 4: shortVideoCoreService.api.v1.GetVideoByIdRequest
	(*GetVideoByIdResponse)(nil),       // 5: shortVideoCoreService.api.v1.GetVideoByIdResponse
	(*PublishVideoRequest)(nil),        // 6: shortVideoCoreService.api.v1.PublishVideoRequest
	(*PublishVideoResponse)(nil),       // 7: shortVideoCoreService.api.v1.PublishVideoResponse
	(*ListPublishedVideoRequest)(nil),  // 8: shortVideoCoreService.api.v1.ListPublishedVideoRequest
	(*ListPublishedVideoResponse)(nil), // 9: shortVideoCoreService.api.v1.ListPublishedVideoResponse
	(*GetVideoByIdListRequest)(nil),    // 10: shortVideoCoreService.api.v1.GetVideoByIdListRequest
	(*GetVideoByIdListResponse)(nil),   // 11: shortVideoCoreService.api.v1.GetVideoByIdListResponse
	(*SearchVideoRequest)(nil),         // 12: shortVideoCoreService.api.v1.SearchVideoRequest
	(*SearchVideoResponse)(nil),        // 13: shortVideoCoreService.api.v1.SearchVideoResponse
	(*Metadata)(nil),                   // 14: shortVideoCoreService.api.v1.Metadata
	(*PaginationRequest)(nil),          // 15: shortVideoCoreService.api.v1.PaginationRequest
	(*PaginationResponse)(nil),         // 16: shortVideoCoreService.api.v1.PaginationResponse
}
var file_v1_video_proto_depIdxs = []int32{
	0,  // 0: shortVideoCoreService.api.v1.Video.author:type_name -> shortVideoCoreService.api.v1.Author
	14, // 1: shortVideoCoreService.api.v1.FeedShortVideoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 2: shortVideoCoreService.api.v1.FeedShortVideoResponse.videos:type_name -> shortVideoCoreService.api.v1.Video
	14, // 3: shortVideoCoreService.api.v1.GetVideoByIdResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 4: shortVideoCoreService.api.v1.GetVideoByIdResponse.video:type_name -> shortVideoCoreService.api.v1.Video
	14, // 5: shortVideoCoreService.api.v1.PublishVideoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	15, // 6: shortVideoCoreService.api.v1.ListPublishedVideoRequest.pagination:type_name -> shortVideoCoreService.api.v1.PaginationRequest
	14, // 7: shortVideoCoreService.api.v1.ListPublishedVideoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 8: shortVideoCoreService.api.v1.ListPublishedVideoResponse.videos:type_name -> shortVideoCoreService.api.v1.Video
	16, // 9: shortVideoCoreService.api.v1.ListPublishedVideoResponse.pagination:type_name -> shortVideoCoreService.api.v1.PaginationResponse
	14, // 10: shortVideoCoreService.api.v1.GetVideoByIdListResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 11: shortVideoCoreService.api.v1.GetVideoByIdListResponse.videos:type_name -> shortVideoCoreService.api.v1.Video
	14, // 12: shortVideoCoreService.api.v1.SearchVideoResponse.meta:type_name -> shortVideoCoreService.api.v1.Metadata
	1,  // 13: shortVideoCoreService.api.v1.SearchVideoResponse.videos:type_name -> shortVideoCoreService.api.v1.Video
	2,  // 14: shortVideoCoreService.api.v1.VideoService.FeedShortVideo:input_type -> shortVideoCoreService.api.v1.FeedShortVideoRequest
	4,  // 15: shortVideoCoreService.api.v1.VideoService.GetVideoById:input_type -> shortVideoCoreService.api.v1.GetVideoByIdRequest
	6,  // 16: shortVideoCoreService.api.v1.VideoService.PublishVideo:input_type -> shortVideoCoreService.api.v1.PublishVideoRequest
	8,  // 17: shortVideoCoreService.api.v1.VideoService.ListPublishedVideo:input_type -> shortVideoCoreService.api.v1.ListPublishedVideoRequest
	10, // 18: shortVideoCoreService.api.v1.VideoService.GetVideoByIdList:input_type -> shortVideoCoreService.api.v1.GetVideoByIdListRequest
	12, // 19: shortVideoCoreService.api.v1.VideoService.SearchVideo:input_type -> shortVideoCoreService.api.v1.SearchVideoRequest
	3,  // 20: shortVideoCoreService.api.v1.VideoService.FeedShortVideo:output_type -> shortVideoCoreService.api.v1.FeedShortVideoResponse
	5,  // 21: shortVideoCoreService.api.v1.VideoService.GetVideoById:output_type -> shortVideoCoreService.api.v1.GetVideoByIdResponse
	7,  // 22: shortVideoCoreService.api.v1.VideoService.PublishVideo:output_type -> shortVideoCoreService.api.v1.PublishVideoResponse
	9,  // 23: shortVideoCoreService.api.v1.VideoService.ListPublishedVideo:output_type -> shortVideoCoreService.api.v1.ListPublishedVideoResponse
	11, // 24: shortVideoCoreService.api.v1.VideoService.GetVideoByIdList:output_type -> shortVideoCoreService.api.v1.GetVideoByIdListResponse
	13, // 25: shortVideoCoreService.api.v1.VideoService.SearchVideo:output_type -> shortVideoCoreService.api.v1.SearchVideoResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_video_proto_init() }
func file_v1_video_proto_init() {
	if File_v1_video_proto != nil {
		return
	}
	file_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_video_proto_rawDesc), len(file_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_video_proto_goTypes,
		DependencyIndexes: file_v1_video_proto_depIdxs,
		MessageInfos:      file_v1_video_proto_msgTypes,
	}.Build()
	File_v1_video_proto = out.File
	file_v1_video_proto_goTypes = nil
	file_v1_video_proto_depIdxs = nil
}
