/* Generated by restful-react */

import React from "react";
import {
  Get,
  GetProps,
  useGet,
  UseGetProps,
  Mutate,
  MutateProps,
  useMutate,
  UseMutateProps
} from "restful-react";
export const SPEC_VERSION = "0.0.1";
export interface SvapiAddFavoriteRequest {
  target?: number;
  type?: number;
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiAddFavoriteResponse {}

export interface SvapiAddFollowRequest {
  /**
   * @gotags: json:"userId,omitempty,string"
   */
  userId?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiAddFollowResponse {}

export interface SvapiAddVideo2CollectionRequest {
  /**
   * @gotags: json:"collectionId,omitempty,string"
   */
  collectionId?: string;
  /**
   * @gotags: json:"videoId,omitempty,string"
   */
  videoId?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiAddVideo2CollectionResponse {}

export interface SvapiBindUserVoucherRequest {
  voucherType?: number;
  voucher?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiBindUserVoucherResponse {}

export interface SvapiCollection {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  /**
   * @gotags: json:"userId,omitempty,string"
   */
  userId?: string;
  name?: string;
  description?: string;
}

export interface SvapiComment {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  /**
   * @gotags: json:"videoId,omitempty,string"
   */
  videoId?: string;
  /**
   * @gotags: json:"parentId,omitempty,string"
   */
  parentId?: string;
  user?: SvapiCommentUser;
  replyUser?: SvapiCommentUser;
  content?: string;
  date?: string;
  likeCount?: string;
  replyCount?: string;
  comments?: SvapiComment[];
}

export interface SvapiCommentUser {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  name?: string;
  avatar?: string;
  isFollowing?: boolean;
}

/**
 * 搜索请求消息类型
 */
export interface SvapiContentSearchRequest {
  query?: string;
  type?: number;
  pagination?: SvapiPaginationRequest;
}

/**
 * 搜索响应消息类型
 */
export interface SvapiContentSearchResponse {
  videos?: SvapiVideo[];
  users?: SvapiUser[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiCreateCollectionRequest {
  name?: string;
  description?: string;
}

export interface SvapiCreateCollectionResponse {
  collection?: SvapiCollection;
}

export interface SvapiCreateCommentRequest {
  /**
   * @gotags: json:"videoId,omitempty,string"
   */
  videoId?: string;
  content?: string;
  /**
   * @gotags: json:"parentId,omitempty,string"
   */
  parentId?: string;
  /**
   * @gotags: json:"replyUserId,omitempty,string"
   */
  replyUserId?: string;
}

export interface SvapiCreateCommentResponse {
  comment?: SvapiComment;
}

/**
 * 刷视频请求消息类型
 */
export interface SvapiFeedShortVideoRequest {
  /**
   * @gotags: json:"latest_time,omitempty,string"
   */
  latestTime?: string;
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
  /**
   * @gotags: json:"feed_num,omitempty,string"
   */
  feedNum?: string;
}

/**
 * 刷视频响应消息类型
 */
export interface SvapiFeedShortVideoResponse {
  meta?: SvapiMetadata;
  videos?: SvapiVideo[];
  /**
   * @gotags: json:"next_time,omitempty,string"
   */
  nextTime?: string;
}

export interface SvapiFollowUser {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  name?: string;
  avatar?: string;
  isFollowing?: boolean;
}

export interface SvapiGetUserInfoResponse {
  user?: SvapiUser;
}

export interface SvapiGetVerificationCodeRequest {
  mobile?: string;
  email?: string;
}

export interface SvapiGetVerificationCodeResponse {
  /**
   * @gotags: json:"code_id,omitempty,string"
   */
  codeId?: string;
}

/**
 * 获取视频信息响应消息类型
 */
export interface SvapiGetVideoByIdResponse {
  video?: SvapiVideo;
}

export interface SvapiListChildCommentRequest {
  /**
   * @gotags: json:"commentId,omitempty,string"
   */
  commentId?: string;
  pagination?: SvapiPaginationRequest;
}

export interface SvapiListChildCommentResponse {
  comments?: SvapiComment[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiListCollectionResponse {
  collections?: SvapiCollection[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiListComment4VideoRequest {
  /**
   * @gotags: json:"videoId,omitempty,string"
   */
  videoId?: string;
  pagination?: SvapiPaginationRequest;
}

export interface SvapiListComment4VideoResponse {
  comments?: SvapiComment[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiListFavoriteVideoRequest {
  userId?: string;
  page?: number;
  size?: number;
}

export interface SvapiListFavoriteVideoResponse {
  videos?: SvapiVideo[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiListFollowingResponse {
  users?: SvapiFollowUser[];
  pagination?: SvapiPaginationResponse;
}

/**
 * 获取当前用户的发布视频列表请求消息类型
 */
export interface SvapiListPublishedVideoRequest {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
  pagination?: SvapiPaginationRequest;
}

/**
 * 获取当前用户的发布视频列表响应消息类型
 */
export interface SvapiListPublishedVideoResponse {
  videoList?: SvapiVideo[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiListVideo4CollectionResponse {
  videos?: SvapiVideo[];
  pagination?: SvapiPaginationResponse;
}

export interface SvapiLoginRequest {
  mobile?: string;
  email?: string;
  password?: string;
}

export interface SvapiLoginResponse {
  token?: string;
}

export interface SvapiMetadata {
  bizCode?: number;
  message?: string;
  domain?: string;
  reason?: string[];
}

export interface SvapiPaginationRequest {
  page?: number;
  size?: number;
  sort?: SvapiSortField[];
}

export interface SvapiPaginationResponse {
  page?: number;
  total?: number;
  count?: number;
}

/**
 * 通用小文件单次上传请求消息类型
 */
export interface SvapiPreSign4UploadRequest {
  /**
   * md5 hash
   */
  hash?: string;
  /**
   * 文件类型，默认mp4
   */
  fileType?: string;
  /**
   * 文件大小，单位byte
   *  @gotags: json:"size,omitempty,string"
   */
  size?: string;
  /**
   * 文件名
   */
  filename?: string;
}

/**
 * 通用小文件单次上传响应消息类型
 */
export interface SvapiPreSign4UploadResponse {
  /**
   * minio上传地址
   */
  url?: string;
  /**
   * 文件id
   *  @gotags: json:"file_id,omitempty,string"
   */
  fileId?: string;
}

/**
 * 预注册上传视频请求消息类型
 */
export interface SvapiPreSign4UploadVideoRequest {
  /**
   * md5 hash
   */
  hash?: string;
  /**
   * 文件类型，默认mp4
   */
  fileType?: string;
  /**
   * 文件大小，单位byte
   *  @gotags: json:"size,omitempty,string"
   */
  size?: string;
  /**
   * 文件名
   */
  filename?: string;
}

/**
 * 预注册上传视频响应消息类型
 */
export interface SvapiPreSign4UploadVideoResponse {
  /**
   * minio上传地址
   */
  url?: string;
  /**
   * 文件id
   *  @gotags: json:"file_id,omitempty,string"
   */
  fileId?: string;
}

export interface SvapiPreSignUploadPublicFileRequest {
  hash?: string;
  fileType?: string;
  /**
   * gotags: json`size,omitempty,string`
   */
  size?: string;
}

export interface SvapiPreSignUploadPublicFileResponse {
  url?: string;
  /**
   * @gotags: json:"file_id,omitempty,string"
   */
  fileId?: string;
}

export interface SvapiRegisterRequest {
  mobile?: string;
  email?: string;
  password?: string;
  /**
   * @gotags: json:"code_id,omitempty,string"
   */
  codeId?: string;
  code?: string;
}

export interface SvapiRegisterResponse {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
}

export interface SvapiRemoveCollectionRequest {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiRemoveCollectionResponse {}

export interface SvapiRemoveCommentRequest {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiRemoveCommentResponse {}

export interface SvapiRemoveFavoriteRequest {
  target?: number;
  type?: number;
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiRemoveFavoriteResponse {}

export interface SvapiRemoveFollowRequest {
  /**
   * @gotags: json:"userId,omitempty,string"
   */
  userId?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiRemoveFollowResponse {}

export interface SvapiRemoveVideoFromCollectionRequest {
  /**
   * @gotags: json:"collectionId,omitempty,string"
   */
  collectionId?: string;
  /**
   * @gotags: json:"videoId,omitempty,string"
   */
  videoId?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiRemoveVideoFromCollectionResponse {}

/**
 * 通用确认上传完成请求消息类型
 */
export interface SvapiReportFinishUploadRequest {
  /**
   * 文件id
   *  @gotags: json:"file_id,omitempty,string"
   */
  fileId?: string;
}

/**
 * 通用确认上传完成响应消息类型
 */
export interface SvapiReportFinishUploadResponse {
  /**
   * url
   */
  url?: string;
}

export interface SvapiReportPublicFileUploadedRequest {
  fileId?: string;
}

export interface SvapiReportPublicFileUploadedResponse {
  objectName?: string;
}

/**
 * 确认视频上传完成请求消息类型
 */
export interface SvapiReportVideoFinishUploadRequest {
  /**
   * 文件id
   *  @gotags: json:"file_id,omitempty,string"
   */
  fileId?: string;
  /**
   * 视频标题
   */
  title?: string;
  /**
   * 视频封面地址
   */
  coverUrl?: string;
  /**
   * 视频描述
   */
  description?: string;
  /**
   * 视频地址
   */
  videoUrl?: string;
}

/**
 * 确认视频上传完成响应消息类型
 */
export interface SvapiReportVideoFinishUploadResponse {
  /**
   * 视频id
   *  @gotags: json:"video_id,omitempty,string"
   */
  videoId?: string;
}

export interface SvapiSortField {
  field?: string;
  order?: number;
}

export interface SvapiUnbindUserVoucherRequest {
  voucherType?: number;
  voucher?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiUnbindUserVoucherResponse {}

export interface SvapiUpdateCollectionRequest {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  name?: string;
  description?: string;
}

export interface SvapiUpdateCollectionResponse {
  collection?: SvapiCollection;
}

export interface SvapiUpdateUserInfoRequest {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
  name?: string;
  avatar?: string;
  backgroundImage?: string;
  signature?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiUpdateUserInfoResponse {}

export interface SvapiUser {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  name?: string;
  avatar?: string;
  backgroundImage?: string;
  signature?: string;
  mobile?: string;
  email?: string;
  /**
   * @gotags: json:"followCount,omitempty,string"
   */
  followCount?: string;
  /**
   * @gotags: json:"followerCount,omitempty,string"
   */
  followerCount?: string;
  /**
   * @gotags: json:"totalFavorited,omitempty,string"
   */
  totalFavorited?: string;
  /**
   * @gotags: json:"workCount,omitempty,string"
   */
  workCount?: string;
  /**
   * @gotags: json:"favoriteCount,omitempty,string"
   */
  favoriteCount?: string;
}

export interface SvapiVideo {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  author?: SvapiVideoAuthor;
  play_url?: string;
  cover_url?: string;
  /**
   * @gotags: json:"favoriteCount,omitempty,string"
   */
  favoriteCount?: string;
  /**
   * @gotags: json:"commentCount,omitempty,string"
   */
  commentCount?: string;
  isFavorite?: boolean;
  title?: string;
  isCollected?: boolean;
  /**
   * @gotags: json:"collectedCount,omitempty,string"
   */
  collectedCount?: string;
}

export interface SvapiVideoAuthor {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  name?: string;
  avatar?: string;
  isFollowing?: boolean;
}

export interface CollectionServiceListCollectionQueryParams {
  "pagination.page"?: number;
  "pagination.size"?: number;
}

export type CollectionServiceListCollectionProps = Omit<
  GetProps<
    SvapiListCollectionResponse,
    unknown,
    CollectionServiceListCollectionQueryParams,
    void
  >,
  "path"
>;

/**
 * 列出用户的收藏夹
 */
export const CollectionServiceListCollection = (
  props: CollectionServiceListCollectionProps
) => (
  <Get<
    SvapiListCollectionResponse,
    unknown,
    CollectionServiceListCollectionQueryParams,
    void
  >
    path={`/collection`}
    {...props}
  />
);

export type UseCollectionServiceListCollectionProps = Omit<
  UseGetProps<
    SvapiListCollectionResponse,
    unknown,
    CollectionServiceListCollectionQueryParams,
    void
  >,
  "path"
>;

/**
 * 列出用户的收藏夹
 */
export const useCollectionServiceListCollection = (
  props: UseCollectionServiceListCollectionProps
) =>
  useGet<
    SvapiListCollectionResponse,
    unknown,
    CollectionServiceListCollectionQueryParams,
    void
  >(`/collection`, props);

export type CollectionServiceUpdateCollectionProps = Omit<
  MutateProps<
    SvapiUpdateCollectionResponse,
    unknown,
    void,
    SvapiUpdateCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 更新收藏夹信息
 */
export const CollectionServiceUpdateCollection = (
  props: CollectionServiceUpdateCollectionProps
) => (
  <Mutate<
    SvapiUpdateCollectionResponse,
    unknown,
    void,
    SvapiUpdateCollectionRequest,
    void
  >
    verb="PUT"
    path={`/collection`}
    {...props}
  />
);

export type UseCollectionServiceUpdateCollectionProps = Omit<
  UseMutateProps<
    SvapiUpdateCollectionResponse,
    unknown,
    void,
    SvapiUpdateCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 更新收藏夹信息
 */
export const useCollectionServiceUpdateCollection = (
  props: UseCollectionServiceUpdateCollectionProps
) =>
  useMutate<
    SvapiUpdateCollectionResponse,
    unknown,
    void,
    SvapiUpdateCollectionRequest,
    void
  >("PUT", `/collection`, props);

export type CollectionServiceCreateCollectionProps = Omit<
  MutateProps<
    SvapiCreateCollectionResponse,
    unknown,
    void,
    SvapiCreateCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 创建收藏夹
 */
export const CollectionServiceCreateCollection = (
  props: CollectionServiceCreateCollectionProps
) => (
  <Mutate<
    SvapiCreateCollectionResponse,
    unknown,
    void,
    SvapiCreateCollectionRequest,
    void
  >
    verb="POST"
    path={`/collection`}
    {...props}
  />
);

export type UseCollectionServiceCreateCollectionProps = Omit<
  UseMutateProps<
    SvapiCreateCollectionResponse,
    unknown,
    void,
    SvapiCreateCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 创建收藏夹
 */
export const useCollectionServiceCreateCollection = (
  props: UseCollectionServiceCreateCollectionProps
) =>
  useMutate<
    SvapiCreateCollectionResponse,
    unknown,
    void,
    SvapiCreateCollectionRequest,
    void
  >("POST", `/collection`, props);

export type CollectionServiceRemoveCollectionProps = Omit<
  MutateProps<
    SvapiRemoveCollectionResponse,
    unknown,
    void,
    SvapiRemoveCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 删除收藏夹
 */
export const CollectionServiceRemoveCollection = (
  props: CollectionServiceRemoveCollectionProps
) => (
  <Mutate<
    SvapiRemoveCollectionResponse,
    unknown,
    void,
    SvapiRemoveCollectionRequest,
    void
  >
    verb="DELETE"
    path={`/collection`}
    {...props}
  />
);

export type UseCollectionServiceRemoveCollectionProps = Omit<
  UseMutateProps<
    SvapiRemoveCollectionResponse,
    unknown,
    void,
    SvapiRemoveCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 删除收藏夹
 */
export const useCollectionServiceRemoveCollection = (
  props: UseCollectionServiceRemoveCollectionProps
) =>
  useMutate<
    SvapiRemoveCollectionResponse,
    unknown,
    void,
    SvapiRemoveCollectionRequest,
    void
  >("DELETE", `/collection`, { ...props });

export interface CollectionServiceListVideo4CollectionQueryParams {
  /**
   * @gotags: json:"collectionId,omitempty,string"
   */
  collectionId?: string;
  "pagination.page"?: number;
  "pagination.size"?: number;
}

export type CollectionServiceListVideo4CollectionProps = Omit<
  GetProps<
    SvapiListVideo4CollectionResponse,
    unknown,
    CollectionServiceListVideo4CollectionQueryParams,
    void
  >,
  "path"
>;

/**
 * 列出收藏夹中的视频
 */
export const CollectionServiceListVideo4Collection = (
  props: CollectionServiceListVideo4CollectionProps
) => (
  <Get<
    SvapiListVideo4CollectionResponse,
    unknown,
    CollectionServiceListVideo4CollectionQueryParams,
    void
  >
    path={`/collection/video`}
    {...props}
  />
);

export type UseCollectionServiceListVideo4CollectionProps = Omit<
  UseGetProps<
    SvapiListVideo4CollectionResponse,
    unknown,
    CollectionServiceListVideo4CollectionQueryParams,
    void
  >,
  "path"
>;

/**
 * 列出收藏夹中的视频
 */
export const useCollectionServiceListVideo4Collection = (
  props: UseCollectionServiceListVideo4CollectionProps
) =>
  useGet<
    SvapiListVideo4CollectionResponse,
    unknown,
    CollectionServiceListVideo4CollectionQueryParams,
    void
  >(`/collection/video`, props);

export type CollectionServiceAddVideo2CollectionProps = Omit<
  MutateProps<
    SvapiAddVideo2CollectionResponse,
    unknown,
    void,
    SvapiAddVideo2CollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 将视频添加到收藏夹
 */
export const CollectionServiceAddVideo2Collection = (
  props: CollectionServiceAddVideo2CollectionProps
) => (
  <Mutate<
    SvapiAddVideo2CollectionResponse,
    unknown,
    void,
    SvapiAddVideo2CollectionRequest,
    void
  >
    verb="POST"
    path={`/collection/video`}
    {...props}
  />
);

export type UseCollectionServiceAddVideo2CollectionProps = Omit<
  UseMutateProps<
    SvapiAddVideo2CollectionResponse,
    unknown,
    void,
    SvapiAddVideo2CollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 将视频添加到收藏夹
 */
export const useCollectionServiceAddVideo2Collection = (
  props: UseCollectionServiceAddVideo2CollectionProps
) =>
  useMutate<
    SvapiAddVideo2CollectionResponse,
    unknown,
    void,
    SvapiAddVideo2CollectionRequest,
    void
  >("POST", `/collection/video`, props);

export type CollectionServiceRemoveVideoFromCollectionProps = Omit<
  MutateProps<
    SvapiRemoveVideoFromCollectionResponse,
    unknown,
    void,
    SvapiRemoveVideoFromCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 从收藏夹中移除视频
 */
export const CollectionServiceRemoveVideoFromCollection = (
  props: CollectionServiceRemoveVideoFromCollectionProps
) => (
  <Mutate<
    SvapiRemoveVideoFromCollectionResponse,
    unknown,
    void,
    SvapiRemoveVideoFromCollectionRequest,
    void
  >
    verb="DELETE"
    path={`/collection/video`}
    {...props}
  />
);

export type UseCollectionServiceRemoveVideoFromCollectionProps = Omit<
  UseMutateProps<
    SvapiRemoveVideoFromCollectionResponse,
    unknown,
    void,
    SvapiRemoveVideoFromCollectionRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 从收藏夹中移除视频
 */
export const useCollectionServiceRemoveVideoFromCollection = (
  props: UseCollectionServiceRemoveVideoFromCollectionProps
) =>
  useMutate<
    SvapiRemoveVideoFromCollectionResponse,
    unknown,
    void,
    SvapiRemoveVideoFromCollectionRequest,
    void
  >("DELETE", `/collection/video`, { ...props });

export type CommentServiceCreateCommentProps = Omit<
  MutateProps<
    SvapiCreateCommentResponse,
    unknown,
    void,
    SvapiCreateCommentRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 创建评论
 */
export const CommentServiceCreateComment = (
  props: CommentServiceCreateCommentProps
) => (
  <Mutate<
    SvapiCreateCommentResponse,
    unknown,
    void,
    SvapiCreateCommentRequest,
    void
  >
    verb="POST"
    path={`/comment`}
    {...props}
  />
);

export type UseCommentServiceCreateCommentProps = Omit<
  UseMutateProps<
    SvapiCreateCommentResponse,
    unknown,
    void,
    SvapiCreateCommentRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 创建评论
 */
export const useCommentServiceCreateComment = (
  props: UseCommentServiceCreateCommentProps
) =>
  useMutate<
    SvapiCreateCommentResponse,
    unknown,
    void,
    SvapiCreateCommentRequest,
    void
  >("POST", `/comment`, props);

export type CommentServiceRemoveCommentProps = Omit<
  MutateProps<
    SvapiRemoveCommentResponse,
    unknown,
    void,
    SvapiRemoveCommentRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 删除评论
 */
export const CommentServiceRemoveComment = (
  props: CommentServiceRemoveCommentProps
) => (
  <Mutate<
    SvapiRemoveCommentResponse,
    unknown,
    void,
    SvapiRemoveCommentRequest,
    void
  >
    verb="DELETE"
    path={`/comment`}
    {...props}
  />
);

export type UseCommentServiceRemoveCommentProps = Omit<
  UseMutateProps<
    SvapiRemoveCommentResponse,
    unknown,
    void,
    SvapiRemoveCommentRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 删除评论
 */
export const useCommentServiceRemoveComment = (
  props: UseCommentServiceRemoveCommentProps
) =>
  useMutate<
    SvapiRemoveCommentResponse,
    unknown,
    void,
    SvapiRemoveCommentRequest,
    void
  >("DELETE", `/comment`, { ...props });

export type CommentServiceListChildCommentProps = Omit<
  MutateProps<
    SvapiListChildCommentResponse,
    unknown,
    void,
    SvapiListChildCommentRequest,
    void
  >,
  "path" | "verb"
>;

export const CommentServiceListChildComment = (
  props: CommentServiceListChildCommentProps
) => (
  <Mutate<
    SvapiListChildCommentResponse,
    unknown,
    void,
    SvapiListChildCommentRequest,
    void
  >
    verb="POST"
    path={`/comment/child`}
    {...props}
  />
);

export type UseCommentServiceListChildCommentProps = Omit<
  UseMutateProps<
    SvapiListChildCommentResponse,
    unknown,
    void,
    SvapiListChildCommentRequest,
    void
  >,
  "path" | "verb"
>;

export const useCommentServiceListChildComment = (
  props: UseCommentServiceListChildCommentProps
) =>
  useMutate<
    SvapiListChildCommentResponse,
    unknown,
    void,
    SvapiListChildCommentRequest,
    void
  >("POST", `/comment/child`, props);

export type CommentServiceListComment4VideoProps = Omit<
  MutateProps<
    SvapiListComment4VideoResponse,
    unknown,
    void,
    SvapiListComment4VideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 列出视频的评论
 */
export const CommentServiceListComment4Video = (
  props: CommentServiceListComment4VideoProps
) => (
  <Mutate<
    SvapiListComment4VideoResponse,
    unknown,
    void,
    SvapiListComment4VideoRequest,
    void
  >
    verb="POST"
    path={`/comment/video`}
    {...props}
  />
);

export type UseCommentServiceListComment4VideoProps = Omit<
  UseMutateProps<
    SvapiListComment4VideoResponse,
    unknown,
    void,
    SvapiListComment4VideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 列出视频的评论
 */
export const useCommentServiceListComment4Video = (
  props: UseCommentServiceListComment4VideoProps
) =>
  useMutate<
    SvapiListComment4VideoResponse,
    unknown,
    void,
    SvapiListComment4VideoRequest,
    void
  >("POST", `/comment/video`, props);

export type ShortVideoCoreVideoServicePreSign4UploadCoverProps = Omit<
  MutateProps<
    SvapiPreSign4UploadResponse,
    unknown,
    void,
    SvapiPreSign4UploadRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 预注册上传封面
 */
export const ShortVideoCoreVideoServicePreSign4UploadCover = (
  props: ShortVideoCoreVideoServicePreSign4UploadCoverProps
) => (
  <Mutate<
    SvapiPreSign4UploadResponse,
    unknown,
    void,
    SvapiPreSign4UploadRequest,
    void
  >
    verb="POST"
    path={`/cover/upload`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServicePreSign4UploadCoverProps = Omit<
  UseMutateProps<
    SvapiPreSign4UploadResponse,
    unknown,
    void,
    SvapiPreSign4UploadRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 预注册上传封面
 */
export const useShortVideoCoreVideoServicePreSign4UploadCover = (
  props: UseShortVideoCoreVideoServicePreSign4UploadCoverProps
) =>
  useMutate<
    SvapiPreSign4UploadResponse,
    unknown,
    void,
    SvapiPreSign4UploadRequest,
    void
  >("POST", `/cover/upload`, props);

export type FavoriteServiceAddFavoriteProps = Omit<
  MutateProps<
    SvapiAddFavoriteResponse,
    unknown,
    void,
    SvapiAddFavoriteRequest,
    void
  >,
  "path" | "verb"
>;

export const FavoriteServiceAddFavorite = (
  props: FavoriteServiceAddFavoriteProps
) => (
  <Mutate<
    SvapiAddFavoriteResponse,
    unknown,
    void,
    SvapiAddFavoriteRequest,
    void
  >
    verb="POST"
    path={`/favorite`}
    {...props}
  />
);

export type UseFavoriteServiceAddFavoriteProps = Omit<
  UseMutateProps<
    SvapiAddFavoriteResponse,
    unknown,
    void,
    SvapiAddFavoriteRequest,
    void
  >,
  "path" | "verb"
>;

export const useFavoriteServiceAddFavorite = (
  props: UseFavoriteServiceAddFavoriteProps
) =>
  useMutate<
    SvapiAddFavoriteResponse,
    unknown,
    void,
    SvapiAddFavoriteRequest,
    void
  >("POST", `/favorite`, props);

export type FavoriteServiceRemoveFavoriteProps = Omit<
  MutateProps<
    SvapiRemoveFavoriteResponse,
    unknown,
    void,
    SvapiRemoveFavoriteRequest,
    void
  >,
  "path" | "verb"
>;

export const FavoriteServiceRemoveFavorite = (
  props: FavoriteServiceRemoveFavoriteProps
) => (
  <Mutate<
    SvapiRemoveFavoriteResponse,
    unknown,
    void,
    SvapiRemoveFavoriteRequest,
    void
  >
    verb="DELETE"
    path={`/favorite`}
    {...props}
  />
);

export type UseFavoriteServiceRemoveFavoriteProps = Omit<
  UseMutateProps<
    SvapiRemoveFavoriteResponse,
    unknown,
    void,
    SvapiRemoveFavoriteRequest,
    void
  >,
  "path" | "verb"
>;

export const useFavoriteServiceRemoveFavorite = (
  props: UseFavoriteServiceRemoveFavoriteProps
) =>
  useMutate<
    SvapiRemoveFavoriteResponse,
    unknown,
    void,
    SvapiRemoveFavoriteRequest,
    void
  >("DELETE", `/favorite`, { ...props });

export type FavoriteServiceListFavoriteVideoProps = Omit<
  MutateProps<
    SvapiListFavoriteVideoResponse,
    unknown,
    void,
    SvapiListFavoriteVideoRequest,
    void
  >,
  "path" | "verb"
>;

export const FavoriteServiceListFavoriteVideo = (
  props: FavoriteServiceListFavoriteVideoProps
) => (
  <Mutate<
    SvapiListFavoriteVideoResponse,
    unknown,
    void,
    SvapiListFavoriteVideoRequest,
    void
  >
    verb="POST"
    path={`/favorite/video/list`}
    {...props}
  />
);

export type UseFavoriteServiceListFavoriteVideoProps = Omit<
  UseMutateProps<
    SvapiListFavoriteVideoResponse,
    unknown,
    void,
    SvapiListFavoriteVideoRequest,
    void
  >,
  "path" | "verb"
>;

export const useFavoriteServiceListFavoriteVideo = (
  props: UseFavoriteServiceListFavoriteVideoProps
) =>
  useMutate<
    SvapiListFavoriteVideoResponse,
    unknown,
    void,
    SvapiListFavoriteVideoRequest,
    void
  >("POST", `/favorite/video/list`, props);

export interface ShortVideoCoreVideoServiceReportFinishUploadPathParams {
  /**
   * 文件id
   *  @gotags: json:"file_id,omitempty,string"
   */
  fileId: string;
}

export type ShortVideoCoreVideoServiceReportFinishUploadProps = Omit<
  MutateProps<
    SvapiReportFinishUploadResponse,
    unknown,
    void,
    SvapiReportFinishUploadRequest,
    ShortVideoCoreVideoServiceReportFinishUploadPathParams
  >,
  "path" | "verb"
> &
  ShortVideoCoreVideoServiceReportFinishUploadPathParams;

/**
 * 通用确认上传完成
 */
export const ShortVideoCoreVideoServiceReportFinishUpload = ({
  fileId,
  ...props
}: ShortVideoCoreVideoServiceReportFinishUploadProps) => (
  <Mutate<
    SvapiReportFinishUploadResponse,
    unknown,
    void,
    SvapiReportFinishUploadRequest,
    ShortVideoCoreVideoServiceReportFinishUploadPathParams
  >
    verb="POST"
    path={`/file/${fileId}/finish`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServiceReportFinishUploadProps = Omit<
  UseMutateProps<
    SvapiReportFinishUploadResponse,
    unknown,
    void,
    SvapiReportFinishUploadRequest,
    ShortVideoCoreVideoServiceReportFinishUploadPathParams
  >,
  "path" | "verb"
> &
  ShortVideoCoreVideoServiceReportFinishUploadPathParams;

/**
 * 通用确认上传完成
 */
export const useShortVideoCoreVideoServiceReportFinishUpload = ({
  fileId,
  ...props
}: UseShortVideoCoreVideoServiceReportFinishUploadProps) =>
  useMutate<
    SvapiReportFinishUploadResponse,
    unknown,
    void,
    SvapiReportFinishUploadRequest,
    ShortVideoCoreVideoServiceReportFinishUploadPathParams
  >(
    "POST",
    (paramsInPath: ShortVideoCoreVideoServiceReportFinishUploadPathParams) =>
      `/file/${paramsInPath.fileId}/finish`,
    { pathParams: { fileId }, ...props }
  );

export interface FollowServiceListFollowingQueryParams {
  /**
   * @gotags: json:"userId,omitempty,string"
   */
  userId?: string;
  type?: number;
  "pagination.page"?: number;
  "pagination.size"?: number;
}

export type FollowServiceListFollowingProps = Omit<
  GetProps<
    SvapiListFollowingResponse,
    unknown,
    FollowServiceListFollowingQueryParams,
    void
  >,
  "path"
>;

export const FollowServiceListFollowing = (
  props: FollowServiceListFollowingProps
) => (
  <Get<
    SvapiListFollowingResponse,
    unknown,
    FollowServiceListFollowingQueryParams,
    void
  >
    path={`/follow`}
    {...props}
  />
);

export type UseFollowServiceListFollowingProps = Omit<
  UseGetProps<
    SvapiListFollowingResponse,
    unknown,
    FollowServiceListFollowingQueryParams,
    void
  >,
  "path"
>;

export const useFollowServiceListFollowing = (
  props: UseFollowServiceListFollowingProps
) =>
  useGet<
    SvapiListFollowingResponse,
    unknown,
    FollowServiceListFollowingQueryParams,
    void
  >(`/follow`, props);

export type FollowServiceAddFollowProps = Omit<
  MutateProps<
    SvapiAddFollowResponse,
    unknown,
    void,
    SvapiAddFollowRequest,
    void
  >,
  "path" | "verb"
>;

export const FollowServiceAddFollow = (props: FollowServiceAddFollowProps) => (
  <Mutate<SvapiAddFollowResponse, unknown, void, SvapiAddFollowRequest, void>
    verb="POST"
    path={`/follow`}
    {...props}
  />
);

export type UseFollowServiceAddFollowProps = Omit<
  UseMutateProps<
    SvapiAddFollowResponse,
    unknown,
    void,
    SvapiAddFollowRequest,
    void
  >,
  "path" | "verb"
>;

export const useFollowServiceAddFollow = (
  props: UseFollowServiceAddFollowProps
) =>
  useMutate<SvapiAddFollowResponse, unknown, void, SvapiAddFollowRequest, void>(
    "POST",
    `/follow`,
    props
  );

export type FollowServiceRemoveFollowProps = Omit<
  MutateProps<
    SvapiRemoveFollowResponse,
    unknown,
    void,
    SvapiRemoveFollowRequest,
    void
  >,
  "path" | "verb"
>;

export const FollowServiceRemoveFollow = (
  props: FollowServiceRemoveFollowProps
) => (
  <Mutate<
    SvapiRemoveFollowResponse,
    unknown,
    void,
    SvapiRemoveFollowRequest,
    void
  >
    verb="DELETE"
    path={`/follow`}
    {...props}
  />
);

export type UseFollowServiceRemoveFollowProps = Omit<
  UseMutateProps<
    SvapiRemoveFollowResponse,
    unknown,
    void,
    SvapiRemoveFollowRequest,
    void
  >,
  "path" | "verb"
>;

export const useFollowServiceRemoveFollow = (
  props: UseFollowServiceRemoveFollowProps
) =>
  useMutate<
    SvapiRemoveFollowResponse,
    unknown,
    void,
    SvapiRemoveFollowRequest,
    void
  >("DELETE", `/follow`, { ...props });

export type SearchServiceSearchProps = Omit<
  MutateProps<
    SvapiContentSearchResponse,
    unknown,
    void,
    SvapiContentSearchRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 搜索
 */
export const SearchServiceSearch = (props: SearchServiceSearchProps) => (
  <Mutate<
    SvapiContentSearchResponse,
    unknown,
    void,
    SvapiContentSearchRequest,
    void
  >
    verb="POST"
    path={`/search`}
    {...props}
  />
);

export type UseSearchServiceSearchProps = Omit<
  UseMutateProps<
    SvapiContentSearchResponse,
    unknown,
    void,
    SvapiContentSearchRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 搜索
 */
export const useSearchServiceSearch = (props: UseSearchServiceSearchProps) =>
  useMutate<
    SvapiContentSearchResponse,
    unknown,
    void,
    SvapiContentSearchRequest,
    void
  >("POST", `/search`, props);

export type UserServiceGetVerificationCodeProps = Omit<
  MutateProps<
    SvapiGetVerificationCodeResponse,
    unknown,
    void,
    SvapiGetVerificationCodeRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 获取验证码
 */
export const UserServiceGetVerificationCode = (
  props: UserServiceGetVerificationCodeProps
) => (
  <Mutate<
    SvapiGetVerificationCodeResponse,
    unknown,
    void,
    SvapiGetVerificationCodeRequest,
    void
  >
    verb="POST"
    path={`/user/code`}
    {...props}
  />
);

export type UseUserServiceGetVerificationCodeProps = Omit<
  UseMutateProps<
    SvapiGetVerificationCodeResponse,
    unknown,
    void,
    SvapiGetVerificationCodeRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 获取验证码
 */
export const useUserServiceGetVerificationCode = (
  props: UseUserServiceGetVerificationCodeProps
) =>
  useMutate<
    SvapiGetVerificationCodeResponse,
    unknown,
    void,
    SvapiGetVerificationCodeRequest,
    void
  >("POST", `/user/code`, props);

export interface UserServiceGetUserInfoQueryParams {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
}

export type UserServiceGetUserInfoProps = Omit<
  GetProps<
    SvapiGetUserInfoResponse,
    unknown,
    UserServiceGetUserInfoQueryParams,
    void
  >,
  "path"
>;

/**
 * 获取用户信息
 */
export const UserServiceGetUserInfo = (props: UserServiceGetUserInfoProps) => (
  <Get<
    SvapiGetUserInfoResponse,
    unknown,
    UserServiceGetUserInfoQueryParams,
    void
  >
    path={`/user/info`}
    {...props}
  />
);

export type UseUserServiceGetUserInfoProps = Omit<
  UseGetProps<
    SvapiGetUserInfoResponse,
    unknown,
    UserServiceGetUserInfoQueryParams,
    void
  >,
  "path"
>;

/**
 * 获取用户信息
 */
export const useUserServiceGetUserInfo = (
  props: UseUserServiceGetUserInfoProps
) =>
  useGet<
    SvapiGetUserInfoResponse,
    unknown,
    UserServiceGetUserInfoQueryParams,
    void
  >(`/user/info`, props);

export type UserServiceUpdateUserInfoProps = Omit<
  MutateProps<
    SvapiUpdateUserInfoResponse,
    unknown,
    void,
    SvapiUpdateUserInfoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 更新用户信息
 */
export const UserServiceUpdateUserInfo = (
  props: UserServiceUpdateUserInfoProps
) => (
  <Mutate<
    SvapiUpdateUserInfoResponse,
    unknown,
    void,
    SvapiUpdateUserInfoRequest,
    void
  >
    verb="PUT"
    path={`/user/info`}
    {...props}
  />
);

export type UseUserServiceUpdateUserInfoProps = Omit<
  UseMutateProps<
    SvapiUpdateUserInfoResponse,
    unknown,
    void,
    SvapiUpdateUserInfoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 更新用户信息
 */
export const useUserServiceUpdateUserInfo = (
  props: UseUserServiceUpdateUserInfoProps
) =>
  useMutate<
    SvapiUpdateUserInfoResponse,
    unknown,
    void,
    SvapiUpdateUserInfoRequest,
    void
  >("PUT", `/user/info`, props);

export type UserServiceLoginProps = Omit<
  MutateProps<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>,
  "path" | "verb"
>;

/**
 * 登录
 */
export const UserServiceLogin = (props: UserServiceLoginProps) => (
  <Mutate<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>
    verb="POST"
    path={`/user/login`}
    {...props}
  />
);

export type UseUserServiceLoginProps = Omit<
  UseMutateProps<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>,
  "path" | "verb"
>;

/**
 * 登录
 */
export const useUserServiceLogin = (props: UseUserServiceLoginProps) =>
  useMutate<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>(
    "POST",
    `/user/login`,
    props
  );

export type UserServiceRegisterProps = Omit<
  MutateProps<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>,
  "path" | "verb"
>;

/**
 * 注册
 */
export const UserServiceRegister = (props: UserServiceRegisterProps) => (
  <Mutate<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>
    verb="POST"
    path={`/user/register`}
    {...props}
  />
);

export type UseUserServiceRegisterProps = Omit<
  UseMutateProps<
    SvapiRegisterResponse,
    unknown,
    void,
    SvapiRegisterRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 注册
 */
export const useUserServiceRegister = (props: UseUserServiceRegisterProps) =>
  useMutate<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>(
    "POST",
    `/user/register`,
    props
  );

export type UserServiceBindUserVoucherProps = Omit<
  MutateProps<
    SvapiBindUserVoucherResponse,
    unknown,
    void,
    SvapiBindUserVoucherRequest,
    void
  >,
  "path" | "verb"
>;

export const UserServiceBindUserVoucher = (
  props: UserServiceBindUserVoucherProps
) => (
  <Mutate<
    SvapiBindUserVoucherResponse,
    unknown,
    void,
    SvapiBindUserVoucherRequest,
    void
  >
    verb="POST"
    path={`/user/voucher`}
    {...props}
  />
);

export type UseUserServiceBindUserVoucherProps = Omit<
  UseMutateProps<
    SvapiBindUserVoucherResponse,
    unknown,
    void,
    SvapiBindUserVoucherRequest,
    void
  >,
  "path" | "verb"
>;

export const useUserServiceBindUserVoucher = (
  props: UseUserServiceBindUserVoucherProps
) =>
  useMutate<
    SvapiBindUserVoucherResponse,
    unknown,
    void,
    SvapiBindUserVoucherRequest,
    void
  >("POST", `/user/voucher`, props);

export type UserServiceUnbindUserVoucherProps = Omit<
  MutateProps<
    SvapiUnbindUserVoucherResponse,
    unknown,
    void,
    SvapiUnbindUserVoucherRequest,
    void
  >,
  "path" | "verb"
>;

export const UserServiceUnbindUserVoucher = (
  props: UserServiceUnbindUserVoucherProps
) => (
  <Mutate<
    SvapiUnbindUserVoucherResponse,
    unknown,
    void,
    SvapiUnbindUserVoucherRequest,
    void
  >
    verb="DELETE"
    path={`/user/voucher`}
    {...props}
  />
);

export type UseUserServiceUnbindUserVoucherProps = Omit<
  UseMutateProps<
    SvapiUnbindUserVoucherResponse,
    unknown,
    void,
    SvapiUnbindUserVoucherRequest,
    void
  >,
  "path" | "verb"
>;

export const useUserServiceUnbindUserVoucher = (
  props: UseUserServiceUnbindUserVoucherProps
) =>
  useMutate<
    SvapiUnbindUserVoucherResponse,
    unknown,
    void,
    SvapiUnbindUserVoucherRequest,
    void
  >("DELETE", `/user/voucher`, { ...props });

export type ShortVideoCoreVideoServiceFeedShortVideoProps = Omit<
  MutateProps<
    SvapiFeedShortVideoResponse,
    unknown,
    void,
    SvapiFeedShortVideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 刷视频
 */
export const ShortVideoCoreVideoServiceFeedShortVideo = (
  props: ShortVideoCoreVideoServiceFeedShortVideoProps
) => (
  <Mutate<
    SvapiFeedShortVideoResponse,
    unknown,
    void,
    SvapiFeedShortVideoRequest,
    void
  >
    verb="POST"
    path={`/video/feed`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServiceFeedShortVideoProps = Omit<
  UseMutateProps<
    SvapiFeedShortVideoResponse,
    unknown,
    void,
    SvapiFeedShortVideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 刷视频
 */
export const useShortVideoCoreVideoServiceFeedShortVideo = (
  props: UseShortVideoCoreVideoServiceFeedShortVideoProps
) =>
  useMutate<
    SvapiFeedShortVideoResponse,
    unknown,
    void,
    SvapiFeedShortVideoRequest,
    void
  >("POST", `/video/feed`, props);

export type ShortVideoCoreVideoServiceReportVideoFinishUploadProps = Omit<
  MutateProps<
    SvapiReportVideoFinishUploadResponse,
    unknown,
    void,
    SvapiReportVideoFinishUploadRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 确认视频上传完成
 */
export const ShortVideoCoreVideoServiceReportVideoFinishUpload = (
  props: ShortVideoCoreVideoServiceReportVideoFinishUploadProps
) => (
  <Mutate<
    SvapiReportVideoFinishUploadResponse,
    unknown,
    void,
    SvapiReportVideoFinishUploadRequest,
    void
  >
    verb="POST"
    path={`/video/finish`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServiceReportVideoFinishUploadProps = Omit<
  UseMutateProps<
    SvapiReportVideoFinishUploadResponse,
    unknown,
    void,
    SvapiReportVideoFinishUploadRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 确认视频上传完成
 */
export const useShortVideoCoreVideoServiceReportVideoFinishUpload = (
  props: UseShortVideoCoreVideoServiceReportVideoFinishUploadProps
) =>
  useMutate<
    SvapiReportVideoFinishUploadResponse,
    unknown,
    void,
    SvapiReportVideoFinishUploadRequest,
    void
  >("POST", `/video/finish`, props);

export type ShortVideoCoreVideoServiceListPublishedVideoProps = Omit<
  MutateProps<
    SvapiListPublishedVideoResponse,
    unknown,
    void,
    SvapiListPublishedVideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 获取当前用户的发布视频列表
 */
export const ShortVideoCoreVideoServiceListPublishedVideo = (
  props: ShortVideoCoreVideoServiceListPublishedVideoProps
) => (
  <Mutate<
    SvapiListPublishedVideoResponse,
    unknown,
    void,
    SvapiListPublishedVideoRequest,
    void
  >
    verb="POST"
    path={`/video/list`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServiceListPublishedVideoProps = Omit<
  UseMutateProps<
    SvapiListPublishedVideoResponse,
    unknown,
    void,
    SvapiListPublishedVideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 获取当前用户的发布视频列表
 */
export const useShortVideoCoreVideoServiceListPublishedVideo = (
  props: UseShortVideoCoreVideoServiceListPublishedVideoProps
) =>
  useMutate<
    SvapiListPublishedVideoResponse,
    unknown,
    void,
    SvapiListPublishedVideoRequest,
    void
  >("POST", `/video/list`, props);

export type ShortVideoCoreVideoServicePreSign4UploadVideoProps = Omit<
  MutateProps<
    SvapiPreSign4UploadVideoResponse,
    unknown,
    void,
    SvapiPreSign4UploadVideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 预注册上传视频
 */
export const ShortVideoCoreVideoServicePreSign4UploadVideo = (
  props: ShortVideoCoreVideoServicePreSign4UploadVideoProps
) => (
  <Mutate<
    SvapiPreSign4UploadVideoResponse,
    unknown,
    void,
    SvapiPreSign4UploadVideoRequest,
    void
  >
    verb="POST"
    path={`/video/upload`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServicePreSign4UploadVideoProps = Omit<
  UseMutateProps<
    SvapiPreSign4UploadVideoResponse,
    unknown,
    void,
    SvapiPreSign4UploadVideoRequest,
    void
  >,
  "path" | "verb"
>;

/**
 * 预注册上传视频
 */
export const useShortVideoCoreVideoServicePreSign4UploadVideo = (
  props: UseShortVideoCoreVideoServicePreSign4UploadVideoProps
) =>
  useMutate<
    SvapiPreSign4UploadVideoResponse,
    unknown,
    void,
    SvapiPreSign4UploadVideoRequest,
    void
  >("POST", `/video/upload`, props);

export interface ShortVideoCoreVideoServiceGetVideoByIdPathParams {
  /**
   * @gotags: json:"video_id,omitempty,string"
   */
  videoId: string;
}

export type ShortVideoCoreVideoServiceGetVideoByIdProps = Omit<
  GetProps<
    SvapiGetVideoByIdResponse,
    unknown,
    void,
    ShortVideoCoreVideoServiceGetVideoByIdPathParams
  >,
  "path"
> &
  ShortVideoCoreVideoServiceGetVideoByIdPathParams;

/**
 * 获取视频信息
 */
export const ShortVideoCoreVideoServiceGetVideoById = ({
  videoId,
  ...props
}: ShortVideoCoreVideoServiceGetVideoByIdProps) => (
  <Get<
    SvapiGetVideoByIdResponse,
    unknown,
    void,
    ShortVideoCoreVideoServiceGetVideoByIdPathParams
  >
    path={`/video/${videoId}`}
    {...props}
  />
);

export type UseShortVideoCoreVideoServiceGetVideoByIdProps = Omit<
  UseGetProps<
    SvapiGetVideoByIdResponse,
    unknown,
    void,
    ShortVideoCoreVideoServiceGetVideoByIdPathParams
  >,
  "path"
> &
  ShortVideoCoreVideoServiceGetVideoByIdPathParams;

/**
 * 获取视频信息
 */
export const useShortVideoCoreVideoServiceGetVideoById = ({
  videoId,
  ...props
}: UseShortVideoCoreVideoServiceGetVideoByIdProps) =>
  useGet<
    SvapiGetVideoByIdResponse,
    unknown,
    void,
    ShortVideoCoreVideoServiceGetVideoByIdPathParams
  >(
    (paramsInPath: ShortVideoCoreVideoServiceGetVideoByIdPathParams) =>
      `/video/${paramsInPath.videoId}`,
    { pathParams: { videoId }, ...props }
  );

export type FileServicePreSignUploadingPublicFileProps = Omit<
  MutateProps<
    SvapiPreSignUploadPublicFileResponse,
    unknown,
    void,
    SvapiPreSignUploadPublicFileRequest,
    void
  >,
  "path" | "verb"
>;

export const FileServicePreSignUploadingPublicFile = (
  props: FileServicePreSignUploadingPublicFileProps
) => (
  <Mutate<
    SvapiPreSignUploadPublicFileResponse,
    unknown,
    void,
    SvapiPreSignUploadPublicFileRequest,
    void
  >
    verb="POST"
    path={`file`}
    {...props}
  />
);

export type UseFileServicePreSignUploadingPublicFileProps = Omit<
  UseMutateProps<
    SvapiPreSignUploadPublicFileResponse,
    unknown,
    void,
    SvapiPreSignUploadPublicFileRequest,
    void
  >,
  "path" | "verb"
>;

export const useFileServicePreSignUploadingPublicFile = (
  props: UseFileServicePreSignUploadingPublicFileProps
) =>
  useMutate<
    SvapiPreSignUploadPublicFileResponse,
    unknown,
    void,
    SvapiPreSignUploadPublicFileRequest,
    void
  >("POST", `file`, props);

export type FileServiceReportPublicFileUploadedProps = Omit<
  MutateProps<
    SvapiReportPublicFileUploadedResponse,
    unknown,
    void,
    SvapiReportPublicFileUploadedRequest,
    void
  >,
  "path" | "verb"
>;

export const FileServiceReportPublicFileUploaded = (
  props: FileServiceReportPublicFileUploadedProps
) => (
  <Mutate<
    SvapiReportPublicFileUploadedResponse,
    unknown,
    void,
    SvapiReportPublicFileUploadedRequest,
    void
  >
    verb="POST"
    path={`file/report`}
    {...props}
  />
);

export type UseFileServiceReportPublicFileUploadedProps = Omit<
  UseMutateProps<
    SvapiReportPublicFileUploadedResponse,
    unknown,
    void,
    SvapiReportPublicFileUploadedRequest,
    void
  >,
  "path" | "verb"
>;

export const useFileServiceReportPublicFileUploaded = (
  props: UseFileServiceReportPublicFileUploadedProps
) =>
  useMutate<
    SvapiReportPublicFileUploadedResponse,
    unknown,
    void,
    SvapiReportPublicFileUploadedRequest,
    void
  >("POST", `file/report`, props);
